// Code generated by astgen. DO NOT EDIT.

package ast

// Kind represents the type of an AST node.
type Kind int

const (
	KindAbortBatchStatement                   Kind = 0
	KindAddColumnAction                       Kind = 1
	KindAddColumnIdentifierAction             Kind = 2
	KindAddConstraintAction                   Kind = 3
	KindAddSubEntityAction                    Kind = 4
	KindAddToRestricteeListClause             Kind = 5
	KindAddTtlAction                          Kind = 6
	KindAfterMatchSkipClause                  Kind = 7
	KindAlias                                 Kind = 8
	KindAliasedGroupRows                      Kind = 9
	KindAliasedQueryExpression                Kind = 10
	KindAliasedQueryList                      Kind = 11
	KindAliasedQueryModifiers                 Kind = 12
	KindAliasedQuery                          Kind = 13
	KindAlterActionList                       Kind = 14
	KindAlterAllRowAccessPoliciesStatement    Kind = 15
	KindAlterApproxViewStatement              Kind = 16
	KindAlterColumnDropDefaultAction          Kind = 17
	KindAlterColumnDropGeneratedAction        Kind = 18
	KindAlterColumnDropNotNullAction          Kind = 19
	KindAlterColumnOptionsAction              Kind = 20
	KindAlterColumnSetDefaultAction           Kind = 21
	KindAlterColumnSetGeneratedAction         Kind = 22
	KindAlterColumnTypeAction                 Kind = 23
	KindAlterConnectionStatement              Kind = 24
	KindAlterConstraintEnforcementAction      Kind = 25
	KindAlterConstraintSetOptionsAction       Kind = 26
	KindAlterDatabaseStatement                Kind = 27
	KindAlterEntityStatement                  Kind = 28
	KindAlterExternalSchemaStatement          Kind = 29
	KindAlterIndexStatement                   Kind = 30
	KindAlterMaterializedViewStatement        Kind = 31
	KindAlterModelStatement                   Kind = 32
	KindAlterPrivilegeRestrictionStatement    Kind = 33
	KindAlterRowAccessPolicyStatement         Kind = 34
	KindAlterSchemaStatement                  Kind = 35
	KindAlterSequenceStatement                Kind = 36
	KindAlterSubEntityAction                  Kind = 37
	KindAlterTableStatement                   Kind = 38
	KindAlterViewStatement                    Kind = 39
	KindAnalyticFunctionCall                  Kind = 40
	KindAnalyzeStatement                      Kind = 41
	KindAndExpr                               Kind = 42
	KindAnySomeAllOp                          Kind = 43
	KindArrayColumnSchema                     Kind = 44
	KindArrayConstructor                      Kind = 45
	KindArrayElement                          Kind = 46
	KindArrayType                             Kind = 47
	KindAssertRowsModified                    Kind = 48
	KindAssertStatement                       Kind = 49
	KindAssignmentFromStruct                  Kind = 50
	KindAuxLoadDataFromFilesOptionsList       Kind = 51
	KindAuxLoadDataPartitionsClause           Kind = 52
	KindAuxLoadDataStatement                  Kind = 53
	KindBeginEndBlock                         Kind = 54
	KindBeginStatement                        Kind = 55
	KindBetweenExpression                     Kind = 56
	KindBigNumericLiteral                     Kind = 57
	KindBinaryExpression                      Kind = 58
	KindBitwiseShiftExpression                Kind = 59
	KindBooleanLiteral                        Kind = 60
	KindBoundedQuantifier                     Kind = 61
	KindBracedConstructorField                Kind = 62
	KindBracedConstructorFieldValue           Kind = 63
	KindBracedConstructorLhs                  Kind = 64
	KindBracedConstructor                     Kind = 65
	KindBracedNewConstructor                  Kind = 66
	KindBreakStatement                        Kind = 67
	KindBytesLiteralComponent                 Kind = 68
	KindBytesLiteral                          Kind = 69
	KindCallStatement                         Kind = 70
	KindCaseNoValueExpression                 Kind = 71
	KindCaseStatement                         Kind = 72
	KindCaseValueExpression                   Kind = 73
	KindCastExpression                        Kind = 74
	KindChainedBaseExpr                       Kind = 75
	KindCheckConstraint                       Kind = 76
	KindClampedBetweenModifier                Kind = 77
	KindCloneDataSourceList                   Kind = 78
	KindCloneDataSource                       Kind = 79
	KindCloneDataStatement                    Kind = 80
	KindClusterBy                             Kind = 81
	KindCollate                               Kind = 82
	KindColumnAttributeList                   Kind = 83
	KindColumnDefinition                      Kind = 84
	KindColumnList                            Kind = 85
	KindColumnPosition                        Kind = 86
	KindColumnWithOptionsList                 Kind = 87
	KindColumnWithOptions                     Kind = 88
	KindCommitStatement                       Kind = 89
	KindConcatExpr                            Kind = 90
	KindConnectionClause                      Kind = 91
	KindContinueStatement                     Kind = 92
	KindCopyDataSource                        Kind = 93
	KindCreateApproxViewStatement             Kind = 94
	KindCreateConnectionStatement             Kind = 95
	KindCreateConstantStatement               Kind = 96
	KindCreateDatabaseStatement               Kind = 97
	KindCreateEntityStatement                 Kind = 98
	KindCreateExternalSchemaStatement         Kind = 99
	KindCreateExternalTableStatement          Kind = 100
	KindCreateFunctionStatement               Kind = 101
	KindCreateIndexStatement                  Kind = 102
	KindCreateLocalityGroupStatement          Kind = 103
	KindCreateMaterializedViewStatement       Kind = 104
	KindCreateModelStatement                  Kind = 105
	KindCreatePrivilegeRestrictionStatement   Kind = 106
	KindCreateProcedureStatement              Kind = 107
	KindCreatePropertyGraphStatement          Kind = 108
	KindCreateRowAccessPolicyStatement        Kind = 109
	KindCreateSchemaStatement                 Kind = 110
	KindCreateSequenceStatement               Kind = 111
	KindCreateSnapshotStatement               Kind = 112
	KindCreateSnapshotTableStatement          Kind = 113
	KindCreateTableFunctionStatement          Kind = 114
	KindCreateTableStatement                  Kind = 115
	KindCreateViewStatement                   Kind = 116
	KindCube                                  Kind = 117
	KindDateOrTimeLiteral                     Kind = 118
	KindDefaultLiteral                        Kind = 119
	KindDefineMacroStatement                  Kind = 120
	KindDefineTableStatement                  Kind = 121
	KindDeleteStatement                       Kind = 122
	KindDescribeStatement                     Kind = 123
	KindDescriptorColumnList                  Kind = 124
	KindDescriptorColumn                      Kind = 125
	KindDescriptor                            Kind = 126
	KindDotGeneralizedField                   Kind = 127
	KindDotIdentifier                         Kind = 128
	KindDotStar                               Kind = 129
	KindDotStarWithModifiers                  Kind = 130
	KindDropAllRowAccessPoliciesStatement     Kind = 131
	KindDropColumnAction                      Kind = 132
	KindDropConstraintAction                  Kind = 133
	KindDropEntityStatement                   Kind = 134
	KindDropFunctionStatement                 Kind = 135
	KindDropMaterializedViewStatement         Kind = 136
	KindDropPrimaryKeyAction                  Kind = 137
	KindDropPrivilegeRestrictionStatement     Kind = 138
	KindDropRowAccessPolicyStatement          Kind = 139
	KindDropSearchIndexStatement              Kind = 140
	KindDropSnapshotTableStatement            Kind = 141
	KindDropStatement                         Kind = 142
	KindDropSubEntityAction                   Kind = 143
	KindDropTableFunctionStatement            Kind = 144
	KindDropTtlAction                         Kind = 145
	KindDropVectorIndexStatement              Kind = 146
	KindElseifClauseList                      Kind = 147
	KindElseifClause                          Kind = 148
	KindEmptyRowPattern                       Kind = 149
	KindExceptionHandlerList                  Kind = 150
	KindExceptionHandler                      Kind = 151
	KindExecuteImmediateStatement             Kind = 152
	KindExecuteIntoClause                     Kind = 153
	KindExecuteUsingArgument                  Kind = 154
	KindExecuteUsingClause                    Kind = 155
	KindExplainStatement                      Kind = 156
	KindExportDataStatement                   Kind = 157
	KindExportMetadataStatement               Kind = 158
	KindExportModelStatement                  Kind = 159
	KindExpressionSubquery                    Kind = 160
	KindExpressionWithAlias                   Kind = 161
	KindExpressionWithOptAlias                Kind = 162
	KindExtendedPathExpression                Kind = 163
	KindExtractExpression                     Kind = 164
	KindFilterFieldsArg                       Kind = 165
	KindFilterUsingClause                     Kind = 166
	KindFixedQuantifier                       Kind = 167
	KindFloatLiteral                          Kind = 168
	KindForInStatement                        Kind = 169
	KindForSystemTime                         Kind = 170
	KindForeignKeyActions                     Kind = 171
	KindForeignKeyColumnAttribute             Kind = 172
	KindForeignKey                            Kind = 173
	KindForeignKeyReference                   Kind = 174
	KindFormatClause                          Kind = 175
	KindFromClause                            Kind = 176
	KindFromQuery                             Kind = 177
	KindFunctionCall                          Kind = 178
	KindFunctionDeclaration                   Kind = 179
	KindFunctionParameter                     Kind = 180
	KindFunctionParameters                    Kind = 181
	KindFunctionTypeArgList                   Kind = 182
	KindFunctionType                          Kind = 183
	KindGeneratedColumnInfo                   Kind = 184
	KindGqlFilter                             Kind = 185
	KindGqlFor                                Kind = 186
	KindGqlGraphPatternQuery                  Kind = 187
	KindGqlInlineSubqueryCall                 Kind = 188
	KindGqlLet                                Kind = 189
	KindGqlLetVariableDefinitionList          Kind = 190
	KindGqlLetVariableDefinition              Kind = 191
	KindGqlLinearOpsQuery                     Kind = 192
	KindGqlMatch                              Kind = 193
	KindGqlNamedCall                          Kind = 194
	KindGqlOperatorList                       Kind = 195
	KindGqlOrderByAndPage                     Kind = 196
	KindGqlPageLimit                          Kind = 197
	KindGqlPage                               Kind = 198
	KindGqlPageOffset                         Kind = 199
	KindGqlQuery                              Kind = 200
	KindGqlReturn                             Kind = 201
	KindGqlSample                             Kind = 202
	KindGqlSetOperation                       Kind = 203
	KindGqlWith                               Kind = 204
	KindGrantStatement                        Kind = 205
	KindGrantToClause                         Kind = 206
	KindGranteeList                           Kind = 207
	KindGraphDerivedPropertyList              Kind = 208
	KindGraphDerivedProperty                  Kind = 209
	KindGraphDynamicLabel                     Kind = 210
	KindGraphDynamicProperties                Kind = 211
	KindGraphEdgePattern                      Kind = 212
	KindGraphElementLabelAndPropertiesList    Kind = 213
	KindGraphElementLabelAndProperties        Kind = 214
	KindGraphElementLabel                     Kind = 215
	KindGraphElementPatternFiller             Kind = 216
	KindGraphElementTableList                 Kind = 217
	KindGraphElementTable                     Kind = 218
	KindGraphIsLabeledPredicate               Kind = 219
	KindGraphLabelFilter                      Kind = 220
	KindGraphLabelOperation                   Kind = 221
	KindGraphLhsHint                          Kind = 222
	KindGraphNodePattern                      Kind = 223
	KindGraphNodeTableReference               Kind = 224
	KindGraphPathMode                         Kind = 225
	KindGraphPathPattern                      Kind = 226
	KindGraphPathSearchPrefixCount            Kind = 227
	KindGraphPathSearchPrefix                 Kind = 228
	KindGraphPattern                          Kind = 229
	KindGraphProperties                       Kind = 230
	KindGraphPropertyNameAndValue             Kind = 231
	KindGraphPropertySpecification            Kind = 232
	KindGraphRhsHint                          Kind = 233
	KindGraphTableQuery                       Kind = 234
	KindGraphWildcardLabel                    Kind = 235
	KindGroupByAll                            Kind = 236
	KindGroupBy                               Kind = 237
	KindGroupingItem                          Kind = 238
	KindGroupingItemOrder                     Kind = 239
	KindGroupingSetList                       Kind = 240
	KindGroupingSet                           Kind = 241
	KindHavingModifier                        Kind = 242
	KindHaving                                Kind = 243
	KindHiddenColumnAttribute                 Kind = 244
	KindHintEntry                             Kind = 245
	KindHint                                  Kind = 246
	KindHintedStatement                       Kind = 247
	KindIdentifierList                        Kind = 248
	KindIdentifier                            Kind = 249
	KindIdentityColumnIncrementBy             Kind = 250
	KindIdentityColumnInfo                    Kind = 251
	KindIdentityColumnMaxValue                Kind = 252
	KindIdentityColumnMinValue                Kind = 253
	KindIdentityColumnStartWith               Kind = 254
	KindIfStatement                           Kind = 255
	KindImportStatement                       Kind = 256
	KindInExpression                          Kind = 257
	KindInList                                Kind = 258
	KindIndexAllColumns                       Kind = 259
	KindIndexItemList                         Kind = 260
	KindIndexStoringExpressionList            Kind = 261
	KindIndexUnnestExpressionList             Kind = 262
	KindInferredTypeColumnSchema              Kind = 263
	KindInputOutputClause                     Kind = 264
	KindInputTableArgument                    Kind = 265
	KindInsertStatement                       Kind = 266
	KindInsertValuesRowList                   Kind = 267
	KindInsertValuesRow                       Kind = 268
	KindIntLiteral                            Kind = 269
	KindIntOrUnbounded                        Kind = 270
	KindIntervalExpr                          Kind = 271
	KindIntoAlias                             Kind = 272
	KindJSONLiteral                           Kind = 273
	KindJoin                                  Kind = 274
	KindLabel                                 Kind = 275
	KindLambda                                Kind = 276
	KindLikeExpression                        Kind = 277
	KindLimitAll                              Kind = 278
	KindLimit                                 Kind = 279
	KindLimitOffset                           Kind = 280
	KindLocation                              Kind = 281
	KindLockMode                              Kind = 282
	KindMacroBody                             Kind = 283
	KindMapType                               Kind = 284
	KindMatchRecognizeClause                  Kind = 285
	KindMaxLiteral                            Kind = 286
	KindMergeAction                           Kind = 287
	KindMergeStatement                        Kind = 288
	KindMergeWhenClauseList                   Kind = 289
	KindMergeWhenClause                       Kind = 290
	KindModelClause                           Kind = 291
	KindModuleStatement                       Kind = 292
	KindNamedArgument                         Kind = 293
	KindNewConstructorArg                     Kind = 294
	KindNewConstructor                        Kind = 295
	KindNotNullColumnAttribute                Kind = 296
	KindNullLiteral                           Kind = 297
	KindNullOrder                             Kind = 298
	KindNumericLiteral                        Kind = 299
	KindOnClause                              Kind = 300
	KindOnConflictClause                      Kind = 301
	KindOnOrUsingClauseList                   Kind = 302
	KindOptionsEntry                          Kind = 303
	KindOptionsList                           Kind = 304
	KindOrExpr                                Kind = 305
	KindOrderBy                               Kind = 306
	KindOrderingExpression                    Kind = 307
	KindParameterAssignment                   Kind = 308
	KindParameterExpr                         Kind = 309
	KindParenthesizedJoin                     Kind = 310
	KindPartitionBy                           Kind = 311
	KindPathExpressionList                    Kind = 312
	KindPathExpression                        Kind = 313
	KindPipeAggregate                         Kind = 314
	KindPipeAs                                Kind = 315
	KindPipeAssert                            Kind = 316
	KindPipeCall                              Kind = 317
	KindPipeCreateTable                       Kind = 318
	KindPipeDescribe                          Kind = 319
	KindPipeDistinct                          Kind = 320
	KindPipeDrop                              Kind = 321
	KindPipeExportData                        Kind = 322
	KindPipeExtend                            Kind = 323
	KindPipeFork                              Kind = 324
	KindPipeIfCase                            Kind = 325
	KindPipeIf                                Kind = 326
	KindPipeInsert                            Kind = 327
	KindPipeJoinLhsPlaceholder                Kind = 328
	KindPipeJoin                              Kind = 329
	KindPipeLimitOffset                       Kind = 330
	KindPipeLog                               Kind = 331
	KindPipeMatchRecognize                    Kind = 332
	KindPipeOrderBy                           Kind = 333
	KindPipePivot                             Kind = 334
	KindPipeRecursiveUnion                    Kind = 335
	KindPipeRenameItem                        Kind = 336
	KindPipeRename                            Kind = 337
	KindPipeSelect                            Kind = 338
	KindPipeSetItem                           Kind = 339
	KindPipeSet                               Kind = 340
	KindPipeSetOperation                      Kind = 341
	KindPipeStaticDescribe                    Kind = 342
	KindPipeTablesample                       Kind = 343
	KindPipeTee                               Kind = 344
	KindPipeUnpivot                           Kind = 345
	KindPipeWhere                             Kind = 346
	KindPipeWindow                            Kind = 347
	KindPipeWith                              Kind = 348
	KindPivotClause                           Kind = 349
	KindPivotExpressionList                   Kind = 350
	KindPivotExpression                       Kind = 351
	KindPivotValueList                        Kind = 352
	KindPivotValue                            Kind = 353
	KindPrimaryKeyColumnAttribute             Kind = 354
	KindPrimaryKeyElementList                 Kind = 355
	KindPrimaryKeyElement                     Kind = 356
	KindPrimaryKey                            Kind = 357
	KindPrivilege                             Kind = 358
	KindPrivileges                            Kind = 359
	KindQualify                               Kind = 360
	KindQuantifierBound                       Kind = 361
	KindQuery                                 Kind = 362
	KindQueryStatement                        Kind = 363
	KindRaiseStatement                        Kind = 364
	KindRangeColumnSchema                     Kind = 365
	KindRangeLiteral                          Kind = 366
	KindRangeType                             Kind = 367
	KindRebuildAction                         Kind = 368
	KindRecursionDepthModifier                Kind = 369
	KindRemoveFromRestricteeListClause        Kind = 370
	KindRenameColumnAction                    Kind = 371
	KindRenameStatement                       Kind = 372
	KindRenameToClause                        Kind = 373
	KindRepeatStatement                       Kind = 374
	KindRepeatableClause                      Kind = 375
	KindReplaceFieldsArg                      Kind = 376
	KindReplaceFieldsExpression               Kind = 377
	KindReplaceTtlAction                      Kind = 378
	KindRestrictToClause                      Kind = 379
	KindReturnStatement                       Kind = 380
	KindReturningClause                       Kind = 381
	KindRevokeFromClause                      Kind = 382
	KindRevokeStatement                       Kind = 383
	KindRollbackStatement                     Kind = 384
	KindRollup                                Kind = 385
	KindRowPatternAnchor                      Kind = 386
	KindRowPatternOperation                   Kind = 387
	KindRowPatternQuantification              Kind = 388
	KindRowPatternVariable                    Kind = 389
	KindRunBatchStatement                     Kind = 390
	KindRunStatement                          Kind = 391
	KindSampleClause                          Kind = 392
	KindSampleSize                            Kind = 393
	KindSampleSuffix                          Kind = 394
	KindScript                                Kind = 395
	KindSelectAs                              Kind = 396
	KindSelectColumn                          Kind = 397
	KindSelectList                            Kind = 398
	KindSelect                                Kind = 399
	KindSequenceArg                           Kind = 400
	KindSetAsAction                           Kind = 401
	KindSetCollateClause                      Kind = 402
	KindSetOperationAllOrDistinct             Kind = 403
	KindSetOperationColumnMatchMode           Kind = 404
	KindSetOperationColumnPropagationMode     Kind = 405
	KindSetOperationMetadataList              Kind = 406
	KindSetOperationMetadata                  Kind = 407
	KindSetOperation                          Kind = 408
	KindSetOperationType                      Kind = 409
	KindSetOptionsAction                      Kind = 410
	KindSetTransactionStatement               Kind = 411
	KindShowStatement                         Kind = 412
	KindSimpleColumnSchema                    Kind = 413
	KindSimpleType                            Kind = 414
	KindSingleAssignment                      Kind = 415
	KindSpannerAlterColumnAction              Kind = 416
	KindSpannerInterleaveClause               Kind = 417
	KindSpannerSetOnDeleteAction              Kind = 418
	KindSpannerTableOptions                   Kind = 419
	KindSqlFunctionBody                       Kind = 420
	KindStarExceptList                        Kind = 421
	KindStarModifiers                         Kind = 422
	KindStar                                  Kind = 423
	KindStarReplaceItem                       Kind = 424
	KindStarWithModifiers                     Kind = 425
	KindStartBatchStatement                   Kind = 426
	KindStatementList                         Kind = 427
	KindStatementWithPipeOperators            Kind = 428
	KindStringLiteralComponent                Kind = 429
	KindStringLiteral                         Kind = 430
	KindStructBracedConstructor               Kind = 431
	KindStructColumnField                     Kind = 432
	KindStructColumnSchema                    Kind = 433
	KindStructConstructorArg                  Kind = 434
	KindStructConstructorWithKeyword          Kind = 435
	KindStructConstructorWithParens           Kind = 436
	KindStructField                           Kind = 437
	KindStructType                            Kind = 438
	KindSubpipeline                           Kind = 439
	KindSubpipelineStatement                  Kind = 440
	KindSymbolQuantifier                      Kind = 441
	KindSystemVariableAssignment              Kind = 442
	KindSystemVariableExpr                    Kind = 443
	KindTVFArgument                           Kind = 444
	KindTVF                                   Kind = 445
	KindTVFSchemaColumn                       Kind = 446
	KindTVFSchema                             Kind = 447
	KindTableAndColumnInfoList                Kind = 448
	KindTableAndColumnInfo                    Kind = 449
	KindTableClause                           Kind = 450
	KindTableElementList                      Kind = 451
	KindTablePathExpression                   Kind = 452
	KindTableSubquery                         Kind = 453
	KindTemplatedParameterType                Kind = 454
	KindTransactionIsolationLevel             Kind = 455
	KindTransactionModeList                   Kind = 456
	KindTransactionReadWriteMode              Kind = 457
	KindTransformClause                       Kind = 458
	KindTruncateStatement                     Kind = 459
	KindTtlClause                             Kind = 460
	KindTypeParameterList                     Kind = 461
	KindUnaryExpression                       Kind = 462
	KindUndropStatement                       Kind = 463
	KindUnnestExpression                      Kind = 464
	KindUnnestExpressionWithOptAliasAndOffset Kind = 465
	KindUnpivotClause                         Kind = 466
	KindUnpivotInItemLabel                    Kind = 467
	KindUnpivotInItemList                     Kind = 468
	KindUnpivotInItem                         Kind = 469
	KindUntilClause                           Kind = 470
	KindUpdateConstructor                     Kind = 471
	KindUpdateItemList                        Kind = 472
	KindUpdateItem                            Kind = 473
	KindUpdateSetValue                        Kind = 474
	KindUpdateStatement                       Kind = 475
	KindUsingClause                           Kind = 476
	KindVariableDeclaration                   Kind = 477
	KindWhenThenClauseList                    Kind = 478
	KindWhenThenClause                        Kind = 479
	KindWhereClause                           Kind = 480
	KindWhileStatement                        Kind = 481
	KindWindowClause                          Kind = 482
	KindWindowDefinition                      Kind = 483
	KindWindowFrameExpr                       Kind = 484
	KindWindowFrame                           Kind = 485
	KindWindowSpecification                   Kind = 486
	KindWithClauseEntry                       Kind = 487
	KindWithClause                            Kind = 488
	KindWithConnectionClause                  Kind = 489
	KindWithExpression                        Kind = 490
	KindWithModifier                          Kind = 491
	KindWithOffset                            Kind = 492
	KindWithPartitionColumnsClause            Kind = 493
	KindWithReportModifier                    Kind = 494
	KindWithWeight                            Kind = 495
	KindYieldItemList                         Kind = 496
)

var kindNames = [...]string{
	KindAbortBatchStatement:                   "KindAbortBatchStatement",
	KindAddColumnAction:                       "KindAddColumnAction",
	KindAddColumnIdentifierAction:             "KindAddColumnIdentifierAction",
	KindAddConstraintAction:                   "KindAddConstraintAction",
	KindAddSubEntityAction:                    "KindAddSubEntityAction",
	KindAddToRestricteeListClause:             "KindAddToRestricteeListClause",
	KindAddTtlAction:                          "KindAddTtlAction",
	KindAfterMatchSkipClause:                  "KindAfterMatchSkipClause",
	KindAlias:                                 "KindAlias",
	KindAliasedGroupRows:                      "KindAliasedGroupRows",
	KindAliasedQueryExpression:                "KindAliasedQueryExpression",
	KindAliasedQueryList:                      "KindAliasedQueryList",
	KindAliasedQueryModifiers:                 "KindAliasedQueryModifiers",
	KindAliasedQuery:                          "KindAliasedQuery",
	KindAlterActionList:                       "KindAlterActionList",
	KindAlterAllRowAccessPoliciesStatement:    "KindAlterAllRowAccessPoliciesStatement",
	KindAlterApproxViewStatement:              "KindAlterApproxViewStatement",
	KindAlterColumnDropDefaultAction:          "KindAlterColumnDropDefaultAction",
	KindAlterColumnDropGeneratedAction:        "KindAlterColumnDropGeneratedAction",
	KindAlterColumnDropNotNullAction:          "KindAlterColumnDropNotNullAction",
	KindAlterColumnOptionsAction:              "KindAlterColumnOptionsAction",
	KindAlterColumnSetDefaultAction:           "KindAlterColumnSetDefaultAction",
	KindAlterColumnSetGeneratedAction:         "KindAlterColumnSetGeneratedAction",
	KindAlterColumnTypeAction:                 "KindAlterColumnTypeAction",
	KindAlterConnectionStatement:              "KindAlterConnectionStatement",
	KindAlterConstraintEnforcementAction:      "KindAlterConstraintEnforcementAction",
	KindAlterConstraintSetOptionsAction:       "KindAlterConstraintSetOptionsAction",
	KindAlterDatabaseStatement:                "KindAlterDatabaseStatement",
	KindAlterEntityStatement:                  "KindAlterEntityStatement",
	KindAlterExternalSchemaStatement:          "KindAlterExternalSchemaStatement",
	KindAlterIndexStatement:                   "KindAlterIndexStatement",
	KindAlterMaterializedViewStatement:        "KindAlterMaterializedViewStatement",
	KindAlterModelStatement:                   "KindAlterModelStatement",
	KindAlterPrivilegeRestrictionStatement:    "KindAlterPrivilegeRestrictionStatement",
	KindAlterRowAccessPolicyStatement:         "KindAlterRowAccessPolicyStatement",
	KindAlterSchemaStatement:                  "KindAlterSchemaStatement",
	KindAlterSequenceStatement:                "KindAlterSequenceStatement",
	KindAlterSubEntityAction:                  "KindAlterSubEntityAction",
	KindAlterTableStatement:                   "KindAlterTableStatement",
	KindAlterViewStatement:                    "KindAlterViewStatement",
	KindAnalyticFunctionCall:                  "KindAnalyticFunctionCall",
	KindAnalyzeStatement:                      "KindAnalyzeStatement",
	KindAndExpr:                               "KindAndExpr",
	KindAnySomeAllOp:                          "KindAnySomeAllOp",
	KindArrayColumnSchema:                     "KindArrayColumnSchema",
	KindArrayConstructor:                      "KindArrayConstructor",
	KindArrayElement:                          "KindArrayElement",
	KindArrayType:                             "KindArrayType",
	KindAssertRowsModified:                    "KindAssertRowsModified",
	KindAssertStatement:                       "KindAssertStatement",
	KindAssignmentFromStruct:                  "KindAssignmentFromStruct",
	KindAuxLoadDataFromFilesOptionsList:       "KindAuxLoadDataFromFilesOptionsList",
	KindAuxLoadDataPartitionsClause:           "KindAuxLoadDataPartitionsClause",
	KindAuxLoadDataStatement:                  "KindAuxLoadDataStatement",
	KindBeginEndBlock:                         "KindBeginEndBlock",
	KindBeginStatement:                        "KindBeginStatement",
	KindBetweenExpression:                     "KindBetweenExpression",
	KindBigNumericLiteral:                     "KindBigNumericLiteral",
	KindBinaryExpression:                      "KindBinaryExpression",
	KindBitwiseShiftExpression:                "KindBitwiseShiftExpression",
	KindBooleanLiteral:                        "KindBooleanLiteral",
	KindBoundedQuantifier:                     "KindBoundedQuantifier",
	KindBracedConstructorField:                "KindBracedConstructorField",
	KindBracedConstructorFieldValue:           "KindBracedConstructorFieldValue",
	KindBracedConstructorLhs:                  "KindBracedConstructorLhs",
	KindBracedConstructor:                     "KindBracedConstructor",
	KindBracedNewConstructor:                  "KindBracedNewConstructor",
	KindBreakStatement:                        "KindBreakStatement",
	KindBytesLiteralComponent:                 "KindBytesLiteralComponent",
	KindBytesLiteral:                          "KindBytesLiteral",
	KindCallStatement:                         "KindCallStatement",
	KindCaseNoValueExpression:                 "KindCaseNoValueExpression",
	KindCaseStatement:                         "KindCaseStatement",
	KindCaseValueExpression:                   "KindCaseValueExpression",
	KindCastExpression:                        "KindCastExpression",
	KindChainedBaseExpr:                       "KindChainedBaseExpr",
	KindCheckConstraint:                       "KindCheckConstraint",
	KindClampedBetweenModifier:                "KindClampedBetweenModifier",
	KindCloneDataSourceList:                   "KindCloneDataSourceList",
	KindCloneDataSource:                       "KindCloneDataSource",
	KindCloneDataStatement:                    "KindCloneDataStatement",
	KindClusterBy:                             "KindClusterBy",
	KindCollate:                               "KindCollate",
	KindColumnAttributeList:                   "KindColumnAttributeList",
	KindColumnDefinition:                      "KindColumnDefinition",
	KindColumnList:                            "KindColumnList",
	KindColumnPosition:                        "KindColumnPosition",
	KindColumnWithOptionsList:                 "KindColumnWithOptionsList",
	KindColumnWithOptions:                     "KindColumnWithOptions",
	KindCommitStatement:                       "KindCommitStatement",
	KindConcatExpr:                            "KindConcatExpr",
	KindConnectionClause:                      "KindConnectionClause",
	KindContinueStatement:                     "KindContinueStatement",
	KindCopyDataSource:                        "KindCopyDataSource",
	KindCreateApproxViewStatement:             "KindCreateApproxViewStatement",
	KindCreateConnectionStatement:             "KindCreateConnectionStatement",
	KindCreateConstantStatement:               "KindCreateConstantStatement",
	KindCreateDatabaseStatement:               "KindCreateDatabaseStatement",
	KindCreateEntityStatement:                 "KindCreateEntityStatement",
	KindCreateExternalSchemaStatement:         "KindCreateExternalSchemaStatement",
	KindCreateExternalTableStatement:          "KindCreateExternalTableStatement",
	KindCreateFunctionStatement:               "KindCreateFunctionStatement",
	KindCreateIndexStatement:                  "KindCreateIndexStatement",
	KindCreateLocalityGroupStatement:          "KindCreateLocalityGroupStatement",
	KindCreateMaterializedViewStatement:       "KindCreateMaterializedViewStatement",
	KindCreateModelStatement:                  "KindCreateModelStatement",
	KindCreatePrivilegeRestrictionStatement:   "KindCreatePrivilegeRestrictionStatement",
	KindCreateProcedureStatement:              "KindCreateProcedureStatement",
	KindCreatePropertyGraphStatement:          "KindCreatePropertyGraphStatement",
	KindCreateRowAccessPolicyStatement:        "KindCreateRowAccessPolicyStatement",
	KindCreateSchemaStatement:                 "KindCreateSchemaStatement",
	KindCreateSequenceStatement:               "KindCreateSequenceStatement",
	KindCreateSnapshotStatement:               "KindCreateSnapshotStatement",
	KindCreateSnapshotTableStatement:          "KindCreateSnapshotTableStatement",
	KindCreateTableFunctionStatement:          "KindCreateTableFunctionStatement",
	KindCreateTableStatement:                  "KindCreateTableStatement",
	KindCreateViewStatement:                   "KindCreateViewStatement",
	KindCube:                                  "KindCube",
	KindDateOrTimeLiteral:                     "KindDateOrTimeLiteral",
	KindDefaultLiteral:                        "KindDefaultLiteral",
	KindDefineMacroStatement:                  "KindDefineMacroStatement",
	KindDefineTableStatement:                  "KindDefineTableStatement",
	KindDeleteStatement:                       "KindDeleteStatement",
	KindDescribeStatement:                     "KindDescribeStatement",
	KindDescriptorColumnList:                  "KindDescriptorColumnList",
	KindDescriptorColumn:                      "KindDescriptorColumn",
	KindDescriptor:                            "KindDescriptor",
	KindDotGeneralizedField:                   "KindDotGeneralizedField",
	KindDotIdentifier:                         "KindDotIdentifier",
	KindDotStar:                               "KindDotStar",
	KindDotStarWithModifiers:                  "KindDotStarWithModifiers",
	KindDropAllRowAccessPoliciesStatement:     "KindDropAllRowAccessPoliciesStatement",
	KindDropColumnAction:                      "KindDropColumnAction",
	KindDropConstraintAction:                  "KindDropConstraintAction",
	KindDropEntityStatement:                   "KindDropEntityStatement",
	KindDropFunctionStatement:                 "KindDropFunctionStatement",
	KindDropMaterializedViewStatement:         "KindDropMaterializedViewStatement",
	KindDropPrimaryKeyAction:                  "KindDropPrimaryKeyAction",
	KindDropPrivilegeRestrictionStatement:     "KindDropPrivilegeRestrictionStatement",
	KindDropRowAccessPolicyStatement:          "KindDropRowAccessPolicyStatement",
	KindDropSearchIndexStatement:              "KindDropSearchIndexStatement",
	KindDropSnapshotTableStatement:            "KindDropSnapshotTableStatement",
	KindDropStatement:                         "KindDropStatement",
	KindDropSubEntityAction:                   "KindDropSubEntityAction",
	KindDropTableFunctionStatement:            "KindDropTableFunctionStatement",
	KindDropTtlAction:                         "KindDropTtlAction",
	KindDropVectorIndexStatement:              "KindDropVectorIndexStatement",
	KindElseifClauseList:                      "KindElseifClauseList",
	KindElseifClause:                          "KindElseifClause",
	KindEmptyRowPattern:                       "KindEmptyRowPattern",
	KindExceptionHandlerList:                  "KindExceptionHandlerList",
	KindExceptionHandler:                      "KindExceptionHandler",
	KindExecuteImmediateStatement:             "KindExecuteImmediateStatement",
	KindExecuteIntoClause:                     "KindExecuteIntoClause",
	KindExecuteUsingArgument:                  "KindExecuteUsingArgument",
	KindExecuteUsingClause:                    "KindExecuteUsingClause",
	KindExplainStatement:                      "KindExplainStatement",
	KindExportDataStatement:                   "KindExportDataStatement",
	KindExportMetadataStatement:               "KindExportMetadataStatement",
	KindExportModelStatement:                  "KindExportModelStatement",
	KindExpressionSubquery:                    "KindExpressionSubquery",
	KindExpressionWithAlias:                   "KindExpressionWithAlias",
	KindExpressionWithOptAlias:                "KindExpressionWithOptAlias",
	KindExtendedPathExpression:                "KindExtendedPathExpression",
	KindExtractExpression:                     "KindExtractExpression",
	KindFilterFieldsArg:                       "KindFilterFieldsArg",
	KindFilterUsingClause:                     "KindFilterUsingClause",
	KindFixedQuantifier:                       "KindFixedQuantifier",
	KindFloatLiteral:                          "KindFloatLiteral",
	KindForInStatement:                        "KindForInStatement",
	KindForSystemTime:                         "KindForSystemTime",
	KindForeignKeyActions:                     "KindForeignKeyActions",
	KindForeignKeyColumnAttribute:             "KindForeignKeyColumnAttribute",
	KindForeignKey:                            "KindForeignKey",
	KindForeignKeyReference:                   "KindForeignKeyReference",
	KindFormatClause:                          "KindFormatClause",
	KindFromClause:                            "KindFromClause",
	KindFromQuery:                             "KindFromQuery",
	KindFunctionCall:                          "KindFunctionCall",
	KindFunctionDeclaration:                   "KindFunctionDeclaration",
	KindFunctionParameter:                     "KindFunctionParameter",
	KindFunctionParameters:                    "KindFunctionParameters",
	KindFunctionTypeArgList:                   "KindFunctionTypeArgList",
	KindFunctionType:                          "KindFunctionType",
	KindGeneratedColumnInfo:                   "KindGeneratedColumnInfo",
	KindGqlFilter:                             "KindGqlFilter",
	KindGqlFor:                                "KindGqlFor",
	KindGqlGraphPatternQuery:                  "KindGqlGraphPatternQuery",
	KindGqlInlineSubqueryCall:                 "KindGqlInlineSubqueryCall",
	KindGqlLet:                                "KindGqlLet",
	KindGqlLetVariableDefinitionList:          "KindGqlLetVariableDefinitionList",
	KindGqlLetVariableDefinition:              "KindGqlLetVariableDefinition",
	KindGqlLinearOpsQuery:                     "KindGqlLinearOpsQuery",
	KindGqlMatch:                              "KindGqlMatch",
	KindGqlNamedCall:                          "KindGqlNamedCall",
	KindGqlOperatorList:                       "KindGqlOperatorList",
	KindGqlOrderByAndPage:                     "KindGqlOrderByAndPage",
	KindGqlPageLimit:                          "KindGqlPageLimit",
	KindGqlPage:                               "KindGqlPage",
	KindGqlPageOffset:                         "KindGqlPageOffset",
	KindGqlQuery:                              "KindGqlQuery",
	KindGqlReturn:                             "KindGqlReturn",
	KindGqlSample:                             "KindGqlSample",
	KindGqlSetOperation:                       "KindGqlSetOperation",
	KindGqlWith:                               "KindGqlWith",
	KindGrantStatement:                        "KindGrantStatement",
	KindGrantToClause:                         "KindGrantToClause",
	KindGranteeList:                           "KindGranteeList",
	KindGraphDerivedPropertyList:              "KindGraphDerivedPropertyList",
	KindGraphDerivedProperty:                  "KindGraphDerivedProperty",
	KindGraphDynamicLabel:                     "KindGraphDynamicLabel",
	KindGraphDynamicProperties:                "KindGraphDynamicProperties",
	KindGraphEdgePattern:                      "KindGraphEdgePattern",
	KindGraphElementLabelAndPropertiesList:    "KindGraphElementLabelAndPropertiesList",
	KindGraphElementLabelAndProperties:        "KindGraphElementLabelAndProperties",
	KindGraphElementLabel:                     "KindGraphElementLabel",
	KindGraphElementPatternFiller:             "KindGraphElementPatternFiller",
	KindGraphElementTableList:                 "KindGraphElementTableList",
	KindGraphElementTable:                     "KindGraphElementTable",
	KindGraphIsLabeledPredicate:               "KindGraphIsLabeledPredicate",
	KindGraphLabelFilter:                      "KindGraphLabelFilter",
	KindGraphLabelOperation:                   "KindGraphLabelOperation",
	KindGraphLhsHint:                          "KindGraphLhsHint",
	KindGraphNodePattern:                      "KindGraphNodePattern",
	KindGraphNodeTableReference:               "KindGraphNodeTableReference",
	KindGraphPathMode:                         "KindGraphPathMode",
	KindGraphPathPattern:                      "KindGraphPathPattern",
	KindGraphPathSearchPrefixCount:            "KindGraphPathSearchPrefixCount",
	KindGraphPathSearchPrefix:                 "KindGraphPathSearchPrefix",
	KindGraphPattern:                          "KindGraphPattern",
	KindGraphProperties:                       "KindGraphProperties",
	KindGraphPropertyNameAndValue:             "KindGraphPropertyNameAndValue",
	KindGraphPropertySpecification:            "KindGraphPropertySpecification",
	KindGraphRhsHint:                          "KindGraphRhsHint",
	KindGraphTableQuery:                       "KindGraphTableQuery",
	KindGraphWildcardLabel:                    "KindGraphWildcardLabel",
	KindGroupByAll:                            "KindGroupByAll",
	KindGroupBy:                               "KindGroupBy",
	KindGroupingItem:                          "KindGroupingItem",
	KindGroupingItemOrder:                     "KindGroupingItemOrder",
	KindGroupingSetList:                       "KindGroupingSetList",
	KindGroupingSet:                           "KindGroupingSet",
	KindHavingModifier:                        "KindHavingModifier",
	KindHaving:                                "KindHaving",
	KindHiddenColumnAttribute:                 "KindHiddenColumnAttribute",
	KindHintEntry:                             "KindHintEntry",
	KindHint:                                  "KindHint",
	KindHintedStatement:                       "KindHintedStatement",
	KindIdentifierList:                        "KindIdentifierList",
	KindIdentifier:                            "KindIdentifier",
	KindIdentityColumnIncrementBy:             "KindIdentityColumnIncrementBy",
	KindIdentityColumnInfo:                    "KindIdentityColumnInfo",
	KindIdentityColumnMaxValue:                "KindIdentityColumnMaxValue",
	KindIdentityColumnMinValue:                "KindIdentityColumnMinValue",
	KindIdentityColumnStartWith:               "KindIdentityColumnStartWith",
	KindIfStatement:                           "KindIfStatement",
	KindImportStatement:                       "KindImportStatement",
	KindInExpression:                          "KindInExpression",
	KindInList:                                "KindInList",
	KindIndexAllColumns:                       "KindIndexAllColumns",
	KindIndexItemList:                         "KindIndexItemList",
	KindIndexStoringExpressionList:            "KindIndexStoringExpressionList",
	KindIndexUnnestExpressionList:             "KindIndexUnnestExpressionList",
	KindInferredTypeColumnSchema:              "KindInferredTypeColumnSchema",
	KindInputOutputClause:                     "KindInputOutputClause",
	KindInputTableArgument:                    "KindInputTableArgument",
	KindInsertStatement:                       "KindInsertStatement",
	KindInsertValuesRowList:                   "KindInsertValuesRowList",
	KindInsertValuesRow:                       "KindInsertValuesRow",
	KindIntLiteral:                            "KindIntLiteral",
	KindIntOrUnbounded:                        "KindIntOrUnbounded",
	KindIntervalExpr:                          "KindIntervalExpr",
	KindIntoAlias:                             "KindIntoAlias",
	KindJSONLiteral:                           "KindJSONLiteral",
	KindJoin:                                  "KindJoin",
	KindLabel:                                 "KindLabel",
	KindLambda:                                "KindLambda",
	KindLikeExpression:                        "KindLikeExpression",
	KindLimitAll:                              "KindLimitAll",
	KindLimit:                                 "KindLimit",
	KindLimitOffset:                           "KindLimitOffset",
	KindLocation:                              "KindLocation",
	KindLockMode:                              "KindLockMode",
	KindMacroBody:                             "KindMacroBody",
	KindMapType:                               "KindMapType",
	KindMatchRecognizeClause:                  "KindMatchRecognizeClause",
	KindMaxLiteral:                            "KindMaxLiteral",
	KindMergeAction:                           "KindMergeAction",
	KindMergeStatement:                        "KindMergeStatement",
	KindMergeWhenClauseList:                   "KindMergeWhenClauseList",
	KindMergeWhenClause:                       "KindMergeWhenClause",
	KindModelClause:                           "KindModelClause",
	KindModuleStatement:                       "KindModuleStatement",
	KindNamedArgument:                         "KindNamedArgument",
	KindNewConstructorArg:                     "KindNewConstructorArg",
	KindNewConstructor:                        "KindNewConstructor",
	KindNotNullColumnAttribute:                "KindNotNullColumnAttribute",
	KindNullLiteral:                           "KindNullLiteral",
	KindNullOrder:                             "KindNullOrder",
	KindNumericLiteral:                        "KindNumericLiteral",
	KindOnClause:                              "KindOnClause",
	KindOnConflictClause:                      "KindOnConflictClause",
	KindOnOrUsingClauseList:                   "KindOnOrUsingClauseList",
	KindOptionsEntry:                          "KindOptionsEntry",
	KindOptionsList:                           "KindOptionsList",
	KindOrExpr:                                "KindOrExpr",
	KindOrderBy:                               "KindOrderBy",
	KindOrderingExpression:                    "KindOrderingExpression",
	KindParameterAssignment:                   "KindParameterAssignment",
	KindParameterExpr:                         "KindParameterExpr",
	KindParenthesizedJoin:                     "KindParenthesizedJoin",
	KindPartitionBy:                           "KindPartitionBy",
	KindPathExpressionList:                    "KindPathExpressionList",
	KindPathExpression:                        "KindPathExpression",
	KindPipeAggregate:                         "KindPipeAggregate",
	KindPipeAs:                                "KindPipeAs",
	KindPipeAssert:                            "KindPipeAssert",
	KindPipeCall:                              "KindPipeCall",
	KindPipeCreateTable:                       "KindPipeCreateTable",
	KindPipeDescribe:                          "KindPipeDescribe",
	KindPipeDistinct:                          "KindPipeDistinct",
	KindPipeDrop:                              "KindPipeDrop",
	KindPipeExportData:                        "KindPipeExportData",
	KindPipeExtend:                            "KindPipeExtend",
	KindPipeFork:                              "KindPipeFork",
	KindPipeIfCase:                            "KindPipeIfCase",
	KindPipeIf:                                "KindPipeIf",
	KindPipeInsert:                            "KindPipeInsert",
	KindPipeJoinLhsPlaceholder:                "KindPipeJoinLhsPlaceholder",
	KindPipeJoin:                              "KindPipeJoin",
	KindPipeLimitOffset:                       "KindPipeLimitOffset",
	KindPipeLog:                               "KindPipeLog",
	KindPipeMatchRecognize:                    "KindPipeMatchRecognize",
	KindPipeOrderBy:                           "KindPipeOrderBy",
	KindPipePivot:                             "KindPipePivot",
	KindPipeRecursiveUnion:                    "KindPipeRecursiveUnion",
	KindPipeRenameItem:                        "KindPipeRenameItem",
	KindPipeRename:                            "KindPipeRename",
	KindPipeSelect:                            "KindPipeSelect",
	KindPipeSetItem:                           "KindPipeSetItem",
	KindPipeSet:                               "KindPipeSet",
	KindPipeSetOperation:                      "KindPipeSetOperation",
	KindPipeStaticDescribe:                    "KindPipeStaticDescribe",
	KindPipeTablesample:                       "KindPipeTablesample",
	KindPipeTee:                               "KindPipeTee",
	KindPipeUnpivot:                           "KindPipeUnpivot",
	KindPipeWhere:                             "KindPipeWhere",
	KindPipeWindow:                            "KindPipeWindow",
	KindPipeWith:                              "KindPipeWith",
	KindPivotClause:                           "KindPivotClause",
	KindPivotExpressionList:                   "KindPivotExpressionList",
	KindPivotExpression:                       "KindPivotExpression",
	KindPivotValueList:                        "KindPivotValueList",
	KindPivotValue:                            "KindPivotValue",
	KindPrimaryKeyColumnAttribute:             "KindPrimaryKeyColumnAttribute",
	KindPrimaryKeyElementList:                 "KindPrimaryKeyElementList",
	KindPrimaryKeyElement:                     "KindPrimaryKeyElement",
	KindPrimaryKey:                            "KindPrimaryKey",
	KindPrivilege:                             "KindPrivilege",
	KindPrivileges:                            "KindPrivileges",
	KindQualify:                               "KindQualify",
	KindQuantifierBound:                       "KindQuantifierBound",
	KindQuery:                                 "KindQuery",
	KindQueryStatement:                        "KindQueryStatement",
	KindRaiseStatement:                        "KindRaiseStatement",
	KindRangeColumnSchema:                     "KindRangeColumnSchema",
	KindRangeLiteral:                          "KindRangeLiteral",
	KindRangeType:                             "KindRangeType",
	KindRebuildAction:                         "KindRebuildAction",
	KindRecursionDepthModifier:                "KindRecursionDepthModifier",
	KindRemoveFromRestricteeListClause:        "KindRemoveFromRestricteeListClause",
	KindRenameColumnAction:                    "KindRenameColumnAction",
	KindRenameStatement:                       "KindRenameStatement",
	KindRenameToClause:                        "KindRenameToClause",
	KindRepeatStatement:                       "KindRepeatStatement",
	KindRepeatableClause:                      "KindRepeatableClause",
	KindReplaceFieldsArg:                      "KindReplaceFieldsArg",
	KindReplaceFieldsExpression:               "KindReplaceFieldsExpression",
	KindReplaceTtlAction:                      "KindReplaceTtlAction",
	KindRestrictToClause:                      "KindRestrictToClause",
	KindReturnStatement:                       "KindReturnStatement",
	KindReturningClause:                       "KindReturningClause",
	KindRevokeFromClause:                      "KindRevokeFromClause",
	KindRevokeStatement:                       "KindRevokeStatement",
	KindRollbackStatement:                     "KindRollbackStatement",
	KindRollup:                                "KindRollup",
	KindRowPatternAnchor:                      "KindRowPatternAnchor",
	KindRowPatternOperation:                   "KindRowPatternOperation",
	KindRowPatternQuantification:              "KindRowPatternQuantification",
	KindRowPatternVariable:                    "KindRowPatternVariable",
	KindRunBatchStatement:                     "KindRunBatchStatement",
	KindRunStatement:                          "KindRunStatement",
	KindSampleClause:                          "KindSampleClause",
	KindSampleSize:                            "KindSampleSize",
	KindSampleSuffix:                          "KindSampleSuffix",
	KindScript:                                "KindScript",
	KindSelectAs:                              "KindSelectAs",
	KindSelectColumn:                          "KindSelectColumn",
	KindSelectList:                            "KindSelectList",
	KindSelect:                                "KindSelect",
	KindSequenceArg:                           "KindSequenceArg",
	KindSetAsAction:                           "KindSetAsAction",
	KindSetCollateClause:                      "KindSetCollateClause",
	KindSetOperationAllOrDistinct:             "KindSetOperationAllOrDistinct",
	KindSetOperationColumnMatchMode:           "KindSetOperationColumnMatchMode",
	KindSetOperationColumnPropagationMode:     "KindSetOperationColumnPropagationMode",
	KindSetOperationMetadataList:              "KindSetOperationMetadataList",
	KindSetOperationMetadata:                  "KindSetOperationMetadata",
	KindSetOperation:                          "KindSetOperation",
	KindSetOperationType:                      "KindSetOperationType",
	KindSetOptionsAction:                      "KindSetOptionsAction",
	KindSetTransactionStatement:               "KindSetTransactionStatement",
	KindShowStatement:                         "KindShowStatement",
	KindSimpleColumnSchema:                    "KindSimpleColumnSchema",
	KindSimpleType:                            "KindSimpleType",
	KindSingleAssignment:                      "KindSingleAssignment",
	KindSpannerAlterColumnAction:              "KindSpannerAlterColumnAction",
	KindSpannerInterleaveClause:               "KindSpannerInterleaveClause",
	KindSpannerSetOnDeleteAction:              "KindSpannerSetOnDeleteAction",
	KindSpannerTableOptions:                   "KindSpannerTableOptions",
	KindSqlFunctionBody:                       "KindSqlFunctionBody",
	KindStarExceptList:                        "KindStarExceptList",
	KindStarModifiers:                         "KindStarModifiers",
	KindStar:                                  "KindStar",
	KindStarReplaceItem:                       "KindStarReplaceItem",
	KindStarWithModifiers:                     "KindStarWithModifiers",
	KindStartBatchStatement:                   "KindStartBatchStatement",
	KindStatementList:                         "KindStatementList",
	KindStatementWithPipeOperators:            "KindStatementWithPipeOperators",
	KindStringLiteralComponent:                "KindStringLiteralComponent",
	KindStringLiteral:                         "KindStringLiteral",
	KindStructBracedConstructor:               "KindStructBracedConstructor",
	KindStructColumnField:                     "KindStructColumnField",
	KindStructColumnSchema:                    "KindStructColumnSchema",
	KindStructConstructorArg:                  "KindStructConstructorArg",
	KindStructConstructorWithKeyword:          "KindStructConstructorWithKeyword",
	KindStructConstructorWithParens:           "KindStructConstructorWithParens",
	KindStructField:                           "KindStructField",
	KindStructType:                            "KindStructType",
	KindSubpipeline:                           "KindSubpipeline",
	KindSubpipelineStatement:                  "KindSubpipelineStatement",
	KindSymbolQuantifier:                      "KindSymbolQuantifier",
	KindSystemVariableAssignment:              "KindSystemVariableAssignment",
	KindSystemVariableExpr:                    "KindSystemVariableExpr",
	KindTVFArgument:                           "KindTVFArgument",
	KindTVF:                                   "KindTVF",
	KindTVFSchemaColumn:                       "KindTVFSchemaColumn",
	KindTVFSchema:                             "KindTVFSchema",
	KindTableAndColumnInfoList:                "KindTableAndColumnInfoList",
	KindTableAndColumnInfo:                    "KindTableAndColumnInfo",
	KindTableClause:                           "KindTableClause",
	KindTableElementList:                      "KindTableElementList",
	KindTablePathExpression:                   "KindTablePathExpression",
	KindTableSubquery:                         "KindTableSubquery",
	KindTemplatedParameterType:                "KindTemplatedParameterType",
	KindTransactionIsolationLevel:             "KindTransactionIsolationLevel",
	KindTransactionModeList:                   "KindTransactionModeList",
	KindTransactionReadWriteMode:              "KindTransactionReadWriteMode",
	KindTransformClause:                       "KindTransformClause",
	KindTruncateStatement:                     "KindTruncateStatement",
	KindTtlClause:                             "KindTtlClause",
	KindTypeParameterList:                     "KindTypeParameterList",
	KindUnaryExpression:                       "KindUnaryExpression",
	KindUndropStatement:                       "KindUndropStatement",
	KindUnnestExpression:                      "KindUnnestExpression",
	KindUnnestExpressionWithOptAliasAndOffset: "KindUnnestExpressionWithOptAliasAndOffset",
	KindUnpivotClause:                         "KindUnpivotClause",
	KindUnpivotInItemLabel:                    "KindUnpivotInItemLabel",
	KindUnpivotInItemList:                     "KindUnpivotInItemList",
	KindUnpivotInItem:                         "KindUnpivotInItem",
	KindUntilClause:                           "KindUntilClause",
	KindUpdateConstructor:                     "KindUpdateConstructor",
	KindUpdateItemList:                        "KindUpdateItemList",
	KindUpdateItem:                            "KindUpdateItem",
	KindUpdateSetValue:                        "KindUpdateSetValue",
	KindUpdateStatement:                       "KindUpdateStatement",
	KindUsingClause:                           "KindUsingClause",
	KindVariableDeclaration:                   "KindVariableDeclaration",
	KindWhenThenClauseList:                    "KindWhenThenClauseList",
	KindWhenThenClause:                        "KindWhenThenClause",
	KindWhereClause:                           "KindWhereClause",
	KindWhileStatement:                        "KindWhileStatement",
	KindWindowClause:                          "KindWindowClause",
	KindWindowDefinition:                      "KindWindowDefinition",
	KindWindowFrameExpr:                       "KindWindowFrameExpr",
	KindWindowFrame:                           "KindWindowFrame",
	KindWindowSpecification:                   "KindWindowSpecification",
	KindWithClauseEntry:                       "KindWithClauseEntry",
	KindWithClause:                            "KindWithClause",
	KindWithConnectionClause:                  "KindWithConnectionClause",
	KindWithExpression:                        "KindWithExpression",
	KindWithModifier:                          "KindWithModifier",
	KindWithOffset:                            "KindWithOffset",
	KindWithPartitionColumnsClause:            "KindWithPartitionColumnsClause",
	KindWithReportModifier:                    "KindWithReportModifier",
	KindWithWeight:                            "KindWithWeight",
	KindYieldItemList:                         "KindYieldItemList",
}

func (k Kind) String() string {
	if int(k) < len(kindNames) {
		return kindNames[k]
	}
	return "Unknown"
}
