// Code generated by astgen. DO NOT EDIT.

package ast

import (
	"github.com/glassmonkey/zetasql-wasm/wasm/generated"
)

func wrapAlterAction(p *generated.AnyASTAlterActionProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTAlterActionProto_AstSetOptionsActionNode:
		return newSetOptionsActionNode(v.AstSetOptionsActionNode)
	case *generated.AnyASTAlterActionProto_AstSetAsActionNode:
		return newSetAsActionNode(v.AstSetAsActionNode)
	case *generated.AnyASTAlterActionProto_AstAddConstraintActionNode:
		return newAddConstraintActionNode(v.AstAddConstraintActionNode)
	case *generated.AnyASTAlterActionProto_AstDropPrimaryKeyActionNode:
		return newDropPrimaryKeyActionNode(v.AstDropPrimaryKeyActionNode)
	case *generated.AnyASTAlterActionProto_AstDropConstraintActionNode:
		return newDropConstraintActionNode(v.AstDropConstraintActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterConstraintEnforcementActionNode:
		return newAlterConstraintEnforcementActionNode(v.AstAlterConstraintEnforcementActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterConstraintSetOptionsActionNode:
		return newAlterConstraintSetOptionsActionNode(v.AstAlterConstraintSetOptionsActionNode)
	case *generated.AnyASTAlterActionProto_AstAddColumnActionNode:
		return newAddColumnActionNode(v.AstAddColumnActionNode)
	case *generated.AnyASTAlterActionProto_AstDropColumnActionNode:
		return newDropColumnActionNode(v.AstDropColumnActionNode)
	case *generated.AnyASTAlterActionProto_AstRenameColumnActionNode:
		return newRenameColumnActionNode(v.AstRenameColumnActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnTypeActionNode:
		return newAlterColumnTypeActionNode(v.AstAlterColumnTypeActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnOptionsActionNode:
		return newAlterColumnOptionsActionNode(v.AstAlterColumnOptionsActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnDropNotNullActionNode:
		return newAlterColumnDropNotNullActionNode(v.AstAlterColumnDropNotNullActionNode)
	case *generated.AnyASTAlterActionProto_AstGrantToClauseNode:
		return newGrantToClauseNode(v.AstGrantToClauseNode)
	case *generated.AnyASTAlterActionProto_AstFilterUsingClauseNode:
		return newFilterUsingClauseNode(v.AstFilterUsingClauseNode)
	case *generated.AnyASTAlterActionProto_AstRevokeFromClauseNode:
		return newRevokeFromClauseNode(v.AstRevokeFromClauseNode)
	case *generated.AnyASTAlterActionProto_AstRenameToClauseNode:
		return newRenameToClauseNode(v.AstRenameToClauseNode)
	case *generated.AnyASTAlterActionProto_AstSetCollateClauseNode:
		return newSetCollateClauseNode(v.AstSetCollateClauseNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnSetDefaultActionNode:
		return newAlterColumnSetDefaultActionNode(v.AstAlterColumnSetDefaultActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnDropDefaultActionNode:
		return newAlterColumnDropDefaultActionNode(v.AstAlterColumnDropDefaultActionNode)
	case *generated.AnyASTAlterActionProto_AstRestrictToClauseNode:
		return newRestrictToClauseNode(v.AstRestrictToClauseNode)
	case *generated.AnyASTAlterActionProto_AstAddToRestricteeListClauseNode:
		return newAddToRestricteeListClauseNode(v.AstAddToRestricteeListClauseNode)
	case *generated.AnyASTAlterActionProto_AstRemoveFromRestricteeListClauseNode:
		return newRemoveFromRestricteeListClauseNode(v.AstRemoveFromRestricteeListClauseNode)
	case *generated.AnyASTAlterActionProto_AstAlterSubEntityActionNode:
		return newAlterSubEntityActionNode(v.AstAlterSubEntityActionNode)
	case *generated.AnyASTAlterActionProto_AstAddSubEntityActionNode:
		return newAddSubEntityActionNode(v.AstAddSubEntityActionNode)
	case *generated.AnyASTAlterActionProto_AstDropSubEntityActionNode:
		return newDropSubEntityActionNode(v.AstDropSubEntityActionNode)
	case *generated.AnyASTAlterActionProto_AstAddTtlActionNode:
		return newAddTtlActionNode(v.AstAddTtlActionNode)
	case *generated.AnyASTAlterActionProto_AstReplaceTtlActionNode:
		return newReplaceTtlActionNode(v.AstReplaceTtlActionNode)
	case *generated.AnyASTAlterActionProto_AstDropTtlActionNode:
		return newDropTtlActionNode(v.AstDropTtlActionNode)
	case *generated.AnyASTAlterActionProto_AstSpannerAlterColumnActionNode:
		return newSpannerAlterColumnActionNode(v.AstSpannerAlterColumnActionNode)
	case *generated.AnyASTAlterActionProto_AstSpannerSetOnDeleteActionNode:
		return newSpannerSetOnDeleteActionNode(v.AstSpannerSetOnDeleteActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnDropGeneratedActionNode:
		return newAlterColumnDropGeneratedActionNode(v.AstAlterColumnDropGeneratedActionNode)
	case *generated.AnyASTAlterActionProto_AstAddColumnIdentifierActionNode:
		return newAddColumnIdentifierActionNode(v.AstAddColumnIdentifierActionNode)
	case *generated.AnyASTAlterActionProto_AstRebuildActionNode:
		return newRebuildActionNode(v.AstRebuildActionNode)
	case *generated.AnyASTAlterActionProto_AstAlterColumnSetGeneratedActionNode:
		return newAlterColumnSetGeneratedActionNode(v.AstAlterColumnSetGeneratedActionNode)
	}
	return nil
}

func wrapAlterActionSlice(ps []*generated.AnyASTAlterActionProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapAlterAction(p)
	}
	return nodes
}

func wrapAlterStatementBase(p *generated.AnyASTAlterStatementBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTAlterStatementBaseProto_AstAlterDatabaseStatementNode:
		return newAlterDatabaseStatementNode(v.AstAlterDatabaseStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterSchemaStatementNode:
		return newAlterSchemaStatementNode(v.AstAlterSchemaStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterTableStatementNode:
		return newAlterTableStatementNode(v.AstAlterTableStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterViewStatementNode:
		return newAlterViewStatementNode(v.AstAlterViewStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterMaterializedViewStatementNode:
		return newAlterMaterializedViewStatementNode(v.AstAlterMaterializedViewStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterRowAccessPolicyStatementNode:
		return newAlterRowAccessPolicyStatementNode(v.AstAlterRowAccessPolicyStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterEntityStatementNode:
		return newAlterEntityStatementNode(v.AstAlterEntityStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterPrivilegeRestrictionStatementNode:
		return newAlterPrivilegeRestrictionStatementNode(v.AstAlterPrivilegeRestrictionStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterModelStatementNode:
		return newAlterModelStatementNode(v.AstAlterModelStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterApproxViewStatementNode:
		return newAlterApproxViewStatementNode(v.AstAlterApproxViewStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterExternalSchemaStatementNode:
		return newAlterExternalSchemaStatementNode(v.AstAlterExternalSchemaStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterConnectionStatementNode:
		return newAlterConnectionStatementNode(v.AstAlterConnectionStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterIndexStatementNode:
		return newAlterIndexStatementNode(v.AstAlterIndexStatementNode)
	case *generated.AnyASTAlterStatementBaseProto_AstAlterSequenceStatementNode:
		return newAlterSequenceStatementNode(v.AstAlterSequenceStatementNode)
	}
	return nil
}

func wrapAlterStatementBaseSlice(ps []*generated.AnyASTAlterStatementBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapAlterStatementBase(p)
	}
	return nodes
}

func wrapBreakContinueStatement(p *generated.AnyASTBreakContinueStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTBreakContinueStatementProto_AstBreakStatementNode:
		return newBreakStatementNode(v.AstBreakStatementNode)
	case *generated.AnyASTBreakContinueStatementProto_AstContinueStatementNode:
		return newContinueStatementNode(v.AstContinueStatementNode)
	}
	return nil
}

func wrapBreakContinueStatementSlice(ps []*generated.AnyASTBreakContinueStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapBreakContinueStatement(p)
	}
	return nodes
}

func wrapColumnAttribute(p *generated.AnyASTColumnAttributeProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTColumnAttributeProto_AstNotNullColumnAttributeNode:
		return newNotNullColumnAttributeNode(v.AstNotNullColumnAttributeNode)
	case *generated.AnyASTColumnAttributeProto_AstHiddenColumnAttributeNode:
		return newHiddenColumnAttributeNode(v.AstHiddenColumnAttributeNode)
	case *generated.AnyASTColumnAttributeProto_AstPrimaryKeyColumnAttributeNode:
		return newPrimaryKeyColumnAttributeNode(v.AstPrimaryKeyColumnAttributeNode)
	case *generated.AnyASTColumnAttributeProto_AstForeignKeyColumnAttributeNode:
		return newForeignKeyColumnAttributeNode(v.AstForeignKeyColumnAttributeNode)
	}
	return nil
}

func wrapColumnAttributeSlice(ps []*generated.AnyASTColumnAttributeProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapColumnAttribute(p)
	}
	return nodes
}

func wrapColumnSchema(p *generated.AnyASTColumnSchemaProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTColumnSchemaProto_AstSimpleColumnSchemaNode:
		return newSimpleColumnSchemaNode(v.AstSimpleColumnSchemaNode)
	case *generated.AnyASTColumnSchemaProto_AstStructColumnSchemaNode:
		return newStructColumnSchemaNode(v.AstStructColumnSchemaNode)
	case *generated.AnyASTColumnSchemaProto_AstInferredTypeColumnSchemaNode:
		return newInferredTypeColumnSchemaNode(v.AstInferredTypeColumnSchemaNode)
	case *generated.AnyASTColumnSchemaProto_AstElementTypeColumnSchemaNode:
		return wrapElementTypeColumnSchema(v.AstElementTypeColumnSchemaNode)
	}
	return nil
}

func wrapColumnSchemaSlice(ps []*generated.AnyASTColumnSchemaProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapColumnSchema(p)
	}
	return nodes
}

func wrapCreateFunctionStmtBase(p *generated.AnyASTCreateFunctionStmtBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTCreateFunctionStmtBaseProto_AstCreateFunctionStatementNode:
		return newCreateFunctionStatementNode(v.AstCreateFunctionStatementNode)
	case *generated.AnyASTCreateFunctionStmtBaseProto_AstCreateTableFunctionStatementNode:
		return newCreateTableFunctionStatementNode(v.AstCreateTableFunctionStatementNode)
	}
	return nil
}

func wrapCreateFunctionStmtBaseSlice(ps []*generated.AnyASTCreateFunctionStmtBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateFunctionStmtBase(p)
	}
	return nodes
}

func wrapCreateSchemaStmtBase(p *generated.AnyASTCreateSchemaStmtBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTCreateSchemaStmtBaseProto_AstCreateSchemaStatementNode:
		return newCreateSchemaStatementNode(v.AstCreateSchemaStatementNode)
	case *generated.AnyASTCreateSchemaStmtBaseProto_AstCreateExternalSchemaStatementNode:
		return newCreateExternalSchemaStatementNode(v.AstCreateExternalSchemaStatementNode)
	}
	return nil
}

func wrapCreateSchemaStmtBaseSlice(ps []*generated.AnyASTCreateSchemaStmtBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateSchemaStmtBase(p)
	}
	return nodes
}

func wrapCreateStatement(p *generated.AnyASTCreateStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTCreateStatementProto_AstCreateConstantStatementNode:
		return newCreateConstantStatementNode(v.AstCreateConstantStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateProcedureStatementNode:
		return newCreateProcedureStatementNode(v.AstCreateProcedureStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateModelStatementNode:
		return newCreateModelStatementNode(v.AstCreateModelStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateIndexStatementNode:
		return newCreateIndexStatementNode(v.AstCreateIndexStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateSnapshotTableStatementNode:
		return newCreateSnapshotTableStatementNode(v.AstCreateSnapshotTableStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateEntityStatementNode:
		return newCreateEntityStatementNode(v.AstCreateEntityStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateRowAccessPolicyStatementNode:
		return newCreateRowAccessPolicyStatementNode(v.AstCreateRowAccessPolicyStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateTableStmtBaseNode:
		return wrapCreateTableStmtBase(v.AstCreateTableStmtBaseNode)
	case *generated.AnyASTCreateStatementProto_AstCreateViewStatementBaseNode:
		return wrapCreateViewStatementBase(v.AstCreateViewStatementBaseNode)
	case *generated.AnyASTCreateStatementProto_AstCreateFunctionStmtBaseNode:
		return wrapCreateFunctionStmtBase(v.AstCreateFunctionStmtBaseNode)
	case *generated.AnyASTCreateStatementProto_AstCreatePrivilegeRestrictionStatementNode:
		return newCreatePrivilegeRestrictionStatementNode(v.AstCreatePrivilegeRestrictionStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreatePropertyGraphStatementNode:
		return newCreatePropertyGraphStatementNode(v.AstCreatePropertyGraphStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateSnapshotStatementNode:
		return newCreateSnapshotStatementNode(v.AstCreateSnapshotStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateSchemaStmtBaseNode:
		return wrapCreateSchemaStmtBase(v.AstCreateSchemaStmtBaseNode)
	case *generated.AnyASTCreateStatementProto_AstCreateConnectionStatementNode:
		return newCreateConnectionStatementNode(v.AstCreateConnectionStatementNode)
	case *generated.AnyASTCreateStatementProto_AstCreateSequenceStatementNode:
		return newCreateSequenceStatementNode(v.AstCreateSequenceStatementNode)
	}
	return nil
}

func wrapCreateStatementSlice(ps []*generated.AnyASTCreateStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateStatement(p)
	}
	return nodes
}

func wrapCreateTableStmtBase(p *generated.AnyASTCreateTableStmtBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTCreateTableStmtBaseProto_AstCreateTableStatementNode:
		return newCreateTableStatementNode(v.AstCreateTableStatementNode)
	case *generated.AnyASTCreateTableStmtBaseProto_AstCreateExternalTableStatementNode:
		return newCreateExternalTableStatementNode(v.AstCreateExternalTableStatementNode)
	case *generated.AnyASTCreateTableStmtBaseProto_AstAuxLoadDataStatementNode:
		return newAuxLoadDataStatementNode(v.AstAuxLoadDataStatementNode)
	}
	return nil
}

func wrapCreateTableStmtBaseSlice(ps []*generated.AnyASTCreateTableStmtBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateTableStmtBase(p)
	}
	return nodes
}

func wrapCreateViewStatementBase(p *generated.AnyASTCreateViewStatementBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTCreateViewStatementBaseProto_AstCreateViewStatementNode:
		return newCreateViewStatementNode(v.AstCreateViewStatementNode)
	case *generated.AnyASTCreateViewStatementBaseProto_AstCreateMaterializedViewStatementNode:
		return newCreateMaterializedViewStatementNode(v.AstCreateMaterializedViewStatementNode)
	case *generated.AnyASTCreateViewStatementBaseProto_AstCreateApproxViewStatementNode:
		return newCreateApproxViewStatementNode(v.AstCreateApproxViewStatementNode)
	}
	return nil
}

func wrapCreateViewStatementBaseSlice(ps []*generated.AnyASTCreateViewStatementBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateViewStatementBase(p)
	}
	return nodes
}

func wrapDdlStatement(p *generated.AnyASTDdlStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTDdlStatementProto_AstDropEntityStatementNode:
		return newDropEntityStatementNode(v.AstDropEntityStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropFunctionStatementNode:
		return newDropFunctionStatementNode(v.AstDropFunctionStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropTableFunctionStatementNode:
		return newDropTableFunctionStatementNode(v.AstDropTableFunctionStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropMaterializedViewStatementNode:
		return newDropMaterializedViewStatementNode(v.AstDropMaterializedViewStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropSnapshotTableStatementNode:
		return newDropSnapshotTableStatementNode(v.AstDropSnapshotTableStatementNode)
	case *generated.AnyASTDdlStatementProto_AstCreateStatementNode:
		return wrapCreateStatement(v.AstCreateStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropRowAccessPolicyStatementNode:
		return newDropRowAccessPolicyStatementNode(v.AstDropRowAccessPolicyStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropStatementNode:
		return newDropStatementNode(v.AstDropStatementNode)
	case *generated.AnyASTDdlStatementProto_AstAlterStatementBaseNode:
		return wrapAlterStatementBase(v.AstAlterStatementBaseNode)
	case *generated.AnyASTDdlStatementProto_AstDropPrivilegeRestrictionStatementNode:
		return newDropPrivilegeRestrictionStatementNode(v.AstDropPrivilegeRestrictionStatementNode)
	case *generated.AnyASTDdlStatementProto_AstUndropStatementNode:
		return newUndropStatementNode(v.AstUndropStatementNode)
	case *generated.AnyASTDdlStatementProto_AstDropIndexStatementNode:
		return wrapDropIndexStatement(v.AstDropIndexStatementNode)
	}
	return nil
}

func wrapDdlStatementSlice(ps []*generated.AnyASTDdlStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapDdlStatement(p)
	}
	return nodes
}

func wrapDropIndexStatement(p *generated.AnyASTDropIndexStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTDropIndexStatementProto_AstDropSearchIndexStatementNode:
		return newDropSearchIndexStatementNode(v.AstDropSearchIndexStatementNode)
	case *generated.AnyASTDropIndexStatementProto_AstDropVectorIndexStatementNode:
		return newDropVectorIndexStatementNode(v.AstDropVectorIndexStatementNode)
	}
	return nil
}

func wrapDropIndexStatementSlice(ps []*generated.AnyASTDropIndexStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapDropIndexStatement(p)
	}
	return nodes
}

func wrapElementTypeColumnSchema(p *generated.AnyASTElementTypeColumnSchemaProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTElementTypeColumnSchemaProto_AstArrayColumnSchemaNode:
		return newArrayColumnSchemaNode(v.AstArrayColumnSchemaNode)
	case *generated.AnyASTElementTypeColumnSchemaProto_AstRangeColumnSchemaNode:
		return newRangeColumnSchemaNode(v.AstRangeColumnSchemaNode)
	}
	return nil
}

func wrapElementTypeColumnSchemaSlice(ps []*generated.AnyASTElementTypeColumnSchemaProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapElementTypeColumnSchema(p)
	}
	return nodes
}

func wrapExpression(p *generated.AnyASTExpressionProto) ExpressionNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTExpressionProto_AstLeafNode:
		return wrapLeaf(v.AstLeafNode)
	case *generated.AnyASTExpressionProto_AstIdentifierNode:
		return newIdentifierNode(v.AstIdentifierNode)
	case *generated.AnyASTExpressionProto_AstGeneralizedPathExpressionNode:
		return wrapGeneralizedPathExpression(v.AstGeneralizedPathExpressionNode)
	case *generated.AnyASTExpressionProto_AstAndExprNode:
		return newAndExprNode(v.AstAndExprNode)
	case *generated.AnyASTExpressionProto_AstBinaryExpressionNode:
		return newBinaryExpressionNode(v.AstBinaryExpressionNode)
	case *generated.AnyASTExpressionProto_AstOrExprNode:
		return newOrExprNode(v.AstOrExprNode)
	case *generated.AnyASTExpressionProto_AstCastExpressionNode:
		return newCastExpressionNode(v.AstCastExpressionNode)
	case *generated.AnyASTExpressionProto_AstFunctionCallNode:
		return newFunctionCallNode(v.AstFunctionCallNode)
	case *generated.AnyASTExpressionProto_AstArrayConstructorNode:
		return newArrayConstructorNode(v.AstArrayConstructorNode)
	case *generated.AnyASTExpressionProto_AstStructConstructorWithParensNode:
		return newStructConstructorWithParensNode(v.AstStructConstructorWithParensNode)
	case *generated.AnyASTExpressionProto_AstStructConstructorWithKeywordNode:
		return newStructConstructorWithKeywordNode(v.AstStructConstructorWithKeywordNode)
	case *generated.AnyASTExpressionProto_AstInExpressionNode:
		return newInExpressionNode(v.AstInExpressionNode)
	case *generated.AnyASTExpressionProto_AstBetweenExpressionNode:
		return newBetweenExpressionNode(v.AstBetweenExpressionNode)
	case *generated.AnyASTExpressionProto_AstDateOrTimeLiteralNode:
		return newDateOrTimeLiteralNode(v.AstDateOrTimeLiteralNode)
	case *generated.AnyASTExpressionProto_AstCaseValueExpressionNode:
		return newCaseValueExpressionNode(v.AstCaseValueExpressionNode)
	case *generated.AnyASTExpressionProto_AstCaseNoValueExpressionNode:
		return newCaseNoValueExpressionNode(v.AstCaseNoValueExpressionNode)
	case *generated.AnyASTExpressionProto_AstBitwiseShiftExpressionNode:
		return newBitwiseShiftExpressionNode(v.AstBitwiseShiftExpressionNode)
	case *generated.AnyASTExpressionProto_AstDotStarNode:
		return newDotStarNode(v.AstDotStarNode)
	case *generated.AnyASTExpressionProto_AstDotStarWithModifiersNode:
		return newDotStarWithModifiersNode(v.AstDotStarWithModifiersNode)
	case *generated.AnyASTExpressionProto_AstExpressionSubqueryNode:
		return newExpressionSubqueryNode(v.AstExpressionSubqueryNode)
	case *generated.AnyASTExpressionProto_AstExtractExpressionNode:
		return newExtractExpressionNode(v.AstExtractExpressionNode)
	case *generated.AnyASTExpressionProto_AstIntervalExprNode:
		return newIntervalExprNode(v.AstIntervalExprNode)
	case *generated.AnyASTExpressionProto_AstNamedArgumentNode:
		return newNamedArgumentNode(v.AstNamedArgumentNode)
	case *generated.AnyASTExpressionProto_AstStarWithModifiersNode:
		return newStarWithModifiersNode(v.AstStarWithModifiersNode)
	case *generated.AnyASTExpressionProto_AstUnaryExpressionNode:
		return newUnaryExpressionNode(v.AstUnaryExpressionNode)
	case *generated.AnyASTExpressionProto_AstLikeExpressionNode:
		return newLikeExpressionNode(v.AstLikeExpressionNode)
	case *generated.AnyASTExpressionProto_AstParameterExprBaseNode:
		return wrapParameterExprBase(v.AstParameterExprBaseNode)
	case *generated.AnyASTExpressionProto_AstLambdaNode:
		return newLambdaNode(v.AstLambdaNode)
	case *generated.AnyASTExpressionProto_AstAnalyticFunctionCallNode:
		return newAnalyticFunctionCallNode(v.AstAnalyticFunctionCallNode)
	case *generated.AnyASTExpressionProto_AstNewConstructorNode:
		return newNewConstructorNode(v.AstNewConstructorNode)
	case *generated.AnyASTExpressionProto_AstDefaultLiteralNode:
		return newDefaultLiteralNode(v.AstDefaultLiteralNode)
	case *generated.AnyASTExpressionProto_AstReplaceFieldsExpressionNode:
		return newReplaceFieldsExpressionNode(v.AstReplaceFieldsExpressionNode)
	case *generated.AnyASTExpressionProto_AstBracedConstructorNode:
		return newBracedConstructorNode(v.AstBracedConstructorNode)
	case *generated.AnyASTExpressionProto_AstBracedNewConstructorNode:
		return newBracedNewConstructorNode(v.AstBracedNewConstructorNode)
	case *generated.AnyASTExpressionProto_AstWithExpressionNode:
		return newWithExpressionNode(v.AstWithExpressionNode)
	case *generated.AnyASTExpressionProto_AstRangeLiteralNode:
		return newRangeLiteralNode(v.AstRangeLiteralNode)
	case *generated.AnyASTExpressionProto_AstSequenceArgNode:
		return newSequenceArgNode(v.AstSequenceArgNode)
	case *generated.AnyASTExpressionProto_AstExpressionWithAliasNode:
		return newExpressionWithAliasNode(v.AstExpressionWithAliasNode)
	case *generated.AnyASTExpressionProto_AstStructBracedConstructorNode:
		return newStructBracedConstructorNode(v.AstStructBracedConstructorNode)
	case *generated.AnyASTExpressionProto_AstIntOrUnboundedNode:
		return newIntOrUnboundedNode(v.AstIntOrUnboundedNode)
	case *generated.AnyASTExpressionProto_AstGraphIsLabeledPredicateNode:
		return newGraphIsLabeledPredicateNode(v.AstGraphIsLabeledPredicateNode)
	case *generated.AnyASTExpressionProto_AstBracedConstructorLhsNode:
		return newBracedConstructorLhsNode(v.AstBracedConstructorLhsNode)
	case *generated.AnyASTExpressionProto_AstUpdateConstructorNode:
		return newUpdateConstructorNode(v.AstUpdateConstructorNode)
	case *generated.AnyASTExpressionProto_AstInputTableArgumentNode:
		return newInputTableArgumentNode(v.AstInputTableArgumentNode)
	case *generated.AnyASTExpressionProto_AstConcatExprNode:
		return newConcatExprNode(v.AstConcatExprNode)
	}
	return nil
}

func wrapExpressionSlice(ps []*generated.AnyASTExpressionProto) []ExpressionNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ExpressionNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapExpression(p)
	}
	return nodes
}

func wrapGeneralizedPathExpression(p *generated.AnyASTGeneralizedPathExpressionProto) ExpressionNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTGeneralizedPathExpressionProto_AstPathExpressionNode:
		return newPathExpressionNode(v.AstPathExpressionNode)
	case *generated.AnyASTGeneralizedPathExpressionProto_AstArrayElementNode:
		return newArrayElementNode(v.AstArrayElementNode)
	case *generated.AnyASTGeneralizedPathExpressionProto_AstDotGeneralizedFieldNode:
		return newDotGeneralizedFieldNode(v.AstDotGeneralizedFieldNode)
	case *generated.AnyASTGeneralizedPathExpressionProto_AstDotIdentifierNode:
		return newDotIdentifierNode(v.AstDotIdentifierNode)
	case *generated.AnyASTGeneralizedPathExpressionProto_AstExtendedPathExpressionNode:
		return newExtendedPathExpressionNode(v.AstExtendedPathExpressionNode)
	}
	return nil
}

func wrapGeneralizedPathExpressionSlice(ps []*generated.AnyASTGeneralizedPathExpressionProto) []ExpressionNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ExpressionNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGeneralizedPathExpression(p)
	}
	return nodes
}

func wrapGqlCallBase(p *generated.AnyASTGqlCallBaseProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTGqlCallBaseProto_AstGqlNamedCallNode:
		return newGqlNamedCallNode(v.AstGqlNamedCallNode)
	case *generated.AnyASTGqlCallBaseProto_AstGqlInlineSubqueryCallNode:
		return newGqlInlineSubqueryCallNode(v.AstGqlInlineSubqueryCallNode)
	}
	return nil
}

func wrapGqlCallBaseSlice(ps []*generated.AnyASTGqlCallBaseProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGqlCallBase(p)
	}
	return nodes
}

func wrapGqlOperator(p *generated.AnyASTGqlOperatorProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTGqlOperatorProto_AstGqlMatchNode:
		return newGqlMatchNode(v.AstGqlMatchNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlReturnNode:
		return newGqlReturnNode(v.AstGqlReturnNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlOperatorListNode:
		return newGqlOperatorListNode(v.AstGqlOperatorListNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlLetNode:
		return newGqlLetNode(v.AstGqlLetNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlFilterNode:
		return newGqlFilterNode(v.AstGqlFilterNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlOrderByAndPageNode:
		return newGqlOrderByAndPageNode(v.AstGqlOrderByAndPageNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlSetOperationNode:
		return newGqlSetOperationNode(v.AstGqlSetOperationNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlWithNode:
		return newGqlWithNode(v.AstGqlWithNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlForNode:
		return newGqlForNode(v.AstGqlForNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlSampleNode:
		return newGqlSampleNode(v.AstGqlSampleNode)
	case *generated.AnyASTGqlOperatorProto_AstGqlCallBaseNode:
		return wrapGqlCallBase(v.AstGqlCallBaseNode)
	}
	return nil
}

func wrapGqlOperatorSlice(ps []*generated.AnyASTGqlOperatorProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGqlOperator(p)
	}
	return nodes
}

func wrapGraphElementPattern(p *generated.AnyASTGraphElementPatternProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTGraphElementPatternProto_AstGraphNodePatternNode:
		return newGraphNodePatternNode(v.AstGraphNodePatternNode)
	case *generated.AnyASTGraphElementPatternProto_AstGraphEdgePatternNode:
		return newGraphEdgePatternNode(v.AstGraphEdgePatternNode)
	}
	return nil
}

func wrapGraphElementPatternSlice(ps []*generated.AnyASTGraphElementPatternProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphElementPattern(p)
	}
	return nodes
}

func wrapGraphLabelExpression(p *generated.AnyASTGraphLabelExpressionProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTGraphLabelExpressionProto_AstGraphElementLabelNode:
		return newGraphElementLabelNode(v.AstGraphElementLabelNode)
	case *generated.AnyASTGraphLabelExpressionProto_AstGraphWildcardLabelNode:
		return newGraphWildcardLabelNode(v.AstGraphWildcardLabelNode)
	case *generated.AnyASTGraphLabelExpressionProto_AstGraphLabelOperationNode:
		return newGraphLabelOperationNode(v.AstGraphLabelOperationNode)
	}
	return nil
}

func wrapGraphLabelExpressionSlice(ps []*generated.AnyASTGraphLabelExpressionProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphLabelExpression(p)
	}
	return nodes
}

func wrapGraphPathBase(p *generated.AnyASTGraphPathBaseProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTGraphPathBaseProto_AstGraphElementPatternNode:
		return wrapGraphElementPattern(v.AstGraphElementPatternNode)
	case *generated.AnyASTGraphPathBaseProto_AstGraphPathPatternNode:
		return newGraphPathPatternNode(v.AstGraphPathPatternNode)
	}
	return nil
}

func wrapGraphPathBaseSlice(ps []*generated.AnyASTGraphPathBaseProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphPathBase(p)
	}
	return nodes
}

func wrapLeaf(p *generated.AnyASTLeafProto) LeafNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTLeafProto_AstStringLiteralNode:
		return newStringLiteralNode(v.AstStringLiteralNode)
	case *generated.AnyASTLeafProto_AstNumericLiteralNode:
		return newNumericLiteralNode(v.AstNumericLiteralNode)
	case *generated.AnyASTLeafProto_AstBignumericLiteralNode:
		return newBigNumericLiteralNode(v.AstBignumericLiteralNode)
	case *generated.AnyASTLeafProto_AstBytesLiteralNode:
		return newBytesLiteralNode(v.AstBytesLiteralNode)
	case *generated.AnyASTLeafProto_AstJsonLiteralNode:
		return newJSONLiteralNode(v.AstJsonLiteralNode)
	case *generated.AnyASTLeafProto_AstPrintableLeafNode:
		return wrapPrintableLeaf(v.AstPrintableLeafNode)
	}
	return nil
}

func wrapLeafSlice(ps []*generated.AnyASTLeafProto) []LeafNode {
	if ps == nil {
		return nil
	}
	nodes := make([]LeafNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapLeaf(p)
	}
	return nodes
}

func wrapLoopStatement(p *generated.AnyASTLoopStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTLoopStatementProto_AstWhileStatementNode:
		return newWhileStatementNode(v.AstWhileStatementNode)
	case *generated.AnyASTLoopStatementProto_AstRepeatStatementNode:
		return newRepeatStatementNode(v.AstRepeatStatementNode)
	case *generated.AnyASTLoopStatementProto_AstForInStatementNode:
		return newForInStatementNode(v.AstForInStatementNode)
	}
	return nil
}

func wrapLoopStatementSlice(ps []*generated.AnyASTLoopStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapLoopStatement(p)
	}
	return nodes
}

func wrapNode(p *generated.AnyASTNodeProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTNodeProto_AstStatementNode:
		return wrapStatement(v.AstStatementNode)
	case *generated.AnyASTNodeProto_AstQueryExpressionNode:
		return wrapQueryExpression(v.AstQueryExpressionNode)
	case *generated.AnyASTNodeProto_AstSelectListNode:
		return newSelectListNode(v.AstSelectListNode)
	case *generated.AnyASTNodeProto_AstSelectColumnNode:
		return newSelectColumnNode(v.AstSelectColumnNode)
	case *generated.AnyASTNodeProto_AstExpressionNode:
		return wrapExpression(v.AstExpressionNode)
	case *generated.AnyASTNodeProto_AstAliasNode:
		return newAliasNode(v.AstAliasNode)
	case *generated.AnyASTNodeProto_AstTableExpressionNode:
		return wrapTableExpression(v.AstTableExpressionNode)
	case *generated.AnyASTNodeProto_AstFromClauseNode:
		return newFromClauseNode(v.AstFromClauseNode)
	case *generated.AnyASTNodeProto_AstWhereClauseNode:
		return newWhereClauseNode(v.AstWhereClauseNode)
	case *generated.AnyASTNodeProto_AstGroupingItemNode:
		return newGroupingItemNode(v.AstGroupingItemNode)
	case *generated.AnyASTNodeProto_AstGroupByNode:
		return newGroupByNode(v.AstGroupByNode)
	case *generated.AnyASTNodeProto_AstOrderingExpressionNode:
		return newOrderingExpressionNode(v.AstOrderingExpressionNode)
	case *generated.AnyASTNodeProto_AstOrderByNode:
		return newOrderByNode(v.AstOrderByNode)
	case *generated.AnyASTNodeProto_AstLimitOffsetNode:
		return newLimitOffsetNode(v.AstLimitOffsetNode)
	case *generated.AnyASTNodeProto_AstOnClauseNode:
		return newOnClauseNode(v.AstOnClauseNode)
	case *generated.AnyASTNodeProto_AstAliasedQueryNode:
		return newAliasedQueryNode(v.AstAliasedQueryNode)
	case *generated.AnyASTNodeProto_AstWithClauseNode:
		return newWithClauseNode(v.AstWithClauseNode)
	case *generated.AnyASTNodeProto_AstHavingNode:
		return newHavingNode(v.AstHavingNode)
	case *generated.AnyASTNodeProto_AstTypeNode:
		return wrapType(v.AstTypeNode)
	case *generated.AnyASTNodeProto_AstStructFieldNode:
		return newStructFieldNode(v.AstStructFieldNode)
	case *generated.AnyASTNodeProto_AstSelectAsNode:
		return newSelectAsNode(v.AstSelectAsNode)
	case *generated.AnyASTNodeProto_AstRollupNode:
		return newRollupNode(v.AstRollupNode)
	case *generated.AnyASTNodeProto_AstStructConstructorArgNode:
		return newStructConstructorArgNode(v.AstStructConstructorArgNode)
	case *generated.AnyASTNodeProto_AstInListNode:
		return newInListNode(v.AstInListNode)
	case *generated.AnyASTNodeProto_AstCollateNode:
		return newCollateNode(v.AstCollateNode)
	case *generated.AnyASTNodeProto_AstHavingModifierNode:
		return newHavingModifierNode(v.AstHavingModifierNode)
	case *generated.AnyASTNodeProto_AstNullOrderNode:
		return newNullOrderNode(v.AstNullOrderNode)
	case *generated.AnyASTNodeProto_AstOnOrUsingClauseListNode:
		return newOnOrUsingClauseListNode(v.AstOnOrUsingClauseListNode)
	case *generated.AnyASTNodeProto_AstPartitionByNode:
		return newPartitionByNode(v.AstPartitionByNode)
	case *generated.AnyASTNodeProto_AstStarExceptListNode:
		return newStarExceptListNode(v.AstStarExceptListNode)
	case *generated.AnyASTNodeProto_AstStarModifiersNode:
		return newStarModifiersNode(v.AstStarModifiersNode)
	case *generated.AnyASTNodeProto_AstStarReplaceItemNode:
		return newStarReplaceItemNode(v.AstStarReplaceItemNode)
	case *generated.AnyASTNodeProto_AstUnnestExpressionNode:
		return newUnnestExpressionNode(v.AstUnnestExpressionNode)
	case *generated.AnyASTNodeProto_AstWindowClauseNode:
		return newWindowClauseNode(v.AstWindowClauseNode)
	case *generated.AnyASTNodeProto_AstWindowDefinitionNode:
		return newWindowDefinitionNode(v.AstWindowDefinitionNode)
	case *generated.AnyASTNodeProto_AstWindowFrameNode:
		return newWindowFrameNode(v.AstWindowFrameNode)
	case *generated.AnyASTNodeProto_AstWindowFrameExprNode:
		return newWindowFrameExprNode(v.AstWindowFrameExprNode)
	case *generated.AnyASTNodeProto_AstWindowSpecificationNode:
		return newWindowSpecificationNode(v.AstWindowSpecificationNode)
	case *generated.AnyASTNodeProto_AstWithOffsetNode:
		return newWithOffsetNode(v.AstWithOffsetNode)
	case *generated.AnyASTNodeProto_AstAnySomeAllOpNode:
		return newAnySomeAllOpNode(v.AstAnySomeAllOpNode)
	case *generated.AnyASTNodeProto_AstStatementListNode:
		return newStatementListNode(v.AstStatementListNode)
	case *generated.AnyASTNodeProto_AstTransactionModeNode:
		return wrapTransactionMode(v.AstTransactionModeNode)
	case *generated.AnyASTNodeProto_AstTransactionModeListNode:
		return newTransactionModeListNode(v.AstTransactionModeListNode)
	case *generated.AnyASTNodeProto_AstWithConnectionClauseNode:
		return newWithConnectionClauseNode(v.AstWithConnectionClauseNode)
	case *generated.AnyASTNodeProto_AstIntoAliasNode:
		return newIntoAliasNode(v.AstIntoAliasNode)
	case *generated.AnyASTNodeProto_AstUnnestExpressionWithOptAliasAndOffsetNode:
		return newUnnestExpressionWithOptAliasAndOffsetNode(v.AstUnnestExpressionWithOptAliasAndOffsetNode)
	case *generated.AnyASTNodeProto_AstPivotExpressionNode:
		return newPivotExpressionNode(v.AstPivotExpressionNode)
	case *generated.AnyASTNodeProto_AstPivotValueNode:
		return newPivotValueNode(v.AstPivotValueNode)
	case *generated.AnyASTNodeProto_AstPivotExpressionListNode:
		return newPivotExpressionListNode(v.AstPivotExpressionListNode)
	case *generated.AnyASTNodeProto_AstPivotValueListNode:
		return newPivotValueListNode(v.AstPivotValueListNode)
	case *generated.AnyASTNodeProto_AstUnpivotInItemNode:
		return newUnpivotInItemNode(v.AstUnpivotInItemNode)
	case *generated.AnyASTNodeProto_AstUnpivotInItemListNode:
		return newUnpivotInItemListNode(v.AstUnpivotInItemListNode)
	case *generated.AnyASTNodeProto_AstUsingClauseNode:
		return newUsingClauseNode(v.AstUsingClauseNode)
	case *generated.AnyASTNodeProto_AstForSystemTimeNode:
		return newForSystemTimeNode(v.AstForSystemTimeNode)
	case *generated.AnyASTNodeProto_AstQualifyNode:
		return newQualifyNode(v.AstQualifyNode)
	case *generated.AnyASTNodeProto_AstClampedBetweenModifierNode:
		return newClampedBetweenModifierNode(v.AstClampedBetweenModifierNode)
	case *generated.AnyASTNodeProto_AstFormatClauseNode:
		return newFormatClauseNode(v.AstFormatClauseNode)
	case *generated.AnyASTNodeProto_AstPathExpressionListNode:
		return newPathExpressionListNode(v.AstPathExpressionListNode)
	case *generated.AnyASTNodeProto_AstClusterByNode:
		return newClusterByNode(v.AstClusterByNode)
	case *generated.AnyASTNodeProto_AstNewConstructorArgNode:
		return newNewConstructorArgNode(v.AstNewConstructorArgNode)
	case *generated.AnyASTNodeProto_AstOptionsListNode:
		return newOptionsListNode(v.AstOptionsListNode)
	case *generated.AnyASTNodeProto_AstOptionsEntryNode:
		return newOptionsEntryNode(v.AstOptionsEntryNode)
	case *generated.AnyASTNodeProto_AstFunctionParameterNode:
		return newFunctionParameterNode(v.AstFunctionParameterNode)
	case *generated.AnyASTNodeProto_AstFunctionParametersNode:
		return newFunctionParametersNode(v.AstFunctionParametersNode)
	case *generated.AnyASTNodeProto_AstFunctionDeclarationNode:
		return newFunctionDeclarationNode(v.AstFunctionDeclarationNode)
	case *generated.AnyASTNodeProto_AstSqlFunctionBodyNode:
		return newSqlFunctionBodyNode(v.AstSqlFunctionBodyNode)
	case *generated.AnyASTNodeProto_AstTvfArgumentNode:
		return newTVFArgumentNode(v.AstTvfArgumentNode)
	case *generated.AnyASTNodeProto_AstModelClauseNode:
		return newModelClauseNode(v.AstModelClauseNode)
	case *generated.AnyASTNodeProto_AstConnectionClauseNode:
		return newConnectionClauseNode(v.AstConnectionClauseNode)
	case *generated.AnyASTNodeProto_AstCloneDataSourceListNode:
		return newCloneDataSourceListNode(v.AstCloneDataSourceListNode)
	case *generated.AnyASTNodeProto_AstTransformClauseNode:
		return newTransformClauseNode(v.AstTransformClauseNode)
	case *generated.AnyASTNodeProto_AstIndexItemListNode:
		return newIndexItemListNode(v.AstIndexItemListNode)
	case *generated.AnyASTNodeProto_AstIndexStoringExpressionListNode:
		return newIndexStoringExpressionListNode(v.AstIndexStoringExpressionListNode)
	case *generated.AnyASTNodeProto_AstIndexUnnestExpressionListNode:
		return newIndexUnnestExpressionListNode(v.AstIndexUnnestExpressionListNode)
	case *generated.AnyASTNodeProto_AstWithPartitionColumnsClauseNode:
		return newWithPartitionColumnsClauseNode(v.AstWithPartitionColumnsClauseNode)
	case *generated.AnyASTNodeProto_AstTypeParameterListNode:
		return newTypeParameterListNode(v.AstTypeParameterListNode)
	case *generated.AnyASTNodeProto_AstTvfSchemaNode:
		return newTVFSchemaNode(v.AstTvfSchemaNode)
	case *generated.AnyASTNodeProto_AstTvfSchemaColumnNode:
		return newTVFSchemaColumnNode(v.AstTvfSchemaColumnNode)
	case *generated.AnyASTNodeProto_AstTableAndColumnInfoNode:
		return newTableAndColumnInfoNode(v.AstTableAndColumnInfoNode)
	case *generated.AnyASTNodeProto_AstTableAndColumnInfoListNode:
		return newTableAndColumnInfoListNode(v.AstTableAndColumnInfoListNode)
	case *generated.AnyASTNodeProto_AstTemplatedParameterTypeNode:
		return newTemplatedParameterTypeNode(v.AstTemplatedParameterTypeNode)
	case *generated.AnyASTNodeProto_AstAssertRowsModifiedNode:
		return newAssertRowsModifiedNode(v.AstAssertRowsModifiedNode)
	case *generated.AnyASTNodeProto_AstReturningClauseNode:
		return newReturningClauseNode(v.AstReturningClauseNode)
	case *generated.AnyASTNodeProto_AstColumnAttributeNode:
		return wrapColumnAttribute(v.AstColumnAttributeNode)
	case *generated.AnyASTNodeProto_AstColumnAttributeListNode:
		return newColumnAttributeListNode(v.AstColumnAttributeListNode)
	case *generated.AnyASTNodeProto_AstStructColumnFieldNode:
		return newStructColumnFieldNode(v.AstStructColumnFieldNode)
	case *generated.AnyASTNodeProto_AstGeneratedColumnInfoNode:
		return newGeneratedColumnInfoNode(v.AstGeneratedColumnInfoNode)
	case *generated.AnyASTNodeProto_AstTableElementNode:
		return wrapTableElement(v.AstTableElementNode)
	case *generated.AnyASTNodeProto_AstTableElementListNode:
		return newTableElementListNode(v.AstTableElementListNode)
	case *generated.AnyASTNodeProto_AstColumnListNode:
		return newColumnListNode(v.AstColumnListNode)
	case *generated.AnyASTNodeProto_AstColumnPositionNode:
		return newColumnPositionNode(v.AstColumnPositionNode)
	case *generated.AnyASTNodeProto_AstInsertValuesRowNode:
		return newInsertValuesRowNode(v.AstInsertValuesRowNode)
	case *generated.AnyASTNodeProto_AstInsertValuesRowListNode:
		return newInsertValuesRowListNode(v.AstInsertValuesRowListNode)
	case *generated.AnyASTNodeProto_AstUpdateSetValueNode:
		return newUpdateSetValueNode(v.AstUpdateSetValueNode)
	case *generated.AnyASTNodeProto_AstUpdateItemNode:
		return newUpdateItemNode(v.AstUpdateItemNode)
	case *generated.AnyASTNodeProto_AstUpdateItemListNode:
		return newUpdateItemListNode(v.AstUpdateItemListNode)
	case *generated.AnyASTNodeProto_AstMergeActionNode:
		return newMergeActionNode(v.AstMergeActionNode)
	case *generated.AnyASTNodeProto_AstMergeWhenClauseNode:
		return newMergeWhenClauseNode(v.AstMergeWhenClauseNode)
	case *generated.AnyASTNodeProto_AstMergeWhenClauseListNode:
		return newMergeWhenClauseListNode(v.AstMergeWhenClauseListNode)
	case *generated.AnyASTNodeProto_AstPrivilegeNode:
		return newPrivilegeNode(v.AstPrivilegeNode)
	case *generated.AnyASTNodeProto_AstPrivilegesNode:
		return newPrivilegesNode(v.AstPrivilegesNode)
	case *generated.AnyASTNodeProto_AstGranteeListNode:
		return newGranteeListNode(v.AstGranteeListNode)
	case *generated.AnyASTNodeProto_AstRepeatableClauseNode:
		return newRepeatableClauseNode(v.AstRepeatableClauseNode)
	case *generated.AnyASTNodeProto_AstFilterFieldsArgNode:
		return newFilterFieldsArgNode(v.AstFilterFieldsArgNode)
	case *generated.AnyASTNodeProto_AstReplaceFieldsArgNode:
		return newReplaceFieldsArgNode(v.AstReplaceFieldsArgNode)
	case *generated.AnyASTNodeProto_AstSampleSizeNode:
		return newSampleSizeNode(v.AstSampleSizeNode)
	case *generated.AnyASTNodeProto_AstWithWeightNode:
		return newWithWeightNode(v.AstWithWeightNode)
	case *generated.AnyASTNodeProto_AstSampleSuffixNode:
		return newSampleSuffixNode(v.AstSampleSuffixNode)
	case *generated.AnyASTNodeProto_AstAlterActionNode:
		return wrapAlterAction(v.AstAlterActionNode)
	case *generated.AnyASTNodeProto_AstAlterActionListNode:
		return newAlterActionListNode(v.AstAlterActionListNode)
	case *generated.AnyASTNodeProto_AstForeignKeyActionsNode:
		return newForeignKeyActionsNode(v.AstForeignKeyActionsNode)
	case *generated.AnyASTNodeProto_AstForeignKeyReferenceNode:
		return newForeignKeyReferenceNode(v.AstForeignKeyReferenceNode)
	case *generated.AnyASTNodeProto_AstScriptNode:
		return newScriptNode(v.AstScriptNode)
	case *generated.AnyASTNodeProto_AstElseifClauseNode:
		return newElseifClauseNode(v.AstElseifClauseNode)
	case *generated.AnyASTNodeProto_AstElseifClauseListNode:
		return newElseifClauseListNode(v.AstElseifClauseListNode)
	case *generated.AnyASTNodeProto_AstWhenThenClauseNode:
		return newWhenThenClauseNode(v.AstWhenThenClauseNode)
	case *generated.AnyASTNodeProto_AstWhenThenClauseListNode:
		return newWhenThenClauseListNode(v.AstWhenThenClauseListNode)
	case *generated.AnyASTNodeProto_AstHintNode:
		return newHintNode(v.AstHintNode)
	case *generated.AnyASTNodeProto_AstHintEntryNode:
		return newHintEntryNode(v.AstHintEntryNode)
	case *generated.AnyASTNodeProto_AstUnpivotInItemLabelNode:
		return newUnpivotInItemLabelNode(v.AstUnpivotInItemLabelNode)
	case *generated.AnyASTNodeProto_AstDescriptorNode:
		return newDescriptorNode(v.AstDescriptorNode)
	case *generated.AnyASTNodeProto_AstColumnSchemaNode:
		return wrapColumnSchema(v.AstColumnSchemaNode)
	case *generated.AnyASTNodeProto_AstDescriptorColumnNode:
		return newDescriptorColumnNode(v.AstDescriptorColumnNode)
	case *generated.AnyASTNodeProto_AstDescriptorColumnListNode:
		return newDescriptorColumnListNode(v.AstDescriptorColumnListNode)
	case *generated.AnyASTNodeProto_AstExceptionHandlerNode:
		return newExceptionHandlerNode(v.AstExceptionHandlerNode)
	case *generated.AnyASTNodeProto_AstExceptionHandlerListNode:
		return newExceptionHandlerListNode(v.AstExceptionHandlerListNode)
	case *generated.AnyASTNodeProto_AstIdentifierListNode:
		return newIdentifierListNode(v.AstIdentifierListNode)
	case *generated.AnyASTNodeProto_AstUntilClauseNode:
		return newUntilClauseNode(v.AstUntilClauseNode)
	case *generated.AnyASTNodeProto_AstExecuteIntoClauseNode:
		return newExecuteIntoClauseNode(v.AstExecuteIntoClauseNode)
	case *generated.AnyASTNodeProto_AstExecuteUsingArgumentNode:
		return newExecuteUsingArgumentNode(v.AstExecuteUsingArgumentNode)
	case *generated.AnyASTNodeProto_AstExecuteUsingClauseNode:
		return newExecuteUsingClauseNode(v.AstExecuteUsingClauseNode)
	case *generated.AnyASTNodeProto_AstBracedConstructorFieldValueNode:
		return newBracedConstructorFieldValueNode(v.AstBracedConstructorFieldValueNode)
	case *generated.AnyASTNodeProto_AstBracedConstructorFieldNode:
		return newBracedConstructorFieldNode(v.AstBracedConstructorFieldNode)
	case *generated.AnyASTNodeProto_AstWithReportModifierNode:
		return newWithReportModifierNode(v.AstWithReportModifierNode)
	case *generated.AnyASTNodeProto_AstLocationNode:
		return newLocationNode(v.AstLocationNode)
	case *generated.AnyASTNodeProto_AstAuxLoadDataFromFilesOptionsListNode:
		return newAuxLoadDataFromFilesOptionsListNode(v.AstAuxLoadDataFromFilesOptionsListNode)
	case *generated.AnyASTNodeProto_AstLabelNode:
		return newLabelNode(v.AstLabelNode)
	case *generated.AnyASTNodeProto_AstPrimaryKeyElementNode:
		return newPrimaryKeyElementNode(v.AstPrimaryKeyElementNode)
	case *generated.AnyASTNodeProto_AstPrimaryKeyElementListNode:
		return newPrimaryKeyElementListNode(v.AstPrimaryKeyElementListNode)
	case *generated.AnyASTNodeProto_AstSpannerTableOptionsNode:
		return newSpannerTableOptionsNode(v.AstSpannerTableOptionsNode)
	case *generated.AnyASTNodeProto_AstSpannerInterleaveClauseNode:
		return newSpannerInterleaveClauseNode(v.AstSpannerInterleaveClauseNode)
	case *generated.AnyASTNodeProto_AstTtlClauseNode:
		return newTtlClauseNode(v.AstTtlClauseNode)
	case *generated.AnyASTNodeProto_AstInputOutputClauseNode:
		return newInputOutputClauseNode(v.AstInputOutputClauseNode)
	case *generated.AnyASTNodeProto_AstGraphLabelExpressionNode:
		return wrapGraphLabelExpression(v.AstGraphLabelExpressionNode)
	case *generated.AnyASTNodeProto_AstGraphLabelFilterNode:
		return newGraphLabelFilterNode(v.AstGraphLabelFilterNode)
	case *generated.AnyASTNodeProto_AstWithModifierNode:
		return newWithModifierNode(v.AstWithModifierNode)
	case *generated.AnyASTNodeProto_AstAliasedQueryListNode:
		return newAliasedQueryListNode(v.AstAliasedQueryListNode)
	case *generated.AnyASTNodeProto_AstColumnWithOptionsNode:
		return newColumnWithOptionsNode(v.AstColumnWithOptionsNode)
	case *generated.AnyASTNodeProto_AstColumnWithOptionsListNode:
		return newColumnWithOptionsListNode(v.AstColumnWithOptionsListNode)
	case *generated.AnyASTNodeProto_AstGraphElementPatternFillerNode:
		return newGraphElementPatternFillerNode(v.AstGraphElementPatternFillerNode)
	case *generated.AnyASTNodeProto_AstGraphElementTableListNode:
		return newGraphElementTableListNode(v.AstGraphElementTableListNode)
	case *generated.AnyASTNodeProto_AstGraphElementTableNode:
		return newGraphElementTableNode(v.AstGraphElementTableNode)
	case *generated.AnyASTNodeProto_AstGraphNodeTableReferenceNode:
		return newGraphNodeTableReferenceNode(v.AstGraphNodeTableReferenceNode)
	case *generated.AnyASTNodeProto_AstAuxLoadDataPartitionsClauseNode:
		return newAuxLoadDataPartitionsClauseNode(v.AstAuxLoadDataPartitionsClauseNode)
	case *generated.AnyASTNodeProto_AstGraphElementLabelAndPropertiesListNode:
		return newGraphElementLabelAndPropertiesListNode(v.AstGraphElementLabelAndPropertiesListNode)
	case *generated.AnyASTNodeProto_AstGraphElementLabelAndPropertiesNode:
		return newGraphElementLabelAndPropertiesNode(v.AstGraphElementLabelAndPropertiesNode)
	case *generated.AnyASTNodeProto_AstGraphPropertiesNode:
		return newGraphPropertiesNode(v.AstGraphPropertiesNode)
	case *generated.AnyASTNodeProto_AstSetOperationMetadataListNode:
		return newSetOperationMetadataListNode(v.AstSetOperationMetadataListNode)
	case *generated.AnyASTNodeProto_AstSetOperationAllOrDistinctNode:
		return newSetOperationAllOrDistinctNode(v.AstSetOperationAllOrDistinctNode)
	case *generated.AnyASTNodeProto_AstSetOperationTypeNode:
		return newSetOperationTypeNode(v.AstSetOperationTypeNode)
	case *generated.AnyASTNodeProto_AstSetOperationMetadataNode:
		return newSetOperationMetadataNode(v.AstSetOperationMetadataNode)
	case *generated.AnyASTNodeProto_AstSetOperationColumnMatchModeNode:
		return newSetOperationColumnMatchModeNode(v.AstSetOperationColumnMatchModeNode)
	case *generated.AnyASTNodeProto_AstSetOperationColumnPropagationModeNode:
		return newSetOperationColumnPropagationModeNode(v.AstSetOperationColumnPropagationModeNode)
	case *generated.AnyASTNodeProto_AstGraphPatternNode:
		return newGraphPatternNode(v.AstGraphPatternNode)
	case *generated.AnyASTNodeProto_AstCubeNode:
		return newCubeNode(v.AstCubeNode)
	case *generated.AnyASTNodeProto_AstGroupingSetNode:
		return newGroupingSetNode(v.AstGroupingSetNode)
	case *generated.AnyASTNodeProto_AstGroupingSetListNode:
		return newGroupingSetListNode(v.AstGroupingSetListNode)
	case *generated.AnyASTNodeProto_AstExpressionWithOptAliasNode:
		return newExpressionWithOptAliasNode(v.AstExpressionWithOptAliasNode)
	case *generated.AnyASTNodeProto_AstGroupByAllNode:
		return newGroupByAllNode(v.AstGroupByAllNode)
	case *generated.AnyASTNodeProto_AstFunctionTypeArgListNode:
		return newFunctionTypeArgListNode(v.AstFunctionTypeArgListNode)
	case *generated.AnyASTNodeProto_AstPipeOperatorNode:
		return wrapPipeOperator(v.AstPipeOperatorNode)
	case *generated.AnyASTNodeProto_AstGraphLhsHintNode:
		return newGraphLhsHintNode(v.AstGraphLhsHintNode)
	case *generated.AnyASTNodeProto_AstGraphRhsHintNode:
		return newGraphRhsHintNode(v.AstGraphRhsHintNode)
	case *generated.AnyASTNodeProto_AstIdentityColumnInfoNode:
		return newIdentityColumnInfoNode(v.AstIdentityColumnInfoNode)
	case *generated.AnyASTNodeProto_AstIdentityColumnStartWithNode:
		return newIdentityColumnStartWithNode(v.AstIdentityColumnStartWithNode)
	case *generated.AnyASTNodeProto_AstIdentityColumnIncrementByNode:
		return newIdentityColumnIncrementByNode(v.AstIdentityColumnIncrementByNode)
	case *generated.AnyASTNodeProto_AstIdentityColumnMaxValueNode:
		return newIdentityColumnMaxValueNode(v.AstIdentityColumnMaxValueNode)
	case *generated.AnyASTNodeProto_AstIdentityColumnMinValueNode:
		return newIdentityColumnMinValueNode(v.AstIdentityColumnMinValueNode)
	case *generated.AnyASTNodeProto_AstGraphPathBaseNode:
		return wrapGraphPathBase(v.AstGraphPathBaseNode)
	case *generated.AnyASTNodeProto_AstGqlOperatorNode:
		return wrapGqlOperator(v.AstGqlOperatorNode)
	case *generated.AnyASTNodeProto_AstGqlLetVariableDefinitionListNode:
		return newGqlLetVariableDefinitionListNode(v.AstGqlLetVariableDefinitionListNode)
	case *generated.AnyASTNodeProto_AstGqlLetVariableDefinitionNode:
		return newGqlLetVariableDefinitionNode(v.AstGqlLetVariableDefinitionNode)
	case *generated.AnyASTNodeProto_AstPipeSetItemNode:
		return newPipeSetItemNode(v.AstPipeSetItemNode)
	case *generated.AnyASTNodeProto_AstGraphPropertySpecificationNode:
		return newGraphPropertySpecificationNode(v.AstGraphPropertySpecificationNode)
	case *generated.AnyASTNodeProto_AstGraphPropertyNameAndValueNode:
		return newGraphPropertyNameAndValueNode(v.AstGraphPropertyNameAndValueNode)
	case *generated.AnyASTNodeProto_AstGqlPageLimitNode:
		return newGqlPageLimitNode(v.AstGqlPageLimitNode)
	case *generated.AnyASTNodeProto_AstGqlPageOffsetNode:
		return newGqlPageOffsetNode(v.AstGqlPageOffsetNode)
	case *generated.AnyASTNodeProto_AstGqlPageNode:
		return newGqlPageNode(v.AstGqlPageNode)
	case *generated.AnyASTNodeProto_AstAliasedQueryModifiersNode:
		return newAliasedQueryModifiersNode(v.AstAliasedQueryModifiersNode)
	case *generated.AnyASTNodeProto_AstRecursionDepthModifierNode:
		return newRecursionDepthModifierNode(v.AstRecursionDepthModifierNode)
	case *generated.AnyASTNodeProto_AstGroupingItemOrderNode:
		return newGroupingItemOrderNode(v.AstGroupingItemOrderNode)
	case *generated.AnyASTNodeProto_AstGraphPathModeNode:
		return newGraphPathModeNode(v.AstGraphPathModeNode)
	case *generated.AnyASTNodeProto_AstGraphPathSearchPrefixNode:
		return newGraphPathSearchPrefixNode(v.AstGraphPathSearchPrefixNode)
	case *generated.AnyASTNodeProto_AstLockModeNode:
		return newLockModeNode(v.AstLockModeNode)
	case *generated.AnyASTNodeProto_AstRowPatternExpressionNode:
		return wrapRowPatternExpression(v.AstRowPatternExpressionNode)
	case *generated.AnyASTNodeProto_AstPostfixTableOperatorNode:
		return wrapPostfixTableOperator(v.AstPostfixTableOperatorNode)
	case *generated.AnyASTNodeProto_AstQuantifierNode:
		return wrapQuantifier(v.AstQuantifierNode)
	case *generated.AnyASTNodeProto_AstQuantifierBoundNode:
		return newQuantifierBoundNode(v.AstQuantifierBoundNode)
	case *generated.AnyASTNodeProto_AstSubpipelineNode:
		return newSubpipelineNode(v.AstSubpipelineNode)
	case *generated.AnyASTNodeProto_AstAfterMatchSkipClauseNode:
		return newAfterMatchSkipClauseNode(v.AstAfterMatchSkipClauseNode)
	case *generated.AnyASTNodeProto_AstOnConflictClauseNode:
		return newOnConflictClauseNode(v.AstOnConflictClauseNode)
	case *generated.AnyASTNodeProto_AstGraphDynamicLabelNode:
		return newGraphDynamicLabelNode(v.AstGraphDynamicLabelNode)
	case *generated.AnyASTNodeProto_AstGraphDynamicPropertiesNode:
		return newGraphDynamicPropertiesNode(v.AstGraphDynamicPropertiesNode)
	case *generated.AnyASTNodeProto_AstGraphPathSearchPrefixCountNode:
		return newGraphPathSearchPrefixCountNode(v.AstGraphPathSearchPrefixCountNode)
	case *generated.AnyASTNodeProto_AstChainedBaseExprNode:
		return newChainedBaseExprNode(v.AstChainedBaseExprNode)
	case *generated.AnyASTNodeProto_AstYieldItemListNode:
		return newYieldItemListNode(v.AstYieldItemListNode)
	case *generated.AnyASTNodeProto_AstLimitAllNode:
		return newLimitAllNode(v.AstLimitAllNode)
	case *generated.AnyASTNodeProto_AstLimitNode:
		return newLimitNode(v.AstLimitNode)
	case *generated.AnyASTNodeProto_AstGraphDerivedPropertyNode:
		return newGraphDerivedPropertyNode(v.AstGraphDerivedPropertyNode)
	case *generated.AnyASTNodeProto_AstGraphDerivedPropertyListNode:
		return newGraphDerivedPropertyListNode(v.AstGraphDerivedPropertyListNode)
	case *generated.AnyASTNodeProto_AstWithClauseEntryNode:
		return newWithClauseEntryNode(v.AstWithClauseEntryNode)
	case *generated.AnyASTNodeProto_AstAliasedGroupRowsNode:
		return newAliasedGroupRowsNode(v.AstAliasedGroupRowsNode)
	}
	return nil
}

func wrapNodeSlice(ps []*generated.AnyASTNodeProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapNode(p)
	}
	return nodes
}

func wrapParameterExprBase(p *generated.AnyASTParameterExprBaseProto) ExpressionNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTParameterExprBaseProto_AstParameterExprNode:
		return newParameterExprNode(v.AstParameterExprNode)
	case *generated.AnyASTParameterExprBaseProto_AstSystemVariableExprNode:
		return newSystemVariableExprNode(v.AstSystemVariableExprNode)
	}
	return nil
}

func wrapParameterExprBaseSlice(ps []*generated.AnyASTParameterExprBaseProto) []ExpressionNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ExpressionNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapParameterExprBase(p)
	}
	return nodes
}

func wrapPipeOperator(p *generated.AnyASTPipeOperatorProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTPipeOperatorProto_AstPipeExtendNode:
		return newPipeExtendNode(v.AstPipeExtendNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeAggregateNode:
		return newPipeAggregateNode(v.AstPipeAggregateNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeSetOperationNode:
		return newPipeSetOperationNode(v.AstPipeSetOperationNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeJoinNode:
		return newPipeJoinNode(v.AstPipeJoinNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeCallNode:
		return newPipeCallNode(v.AstPipeCallNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeWindowNode:
		return newPipeWindowNode(v.AstPipeWindowNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeWhereNode:
		return newPipeWhereNode(v.AstPipeWhereNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeSelectNode:
		return newPipeSelectNode(v.AstPipeSelectNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeLimitOffsetNode:
		return newPipeLimitOffsetNode(v.AstPipeLimitOffsetNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeOrderByNode:
		return newPipeOrderByNode(v.AstPipeOrderByNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeDistinctNode:
		return newPipeDistinctNode(v.AstPipeDistinctNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeTablesampleNode:
		return newPipeTablesampleNode(v.AstPipeTablesampleNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeAsNode:
		return newPipeAsNode(v.AstPipeAsNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeStaticDescribeNode:
		return newPipeStaticDescribeNode(v.AstPipeStaticDescribeNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeAssertNode:
		return newPipeAssertNode(v.AstPipeAssertNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeDropNode:
		return newPipeDropNode(v.AstPipeDropNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeSetNode:
		return newPipeSetNode(v.AstPipeSetNode)
	case *generated.AnyASTPipeOperatorProto_AstPipePivotNode:
		return newPipePivotNode(v.AstPipePivotNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeUnpivotNode:
		return newPipeUnpivotNode(v.AstPipeUnpivotNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeRenameItemNode:
		return newPipeRenameItemNode(v.AstPipeRenameItemNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeRenameNode:
		return newPipeRenameNode(v.AstPipeRenameNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeLogNode:
		return newPipeLogNode(v.AstPipeLogNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeIfNode:
		return newPipeIfNode(v.AstPipeIfNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeIfCaseNode:
		return newPipeIfCaseNode(v.AstPipeIfCaseNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeForkNode:
		return newPipeForkNode(v.AstPipeForkNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeExportDataNode:
		return newPipeExportDataNode(v.AstPipeExportDataNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeRecursiveUnionNode:
		return newPipeRecursiveUnionNode(v.AstPipeRecursiveUnionNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeMatchRecognizeNode:
		return newPipeMatchRecognizeNode(v.AstPipeMatchRecognizeNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeCreateTableNode:
		return newPipeCreateTableNode(v.AstPipeCreateTableNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeTeeNode:
		return newPipeTeeNode(v.AstPipeTeeNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeInsertNode:
		return newPipeInsertNode(v.AstPipeInsertNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeWithNode:
		return newPipeWithNode(v.AstPipeWithNode)
	case *generated.AnyASTPipeOperatorProto_AstPipeDescribeNode:
		return newPipeDescribeNode(v.AstPipeDescribeNode)
	}
	return nil
}

func wrapPipeOperatorSlice(ps []*generated.AnyASTPipeOperatorProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapPipeOperator(p)
	}
	return nodes
}

func wrapPostfixTableOperator(p *generated.AnyASTPostfixTableOperatorProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTPostfixTableOperatorProto_AstPivotClauseNode:
		return newPivotClauseNode(v.AstPivotClauseNode)
	case *generated.AnyASTPostfixTableOperatorProto_AstUnpivotClauseNode:
		return newUnpivotClauseNode(v.AstUnpivotClauseNode)
	case *generated.AnyASTPostfixTableOperatorProto_AstSampleClauseNode:
		return newSampleClauseNode(v.AstSampleClauseNode)
	case *generated.AnyASTPostfixTableOperatorProto_AstMatchRecognizeClauseNode:
		return newMatchRecognizeClauseNode(v.AstMatchRecognizeClauseNode)
	}
	return nil
}

func wrapPostfixTableOperatorSlice(ps []*generated.AnyASTPostfixTableOperatorProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapPostfixTableOperator(p)
	}
	return nodes
}

func wrapPrintableLeaf(p *generated.AnyASTPrintableLeafProto) LeafNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTPrintableLeafProto_AstIntLiteralNode:
		return newIntLiteralNode(v.AstIntLiteralNode)
	case *generated.AnyASTPrintableLeafProto_AstBooleanLiteralNode:
		return newBooleanLiteralNode(v.AstBooleanLiteralNode)
	case *generated.AnyASTPrintableLeafProto_AstStarNode:
		return newStarNode(v.AstStarNode)
	case *generated.AnyASTPrintableLeafProto_AstFloatLiteralNode:
		return newFloatLiteralNode(v.AstFloatLiteralNode)
	case *generated.AnyASTPrintableLeafProto_AstNullLiteralNode:
		return newNullLiteralNode(v.AstNullLiteralNode)
	case *generated.AnyASTPrintableLeafProto_AstMaxLiteralNode:
		return newMaxLiteralNode(v.AstMaxLiteralNode)
	case *generated.AnyASTPrintableLeafProto_AstIndexAllColumnsNode:
		return newIndexAllColumnsNode(v.AstIndexAllColumnsNode)
	case *generated.AnyASTPrintableLeafProto_AstMacroBodyNode:
		return newMacroBodyNode(v.AstMacroBodyNode)
	case *generated.AnyASTPrintableLeafProto_AstStringLiteralComponentNode:
		return newStringLiteralComponentNode(v.AstStringLiteralComponentNode)
	case *generated.AnyASTPrintableLeafProto_AstBytesLiteralComponentNode:
		return newBytesLiteralComponentNode(v.AstBytesLiteralComponentNode)
	}
	return nil
}

func wrapPrintableLeafSlice(ps []*generated.AnyASTPrintableLeafProto) []LeafNode {
	if ps == nil {
		return nil
	}
	nodes := make([]LeafNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapPrintableLeaf(p)
	}
	return nodes
}

func wrapQuantifier(p *generated.AnyASTQuantifierProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTQuantifierProto_AstBoundedQuantifierNode:
		return newBoundedQuantifierNode(v.AstBoundedQuantifierNode)
	case *generated.AnyASTQuantifierProto_AstFixedQuantifierNode:
		return newFixedQuantifierNode(v.AstFixedQuantifierNode)
	case *generated.AnyASTQuantifierProto_AstSymbolQuantifierNode:
		return newSymbolQuantifierNode(v.AstSymbolQuantifierNode)
	}
	return nil
}

func wrapQuantifierSlice(ps []*generated.AnyASTQuantifierProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapQuantifier(p)
	}
	return nodes
}

func wrapQueryExpression(p *generated.AnyASTQueryExpressionProto) QueryExpressionNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTQueryExpressionProto_AstQueryNode:
		return newQueryNode(v.AstQueryNode)
	case *generated.AnyASTQueryExpressionProto_AstSelectNode:
		return newSelectNode(v.AstSelectNode)
	case *generated.AnyASTQueryExpressionProto_AstSetOperationNode:
		return newSetOperationNode(v.AstSetOperationNode)
	case *generated.AnyASTQueryExpressionProto_AstTableClauseNode:
		return newTableClauseNode(v.AstTableClauseNode)
	case *generated.AnyASTQueryExpressionProto_AstFromQueryNode:
		return newFromQueryNode(v.AstFromQueryNode)
	case *generated.AnyASTQueryExpressionProto_AstGqlQueryNode:
		return newGqlQueryNode(v.AstGqlQueryNode)
	case *generated.AnyASTQueryExpressionProto_AstAliasedQueryExpressionNode:
		return newAliasedQueryExpressionNode(v.AstAliasedQueryExpressionNode)
	case *generated.AnyASTQueryExpressionProto_AstGqlGraphPatternQueryNode:
		return newGqlGraphPatternQueryNode(v.AstGqlGraphPatternQueryNode)
	case *generated.AnyASTQueryExpressionProto_AstGqlLinearOpsQueryNode:
		return newGqlLinearOpsQueryNode(v.AstGqlLinearOpsQueryNode)
	}
	return nil
}

func wrapQueryExpressionSlice(ps []*generated.AnyASTQueryExpressionProto) []QueryExpressionNode {
	if ps == nil {
		return nil
	}
	nodes := make([]QueryExpressionNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapQueryExpression(p)
	}
	return nodes
}

func wrapRowPatternExpression(p *generated.AnyASTRowPatternExpressionProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTRowPatternExpressionProto_AstRowPatternVariableNode:
		return newRowPatternVariableNode(v.AstRowPatternVariableNode)
	case *generated.AnyASTRowPatternExpressionProto_AstRowPatternOperationNode:
		return newRowPatternOperationNode(v.AstRowPatternOperationNode)
	case *generated.AnyASTRowPatternExpressionProto_AstEmptyRowPatternNode:
		return newEmptyRowPatternNode(v.AstEmptyRowPatternNode)
	case *generated.AnyASTRowPatternExpressionProto_AstRowPatternQuantificationNode:
		return newRowPatternQuantificationNode(v.AstRowPatternQuantificationNode)
	case *generated.AnyASTRowPatternExpressionProto_AstRowPatternAnchorNode:
		return newRowPatternAnchorNode(v.AstRowPatternAnchorNode)
	}
	return nil
}

func wrapRowPatternExpressionSlice(ps []*generated.AnyASTRowPatternExpressionProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapRowPatternExpression(p)
	}
	return nodes
}

func wrapScriptStatement(p *generated.AnyASTScriptStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTScriptStatementProto_AstIfStatementNode:
		return newIfStatementNode(v.AstIfStatementNode)
	case *generated.AnyASTScriptStatementProto_AstCaseStatementNode:
		return newCaseStatementNode(v.AstCaseStatementNode)
	case *generated.AnyASTScriptStatementProto_AstRaiseStatementNode:
		return newRaiseStatementNode(v.AstRaiseStatementNode)
	case *generated.AnyASTScriptStatementProto_AstBeginEndBlockNode:
		return newBeginEndBlockNode(v.AstBeginEndBlockNode)
	case *generated.AnyASTScriptStatementProto_AstVariableDeclarationNode:
		return newVariableDeclarationNode(v.AstVariableDeclarationNode)
	case *generated.AnyASTScriptStatementProto_AstBreakContinueStatementNode:
		return wrapBreakContinueStatement(v.AstBreakContinueStatementNode)
	case *generated.AnyASTScriptStatementProto_AstReturnStatementNode:
		return newReturnStatementNode(v.AstReturnStatementNode)
	case *generated.AnyASTScriptStatementProto_AstSingleAssignmentNode:
		return newSingleAssignmentNode(v.AstSingleAssignmentNode)
	case *generated.AnyASTScriptStatementProto_AstAssignmentFromStructNode:
		return newAssignmentFromStructNode(v.AstAssignmentFromStructNode)
	case *generated.AnyASTScriptStatementProto_AstLoopStatementNode:
		return wrapLoopStatement(v.AstLoopStatementNode)
	}
	return nil
}

func wrapScriptStatementSlice(ps []*generated.AnyASTScriptStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapScriptStatement(p)
	}
	return nodes
}

func wrapStatement(p *generated.AnyASTStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTStatementProto_AstQueryStatementNode:
		return newQueryStatementNode(v.AstQueryStatementNode)
	case *generated.AnyASTStatementProto_AstScriptStatementNode:
		return wrapScriptStatement(v.AstScriptStatementNode)
	case *generated.AnyASTStatementProto_AstHintedStatementNode:
		return newHintedStatementNode(v.AstHintedStatementNode)
	case *generated.AnyASTStatementProto_AstExplainStatementNode:
		return newExplainStatementNode(v.AstExplainStatementNode)
	case *generated.AnyASTStatementProto_AstDescribeStatementNode:
		return newDescribeStatementNode(v.AstDescribeStatementNode)
	case *generated.AnyASTStatementProto_AstShowStatementNode:
		return newShowStatementNode(v.AstShowStatementNode)
	case *generated.AnyASTStatementProto_AstBeginStatementNode:
		return newBeginStatementNode(v.AstBeginStatementNode)
	case *generated.AnyASTStatementProto_AstSetTransactionStatementNode:
		return newSetTransactionStatementNode(v.AstSetTransactionStatementNode)
	case *generated.AnyASTStatementProto_AstCommitStatementNode:
		return newCommitStatementNode(v.AstCommitStatementNode)
	case *generated.AnyASTStatementProto_AstRollbackStatementNode:
		return newRollbackStatementNode(v.AstRollbackStatementNode)
	case *generated.AnyASTStatementProto_AstStartBatchStatementNode:
		return newStartBatchStatementNode(v.AstStartBatchStatementNode)
	case *generated.AnyASTStatementProto_AstRunBatchStatementNode:
		return newRunBatchStatementNode(v.AstRunBatchStatementNode)
	case *generated.AnyASTStatementProto_AstAbortBatchStatementNode:
		return newAbortBatchStatementNode(v.AstAbortBatchStatementNode)
	case *generated.AnyASTStatementProto_AstDdlStatementNode:
		return wrapDdlStatement(v.AstDdlStatementNode)
	case *generated.AnyASTStatementProto_AstDropAllRowAccessPoliciesStatementNode:
		return newDropAllRowAccessPoliciesStatementNode(v.AstDropAllRowAccessPoliciesStatementNode)
	case *generated.AnyASTStatementProto_AstRenameStatementNode:
		return newRenameStatementNode(v.AstRenameStatementNode)
	case *generated.AnyASTStatementProto_AstImportStatementNode:
		return newImportStatementNode(v.AstImportStatementNode)
	case *generated.AnyASTStatementProto_AstModuleStatementNode:
		return newModuleStatementNode(v.AstModuleStatementNode)
	case *generated.AnyASTStatementProto_AstCloneDataStatementNode:
		return newCloneDataStatementNode(v.AstCloneDataStatementNode)
	case *generated.AnyASTStatementProto_AstCreateDatabaseStatementNode:
		return newCreateDatabaseStatementNode(v.AstCreateDatabaseStatementNode)
	case *generated.AnyASTStatementProto_AstExportDataStatementNode:
		return newExportDataStatementNode(v.AstExportDataStatementNode)
	case *generated.AnyASTStatementProto_AstExportModelStatementNode:
		return newExportModelStatementNode(v.AstExportModelStatementNode)
	case *generated.AnyASTStatementProto_AstCallStatementNode:
		return newCallStatementNode(v.AstCallStatementNode)
	case *generated.AnyASTStatementProto_AstDefineTableStatementNode:
		return newDefineTableStatementNode(v.AstDefineTableStatementNode)
	case *generated.AnyASTStatementProto_AstAnalyzeStatementNode:
		return newAnalyzeStatementNode(v.AstAnalyzeStatementNode)
	case *generated.AnyASTStatementProto_AstAssertStatementNode:
		return newAssertStatementNode(v.AstAssertStatementNode)
	case *generated.AnyASTStatementProto_AstDeleteStatementNode:
		return newDeleteStatementNode(v.AstDeleteStatementNode)
	case *generated.AnyASTStatementProto_AstInsertStatementNode:
		return newInsertStatementNode(v.AstInsertStatementNode)
	case *generated.AnyASTStatementProto_AstUpdateStatementNode:
		return newUpdateStatementNode(v.AstUpdateStatementNode)
	case *generated.AnyASTStatementProto_AstTruncateStatementNode:
		return newTruncateStatementNode(v.AstTruncateStatementNode)
	case *generated.AnyASTStatementProto_AstMergeStatementNode:
		return newMergeStatementNode(v.AstMergeStatementNode)
	case *generated.AnyASTStatementProto_AstGrantStatementNode:
		return newGrantStatementNode(v.AstGrantStatementNode)
	case *generated.AnyASTStatementProto_AstRevokeStatementNode:
		return newRevokeStatementNode(v.AstRevokeStatementNode)
	case *generated.AnyASTStatementProto_AstAlterAllRowAccessPoliciesStatementNode:
		return newAlterAllRowAccessPoliciesStatementNode(v.AstAlterAllRowAccessPoliciesStatementNode)
	case *generated.AnyASTStatementProto_AstParameterAssignmentNode:
		return newParameterAssignmentNode(v.AstParameterAssignmentNode)
	case *generated.AnyASTStatementProto_AstSystemVariableAssignmentNode:
		return newSystemVariableAssignmentNode(v.AstSystemVariableAssignmentNode)
	case *generated.AnyASTStatementProto_AstExecuteImmediateStatementNode:
		return newExecuteImmediateStatementNode(v.AstExecuteImmediateStatementNode)
	case *generated.AnyASTStatementProto_AstDefineMacroStatementNode:
		return newDefineMacroStatementNode(v.AstDefineMacroStatementNode)
	case *generated.AnyASTStatementProto_AstExportMetadataStatementNode:
		return newExportMetadataStatementNode(v.AstExportMetadataStatementNode)
	case *generated.AnyASTStatementProto_AstCreateLocalityGroupStatementNode:
		return newCreateLocalityGroupStatementNode(v.AstCreateLocalityGroupStatementNode)
	case *generated.AnyASTStatementProto_AstRunStatementNode:
		return newRunStatementNode(v.AstRunStatementNode)
	case *generated.AnyASTStatementProto_AstSubpipelineStatementNode:
		return newSubpipelineStatementNode(v.AstSubpipelineStatementNode)
	case *generated.AnyASTStatementProto_AstStatementWithPipeOperatorsNode:
		return newStatementWithPipeOperatorsNode(v.AstStatementWithPipeOperatorsNode)
	}
	return nil
}

func wrapStatementSlice(ps []*generated.AnyASTStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapStatement(p)
	}
	return nodes
}

func wrapTableConstraint(p *generated.AnyASTTableConstraintProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTTableConstraintProto_AstPrimaryKeyNode:
		return newPrimaryKeyNode(v.AstPrimaryKeyNode)
	case *generated.AnyASTTableConstraintProto_AstForeignKeyNode:
		return newForeignKeyNode(v.AstForeignKeyNode)
	case *generated.AnyASTTableConstraintProto_AstCheckConstraintNode:
		return newCheckConstraintNode(v.AstCheckConstraintNode)
	}
	return nil
}

func wrapTableConstraintSlice(ps []*generated.AnyASTTableConstraintProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapTableConstraint(p)
	}
	return nodes
}

func wrapTableDataSource(p *generated.AnyASTTableDataSourceProto) TableExpressionNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTTableDataSourceProto_AstCloneDataSourceNode:
		return newCloneDataSourceNode(v.AstCloneDataSourceNode)
	case *generated.AnyASTTableDataSourceProto_AstCopyDataSourceNode:
		return newCopyDataSourceNode(v.AstCopyDataSourceNode)
	}
	return nil
}

func wrapTableDataSourceSlice(ps []*generated.AnyASTTableDataSourceProto) []TableExpressionNode {
	if ps == nil {
		return nil
	}
	nodes := make([]TableExpressionNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapTableDataSource(p)
	}
	return nodes
}

func wrapTableElement(p *generated.AnyASTTableElementProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTTableElementProto_AstColumnDefinitionNode:
		return newColumnDefinitionNode(v.AstColumnDefinitionNode)
	case *generated.AnyASTTableElementProto_AstTableConstraintNode:
		return wrapTableConstraint(v.AstTableConstraintNode)
	}
	return nil
}

func wrapTableElementSlice(ps []*generated.AnyASTTableElementProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapTableElement(p)
	}
	return nodes
}

func wrapTableExpression(p *generated.AnyASTTableExpressionProto) TableExpressionNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTTableExpressionProto_AstTablePathExpressionNode:
		return newTablePathExpressionNode(v.AstTablePathExpressionNode)
	case *generated.AnyASTTableExpressionProto_AstJoinNode:
		return newJoinNode(v.AstJoinNode)
	case *generated.AnyASTTableExpressionProto_AstParenthesizedJoinNode:
		return newParenthesizedJoinNode(v.AstParenthesizedJoinNode)
	case *generated.AnyASTTableExpressionProto_AstTableSubqueryNode:
		return newTableSubqueryNode(v.AstTableSubqueryNode)
	case *generated.AnyASTTableExpressionProto_AstTvfNode:
		return newTVFNode(v.AstTvfNode)
	case *generated.AnyASTTableExpressionProto_AstTableDataSourceNode:
		return wrapTableDataSource(v.AstTableDataSourceNode)
	case *generated.AnyASTTableExpressionProto_AstGraphTableQueryNode:
		return newGraphTableQueryNode(v.AstGraphTableQueryNode)
	case *generated.AnyASTTableExpressionProto_AstPipeJoinLhsPlaceholderNode:
		return newPipeJoinLhsPlaceholderNode(v.AstPipeJoinLhsPlaceholderNode)
	}
	return nil
}

func wrapTableExpressionSlice(ps []*generated.AnyASTTableExpressionProto) []TableExpressionNode {
	if ps == nil {
		return nil
	}
	nodes := make([]TableExpressionNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapTableExpression(p)
	}
	return nodes
}

func wrapTransactionMode(p *generated.AnyASTTransactionModeProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTTransactionModeProto_AstTransactionIsolationLevelNode:
		return newTransactionIsolationLevelNode(v.AstTransactionIsolationLevelNode)
	case *generated.AnyASTTransactionModeProto_AstTransactionReadWriteModeNode:
		return newTransactionReadWriteModeNode(v.AstTransactionReadWriteModeNode)
	}
	return nil
}

func wrapTransactionModeSlice(ps []*generated.AnyASTTransactionModeProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapTransactionMode(p)
	}
	return nodes
}

func wrapType(p *generated.AnyASTTypeProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyASTTypeProto_AstSimpleTypeNode:
		return newSimpleTypeNode(v.AstSimpleTypeNode)
	case *generated.AnyASTTypeProto_AstArrayTypeNode:
		return newArrayTypeNode(v.AstArrayTypeNode)
	case *generated.AnyASTTypeProto_AstStructTypeNode:
		return newStructTypeNode(v.AstStructTypeNode)
	case *generated.AnyASTTypeProto_AstRangeTypeNode:
		return newRangeTypeNode(v.AstRangeTypeNode)
	case *generated.AnyASTTypeProto_AstFunctionTypeNode:
		return newFunctionTypeNode(v.AstFunctionTypeNode)
	case *generated.AnyASTTypeProto_AstMapTypeNode:
		return newMapTypeNode(v.AstMapTypeNode)
	}
	return nil
}

func wrapTypeSlice(ps []*generated.AnyASTTypeProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapType(p)
	}
	return nodes
}
