package resolved_ast

import "github.com/glassmonkey/zetasql-wasm/wasm/generated"

// This file declares fork-friendly named types for the resolved-AST proto
// enums most commonly inspected when walking analysis output. Each named
// type wraps the underlying proto enum (int32) so accessors and constants
// are typed in this package's namespace, and downstream code does not need
// to import wasm/generated to recognise enum values.
//
// The accessors generated by resolved_astgen return these named types
// directly when the underlying proto enum appears in the wrapEnums map
// (see wasm/tools/resolved_astgen/main.go).

// JoinType describes the join kind on a JoinScanNode.
type JoinType int32

const (
	JoinTypeInner JoinType = JoinType(generated.ResolvedJoinScanEnums_INNER)
	JoinTypeLeft  JoinType = JoinType(generated.ResolvedJoinScanEnums_LEFT)
	JoinTypeRight JoinType = JoinType(generated.ResolvedJoinScanEnums_RIGHT)
	JoinTypeFull  JoinType = JoinType(generated.ResolvedJoinScanEnums_FULL)
)

func (t JoinType) String() string {
	return generated.ResolvedJoinScanEnums_JoinType(t).String()
}

// FrameUnit describes the unit (ROWS / RANGE) of a window frame.
type FrameUnit int32

const (
	FrameUnitRows  FrameUnit = FrameUnit(generated.ResolvedWindowFrameEnums_ROWS)
	FrameUnitRange FrameUnit = FrameUnit(generated.ResolvedWindowFrameEnums_RANGE)
)

func (u FrameUnit) String() string {
	return generated.ResolvedWindowFrameEnums_FrameUnit(u).String()
}

// CreateMode describes the conflict-handling mode of a CREATE statement.
type CreateMode int32

const (
	CreateDefaultMode     CreateMode = CreateMode(generated.ResolvedCreateStatementEnums_CREATE_DEFAULT)
	CreateOrReplaceMode   CreateMode = CreateMode(generated.ResolvedCreateStatementEnums_CREATE_OR_REPLACE)
	CreateIfNotExistsMode CreateMode = CreateMode(generated.ResolvedCreateStatementEnums_CREATE_IF_NOT_EXISTS)
)

func (m CreateMode) String() string {
	return generated.ResolvedCreateStatementEnums_CreateMode(m).String()
}

// CreateScope describes the visibility scope (DEFAULT, PRIVATE, PUBLIC, TEMP).
type CreateScope int32

const (
	CreateDefaultScope CreateScope = CreateScope(generated.ResolvedCreateStatementEnums_CREATE_DEFAULT_SCOPE)
	CreatePrivateScope CreateScope = CreateScope(generated.ResolvedCreateStatementEnums_CREATE_PRIVATE)
	CreatePublicScope  CreateScope = CreateScope(generated.ResolvedCreateStatementEnums_CREATE_PUBLIC)
	CreateTempScope    CreateScope = CreateScope(generated.ResolvedCreateStatementEnums_CREATE_TEMP)
)

func (s CreateScope) String() string {
	return generated.ResolvedCreateStatementEnums_CreateScope(s).String()
}

// MatchType is the WHEN clause discriminator on a MERGE statement.
type MatchType int32

const (
	MatchTypeMatched            MatchType = MatchType(generated.ResolvedMergeWhenEnums_MATCHED)
	MatchTypeNotMatchedBySource MatchType = MatchType(generated.ResolvedMergeWhenEnums_NOT_MATCHED_BY_SOURCE)
	MatchTypeNotMatchedByTarget MatchType = MatchType(generated.ResolvedMergeWhenEnums_NOT_MATCHED_BY_TARGET)
)

func (t MatchType) String() string {
	return generated.ResolvedMergeWhenEnums_MatchType(t).String()
}

// ActionType is the action clause type on a MERGE statement (INSERT / UPDATE / DELETE).
type ActionType int32

const (
	ActionTypeInsert ActionType = ActionType(generated.ResolvedMergeWhenEnums_INSERT)
	ActionTypeUpdate ActionType = ActionType(generated.ResolvedMergeWhenEnums_UPDATE)
	ActionTypeDelete ActionType = ActionType(generated.ResolvedMergeWhenEnums_DELETE)
)

func (t ActionType) String() string {
	return generated.ResolvedMergeWhenEnums_ActionType(t).String()
}

// SubqueryType describes the role of a subquery expression.
type SubqueryType int32

const (
	SubqueryTypeScalar  SubqueryType = SubqueryType(generated.ResolvedSubqueryExprEnums_SCALAR)
	SubqueryTypeArray   SubqueryType = SubqueryType(generated.ResolvedSubqueryExprEnums_ARRAY)
	SubqueryTypeExists  SubqueryType = SubqueryType(generated.ResolvedSubqueryExprEnums_EXISTS)
	SubqueryTypeIn      SubqueryType = SubqueryType(generated.ResolvedSubqueryExprEnums_IN)
	SubqueryTypeLikeAny SubqueryType = SubqueryType(generated.ResolvedSubqueryExprEnums_LIKE_ANY)
	SubqueryTypeLikeAll SubqueryType = SubqueryType(generated.ResolvedSubqueryExprEnums_LIKE_ALL)
)

func (t SubqueryType) String() string {
	return generated.ResolvedSubqueryExprEnums_SubqueryType(t).String()
}

// NullOrderMode describes NULL ordering on an ORDER BY item.
type NullOrderMode int32

const (
	NullOrderUnspecified    NullOrderMode = NullOrderMode(generated.ResolvedOrderByItemEnums_ORDER_UNSPECIFIED)
	NullOrderModeNullsFirst NullOrderMode = NullOrderMode(generated.ResolvedOrderByItemEnums_NULLS_FIRST)
	NullOrderModeNullsLast  NullOrderMode = NullOrderMode(generated.ResolvedOrderByItemEnums_NULLS_LAST)
)

func (m NullOrderMode) String() string {
	return generated.ResolvedOrderByItemEnums_NullOrderMode(m).String()
}

// SetOperationType describes the set-operation kind on a SetOperationScan.
type SetOperationType int32

const (
	SetOperationTypeUnionAll          SetOperationType = SetOperationType(generated.ResolvedSetOperationScanEnums_UNION_ALL)
	SetOperationTypeUnionDistinct     SetOperationType = SetOperationType(generated.ResolvedSetOperationScanEnums_UNION_DISTINCT)
	SetOperationTypeIntersectAll      SetOperationType = SetOperationType(generated.ResolvedSetOperationScanEnums_INTERSECT_ALL)
	SetOperationTypeIntersectDistinct SetOperationType = SetOperationType(generated.ResolvedSetOperationScanEnums_INTERSECT_DISTINCT)
	SetOperationTypeExceptAll         SetOperationType = SetOperationType(generated.ResolvedSetOperationScanEnums_EXCEPT_ALL)
	SetOperationTypeExceptDistinct    SetOperationType = SetOperationType(generated.ResolvedSetOperationScanEnums_EXCEPT_DISTINCT)
)

func (t SetOperationType) String() string {
	return generated.ResolvedSetOperationScanEnums_SetOperationType(t).String()
}

// BoundaryType describes the start / end of a window frame expression.
type BoundaryType int32

const (
	UnboundedPrecedingType BoundaryType = BoundaryType(generated.ResolvedWindowFrameExprEnums_UNBOUNDED_PRECEDING)
	OffsetPrecedingType    BoundaryType = BoundaryType(generated.ResolvedWindowFrameExprEnums_OFFSET_PRECEDING)
	CurrentRowType         BoundaryType = BoundaryType(generated.ResolvedWindowFrameExprEnums_CURRENT_ROW)
	OffsetFollowingType    BoundaryType = BoundaryType(generated.ResolvedWindowFrameExprEnums_OFFSET_FOLLOWING)
	UnboundedFollowingType BoundaryType = BoundaryType(generated.ResolvedWindowFrameExprEnums_UNBOUNDED_FOLLOWING)
)

func (t BoundaryType) String() string {
	return generated.ResolvedWindowFrameExprEnums_BoundaryType(t).String()
}

// NullHandlingModifier describes IGNORE / RESPECT NULLS on aggregate or
// analytic function calls.
type NullHandlingModifier int32

const (
	DefaultNullHandling NullHandlingModifier = NullHandlingModifier(generated.ResolvedNonScalarFunctionCallBaseEnums_DEFAULT_NULL_HANDLING)
	IgnoreNulls         NullHandlingModifier = NullHandlingModifier(generated.ResolvedNonScalarFunctionCallBaseEnums_IGNORE_NULLS)
	RespectNulls        NullHandlingModifier = NullHandlingModifier(generated.ResolvedNonScalarFunctionCallBaseEnums_RESPECT_NULLS)
)

func (m NullHandlingModifier) String() string {
	return generated.ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier(m).String()
}

// ErrorMode describes whether a function call should fail or return NULL on
// runtime errors.
type ErrorMode int32

const (
	DefaultErrorMode ErrorMode = ErrorMode(generated.ResolvedFunctionCallBaseEnums_DEFAULT_ERROR_MODE)
	SafeErrorMode    ErrorMode = ErrorMode(generated.ResolvedFunctionCallBaseEnums_SAFE_ERROR_MODE)
)

func (m ErrorMode) String() string {
	return generated.ResolvedFunctionCallBaseEnums_ErrorMode(m).String()
}
