// Code generated by resolved_astgen. DO NOT EDIT.

package resolved_ast

// Kind represents the type of a resolved AST node.
type Kind int

const (
	KindAbortBatchStmt                      Kind = 0
	KindAddColumnAction                     Kind = 1
	KindAddColumnIdentifierAction           Kind = 2
	KindAddConstraintAction                 Kind = 3
	KindAddSubEntityAction                  Kind = 4
	KindAddToRestricteeListAction           Kind = 5
	KindAggregateFunctionCall               Kind = 6
	KindAggregateHavingModifier             Kind = 7
	KindAggregateScan                       Kind = 8
	KindAggregationThresholdAggregateScan   Kind = 9
	KindAlterAllRowAccessPoliciesStmt       Kind = 10
	KindAlterApproxViewStmt                 Kind = 11
	KindAlterColumnDropDefaultAction        Kind = 12
	KindAlterColumnDropGeneratedAction      Kind = 13
	KindAlterColumnDropNotNullAction        Kind = 14
	KindAlterColumnOptionsAction            Kind = 15
	KindAlterColumnSetDataTypeAction        Kind = 16
	KindAlterColumnSetDefaultAction         Kind = 17
	KindAlterColumnSetGeneratedAction       Kind = 18
	KindAlterConnectionStmt                 Kind = 19
	KindAlterDatabaseStmt                   Kind = 20
	KindAlterEntityStmt                     Kind = 21
	KindAlterExternalSchemaStmt             Kind = 22
	KindAlterIndexStmt                      Kind = 23
	KindAlterMaterializedViewStmt           Kind = 24
	KindAlterModelStmt                      Kind = 25
	KindAlterPrivilegeRestrictionStmt       Kind = 26
	KindAlterRowAccessPolicyStmt            Kind = 27
	KindAlterSchemaStmt                     Kind = 28
	KindAlterSequenceStmt                   Kind = 29
	KindAlterSubEntityAction                Kind = 30
	KindAlterTableSetOptionsStmt            Kind = 31
	KindAlterTableStmt                      Kind = 32
	KindAlterViewStmt                       Kind = 33
	KindAnalyticFunctionCall                Kind = 34
	KindAnalyticFunctionGroup               Kind = 35
	KindAnalyticScan                        Kind = 36
	KindAnalyzeStmt                         Kind = 37
	KindAnonymizedAggregateScan             Kind = 38
	KindArgumentDef                         Kind = 39
	KindArgumentList                        Kind = 40
	KindArgumentRef                         Kind = 41
	KindArrayAggregate                      Kind = 42
	KindArrayScan                           Kind = 43
	KindAssertRowsModified                  Kind = 44
	KindAssertScan                          Kind = 45
	KindAssertStmt                          Kind = 46
	KindAssignmentStmt                      Kind = 47
	KindAuxLoadDataPartitionFilter          Kind = 48
	KindAuxLoadDataStmt                     Kind = 49
	KindBarrierScan                         Kind = 50
	KindBeginStmt                           Kind = 51
	KindCallStmt                            Kind = 52
	KindCast                                Kind = 53
	KindCatalogColumnRef                    Kind = 54
	KindCheckConstraint                     Kind = 55
	KindCloneDataStmt                       Kind = 56
	KindColumnAnnotations                   Kind = 57
	KindColumnDefaultValue                  Kind = 58
	KindColumnDefinition                    Kind = 59
	KindColumnHolder                        Kind = 60
	KindColumnRef                           Kind = 61
	KindCommitStmt                          Kind = 62
	KindComputedColumn                      Kind = 63
	KindConnection                          Kind = 64
	KindConstant                            Kind = 65
	KindCreateApproxViewStmt                Kind = 66
	KindCreateConnectionStmt                Kind = 67
	KindCreateConstantStmt                  Kind = 68
	KindCreateDatabaseStmt                  Kind = 69
	KindCreateEntityStmt                    Kind = 70
	KindCreateExternalSchemaStmt            Kind = 71
	KindCreateExternalTableStmt             Kind = 72
	KindCreateFunctionStmt                  Kind = 73
	KindCreateIndexStmt                     Kind = 74
	KindCreateMaterializedViewStmt          Kind = 75
	KindCreateModelAliasedQuery             Kind = 76
	KindCreateModelStmt                     Kind = 77
	KindCreatePrivilegeRestrictionStmt      Kind = 78
	KindCreateProcedureStmt                 Kind = 79
	KindCreatePropertyGraphStmt             Kind = 80
	KindCreateRowAccessPolicyStmt           Kind = 81
	KindCreateSchemaStmt                    Kind = 82
	KindCreateSequenceStmt                  Kind = 83
	KindCreateSnapshotTableStmt             Kind = 84
	KindCreateTableAsSelectStmt             Kind = 85
	KindCreateTableFunctionStmt             Kind = 86
	KindCreateTableStmt                     Kind = 87
	KindCreateViewStmt                      Kind = 88
	KindCreateWithEntryStmt                 Kind = 89
	KindCube                                Kind = 90
	KindDMLDefault                          Kind = 91
	KindDMLValue                            Kind = 92
	KindDeferredComputedColumn              Kind = 93
	KindDefineTableStmt                     Kind = 94
	KindDeleteStmt                          Kind = 95
	KindDescribeScan                        Kind = 96
	KindDescribeStmt                        Kind = 97
	KindDescriptor                          Kind = 98
	KindDifferentialPrivacyAggregateScan    Kind = 99
	KindDropColumnAction                    Kind = 100
	KindDropConstraintAction                Kind = 101
	KindDropFunctionStmt                    Kind = 102
	KindDropIndexStmt                       Kind = 103
	KindDropMaterializedViewStmt            Kind = 104
	KindDropPrimaryKeyAction                Kind = 105
	KindDropPrivilegeRestrictionStmt        Kind = 106
	KindDropRowAccessPolicyStmt             Kind = 107
	KindDropSnapshotTableStmt               Kind = 108
	KindDropStmt                            Kind = 109
	KindDropSubEntityAction                 Kind = 110
	KindDropTableFunctionStmt               Kind = 111
	KindExecuteAsRoleScan                   Kind = 112
	KindExecuteImmediateArgument            Kind = 113
	KindExecuteImmediateStmt                Kind = 114
	KindExplainStmt                         Kind = 115
	KindExportDataStmt                      Kind = 116
	KindExportMetadataStmt                  Kind = 117
	KindExportModelStmt                     Kind = 118
	KindExpressionColumn                    Kind = 119
	KindExtendedCastElement                 Kind = 120
	KindExtendedCast                        Kind = 121
	KindFilterFieldArg                      Kind = 122
	KindFilterField                         Kind = 123
	KindFilterScan                          Kind = 124
	KindFilterUsingAction                   Kind = 125
	KindFlatten                             Kind = 126
	KindFlattenedArg                        Kind = 127
	KindForeignKey                          Kind = 128
	KindFunctionArgument                    Kind = 129
	KindFunctionCall                        Kind = 130
	KindFunctionSignatureHolder             Kind = 131
	KindGeneralizedQueryStmt                Kind = 132
	KindGeneralizedQuerySubpipeline         Kind = 133
	KindGeneratedColumnInfo                 Kind = 134
	KindGetJsonField                        Kind = 135
	KindGetProtoField                       Kind = 136
	KindGetProtoOneof                       Kind = 137
	KindGetRowField                         Kind = 138
	KindGetStructField                      Kind = 139
	KindGrantStmt                           Kind = 140
	KindGrantToAction                       Kind = 141
	KindGraphCallScan                       Kind = 142
	KindGraphDynamicLabelSpecification      Kind = 143
	KindGraphDynamicPropertiesSpecification Kind = 144
	KindGraphEdgeScan                       Kind = 145
	KindGraphElementIdentifier              Kind = 146
	KindGraphElementLabel                   Kind = 147
	KindGraphElementProperty                Kind = 148
	KindGraphElementTable                   Kind = 149
	KindGraphGetElementProperty             Kind = 150
	KindGraphIsLabeledPredicate             Kind = 151
	KindGraphLabelNaryExpr                  Kind = 152
	KindGraphLabel                          Kind = 153
	KindGraphLinearScan                     Kind = 154
	KindGraphMakeArrayVariable              Kind = 155
	KindGraphMakeElement                    Kind = 156
	KindGraphNodeScan                       Kind = 157
	KindGraphNodeTableReference             Kind = 158
	KindGraphPathCost                       Kind = 159
	KindGraphPathMode                       Kind = 160
	KindGraphPathPatternQuantifier          Kind = 161
	KindGraphPathScan                       Kind = 162
	KindGraphPathSearchPrefix               Kind = 163
	KindGraphPropertyDeclaration            Kind = 164
	KindGraphPropertyDefinition             Kind = 165
	KindGraphRefScan                        Kind = 166
	KindGraphScan                           Kind = 167
	KindGraphTableScan                      Kind = 168
	KindGraphWildCardLabel                  Kind = 169
	KindGroupRowsScan                       Kind = 170
	KindGroupingCall                        Kind = 171
	KindGroupingSetList                     Kind = 172
	KindGroupingSetMultiColumn              Kind = 173
	KindGroupingSet                         Kind = 174
	KindGroupingSetProduct                  Kind = 175
	KindIdentityColumnInfo                  Kind = 176
	KindImportStmt                          Kind = 177
	KindIndexItem                           Kind = 178
	KindInlineLambda                        Kind = 179
	KindInsertRow                           Kind = 180
	KindInsertStmt                          Kind = 181
	KindJoinScan                            Kind = 182
	KindLimitOffsetScan                     Kind = 183
	KindLiteral                             Kind = 184
	KindLockMode                            Kind = 185
	KindLogScan                             Kind = 186
	KindMakeProtoField                      Kind = 187
	KindMakeProto                           Kind = 188
	KindMakeStruct                          Kind = 189
	KindMatchRecognizePatternAnchor         Kind = 190
	KindMatchRecognizePatternEmpty          Kind = 191
	KindMatchRecognizePatternOperation      Kind = 192
	KindMatchRecognizePatternQuantification Kind = 193
	KindMatchRecognizePatternVariableRef    Kind = 194
	KindMatchRecognizeScan                  Kind = 195
	KindMatchRecognizeVariableDefinition    Kind = 196
	KindMeasureGroup                        Kind = 197
	KindMergeStmt                           Kind = 198
	KindMergeWhen                           Kind = 199
	KindModel                               Kind = 200
	KindModuleStmt                          Kind = 201
	KindMultiStmt                           Kind = 202
	KindObjectUnit                          Kind = 203
	KindOnConflictClause                    Kind = 204
	KindOption                              Kind = 205
	KindOrderByItem                         Kind = 206
	KindOrderByScan                         Kind = 207
	KindOutputColumn                        Kind = 208
	KindOutputSchema                        Kind = 209
	KindParameter                           Kind = 210
	KindPipeCreateTableScan                 Kind = 211
	KindPipeExportDataScan                  Kind = 212
	KindPipeForkScan                        Kind = 213
	KindPipeIfCase                          Kind = 214
	KindPipeIfScan                          Kind = 215
	KindPipeInsertScan                      Kind = 216
	KindPipeTeeScan                         Kind = 217
	KindPivotColumn                         Kind = 218
	KindPivotScan                           Kind = 219
	KindPrimaryKey                          Kind = 220
	KindPrivilege                           Kind = 221
	KindProjectScan                         Kind = 222
	KindQueryStmt                           Kind = 223
	KindRebuildAction                       Kind = 224
	KindRecursionDepthModifier              Kind = 225
	KindRecursiveRefScan                    Kind = 226
	KindRecursiveScan                       Kind = 227
	KindRelationArgumentScan                Kind = 228
	KindRemoveFromRestricteeListAction      Kind = 229
	KindRenameColumnAction                  Kind = 230
	KindRenameStmt                          Kind = 231
	KindRenameToAction                      Kind = 232
	KindReplaceFieldItem                    Kind = 233
	KindReplaceField                        Kind = 234
	KindRestrictToAction                    Kind = 235
	KindReturningClause                     Kind = 236
	KindRevokeFromAction                    Kind = 237
	KindRevokeStmt                          Kind = 238
	KindRollbackStmt                        Kind = 239
	KindRollup                              Kind = 240
	KindRunBatchStmt                        Kind = 241
	KindSampleScan                          Kind = 242
	KindSequence                            Kind = 243
	KindSetAsAction                         Kind = 244
	KindSetCollateClause                    Kind = 245
	KindSetOperationItem                    Kind = 246
	KindSetOperationScan                    Kind = 247
	KindSetOptionsAction                    Kind = 248
	KindSetTransactionStmt                  Kind = 249
	KindShowStmt                            Kind = 250
	KindSingleRowScan                       Kind = 251
	KindStartBatchStmt                      Kind = 252
	KindStatementWithPipeOperatorsStmt      Kind = 253
	KindStaticDescribeScan                  Kind = 254
	KindSubpipelineInputScan                Kind = 255
	KindSubpipeline                         Kind = 256
	KindSubpipelineStmt                     Kind = 257
	KindSubqueryExpr                        Kind = 258
	KindSystemVariable                      Kind = 259
	KindTVFScan                             Kind = 260
	KindTableAndColumnInfo                  Kind = 261
	KindTableScan                           Kind = 262
	KindTruncateStmt                        Kind = 263
	KindUndropStmt                          Kind = 264
	KindUnnestItem                          Kind = 265
	KindUnpivotArg                          Kind = 266
	KindUnpivotScan                         Kind = 267
	KindUnsetArgumentScan                   Kind = 268
	KindUpdateConstructor                   Kind = 269
	KindUpdateFieldItem                     Kind = 270
	KindUpdateItemElement                   Kind = 271
	KindUpdateItem                          Kind = 272
	KindUpdateStmt                          Kind = 273
	KindWindowFrameExpr                     Kind = 274
	KindWindowFrame                         Kind = 275
	KindWindowOrdering                      Kind = 276
	KindWindowPartitioning                  Kind = 277
	KindWithEntry                           Kind = 278
	KindWithExpr                            Kind = 279
	KindWithPartitionColumns                Kind = 280
	KindWithRefScan                         Kind = 281
	KindWithScan                            Kind = 282
)

var kindNames = [...]string{
	KindAbortBatchStmt:                      "KindAbortBatchStmt",
	KindAddColumnAction:                     "KindAddColumnAction",
	KindAddColumnIdentifierAction:           "KindAddColumnIdentifierAction",
	KindAddConstraintAction:                 "KindAddConstraintAction",
	KindAddSubEntityAction:                  "KindAddSubEntityAction",
	KindAddToRestricteeListAction:           "KindAddToRestricteeListAction",
	KindAggregateFunctionCall:               "KindAggregateFunctionCall",
	KindAggregateHavingModifier:             "KindAggregateHavingModifier",
	KindAggregateScan:                       "KindAggregateScan",
	KindAggregationThresholdAggregateScan:   "KindAggregationThresholdAggregateScan",
	KindAlterAllRowAccessPoliciesStmt:       "KindAlterAllRowAccessPoliciesStmt",
	KindAlterApproxViewStmt:                 "KindAlterApproxViewStmt",
	KindAlterColumnDropDefaultAction:        "KindAlterColumnDropDefaultAction",
	KindAlterColumnDropGeneratedAction:      "KindAlterColumnDropGeneratedAction",
	KindAlterColumnDropNotNullAction:        "KindAlterColumnDropNotNullAction",
	KindAlterColumnOptionsAction:            "KindAlterColumnOptionsAction",
	KindAlterColumnSetDataTypeAction:        "KindAlterColumnSetDataTypeAction",
	KindAlterColumnSetDefaultAction:         "KindAlterColumnSetDefaultAction",
	KindAlterColumnSetGeneratedAction:       "KindAlterColumnSetGeneratedAction",
	KindAlterConnectionStmt:                 "KindAlterConnectionStmt",
	KindAlterDatabaseStmt:                   "KindAlterDatabaseStmt",
	KindAlterEntityStmt:                     "KindAlterEntityStmt",
	KindAlterExternalSchemaStmt:             "KindAlterExternalSchemaStmt",
	KindAlterIndexStmt:                      "KindAlterIndexStmt",
	KindAlterMaterializedViewStmt:           "KindAlterMaterializedViewStmt",
	KindAlterModelStmt:                      "KindAlterModelStmt",
	KindAlterPrivilegeRestrictionStmt:       "KindAlterPrivilegeRestrictionStmt",
	KindAlterRowAccessPolicyStmt:            "KindAlterRowAccessPolicyStmt",
	KindAlterSchemaStmt:                     "KindAlterSchemaStmt",
	KindAlterSequenceStmt:                   "KindAlterSequenceStmt",
	KindAlterSubEntityAction:                "KindAlterSubEntityAction",
	KindAlterTableSetOptionsStmt:            "KindAlterTableSetOptionsStmt",
	KindAlterTableStmt:                      "KindAlterTableStmt",
	KindAlterViewStmt:                       "KindAlterViewStmt",
	KindAnalyticFunctionCall:                "KindAnalyticFunctionCall",
	KindAnalyticFunctionGroup:               "KindAnalyticFunctionGroup",
	KindAnalyticScan:                        "KindAnalyticScan",
	KindAnalyzeStmt:                         "KindAnalyzeStmt",
	KindAnonymizedAggregateScan:             "KindAnonymizedAggregateScan",
	KindArgumentDef:                         "KindArgumentDef",
	KindArgumentList:                        "KindArgumentList",
	KindArgumentRef:                         "KindArgumentRef",
	KindArrayAggregate:                      "KindArrayAggregate",
	KindArrayScan:                           "KindArrayScan",
	KindAssertRowsModified:                  "KindAssertRowsModified",
	KindAssertScan:                          "KindAssertScan",
	KindAssertStmt:                          "KindAssertStmt",
	KindAssignmentStmt:                      "KindAssignmentStmt",
	KindAuxLoadDataPartitionFilter:          "KindAuxLoadDataPartitionFilter",
	KindAuxLoadDataStmt:                     "KindAuxLoadDataStmt",
	KindBarrierScan:                         "KindBarrierScan",
	KindBeginStmt:                           "KindBeginStmt",
	KindCallStmt:                            "KindCallStmt",
	KindCast:                                "KindCast",
	KindCatalogColumnRef:                    "KindCatalogColumnRef",
	KindCheckConstraint:                     "KindCheckConstraint",
	KindCloneDataStmt:                       "KindCloneDataStmt",
	KindColumnAnnotations:                   "KindColumnAnnotations",
	KindColumnDefaultValue:                  "KindColumnDefaultValue",
	KindColumnDefinition:                    "KindColumnDefinition",
	KindColumnHolder:                        "KindColumnHolder",
	KindColumnRef:                           "KindColumnRef",
	KindCommitStmt:                          "KindCommitStmt",
	KindComputedColumn:                      "KindComputedColumn",
	KindConnection:                          "KindConnection",
	KindConstant:                            "KindConstant",
	KindCreateApproxViewStmt:                "KindCreateApproxViewStmt",
	KindCreateConnectionStmt:                "KindCreateConnectionStmt",
	KindCreateConstantStmt:                  "KindCreateConstantStmt",
	KindCreateDatabaseStmt:                  "KindCreateDatabaseStmt",
	KindCreateEntityStmt:                    "KindCreateEntityStmt",
	KindCreateExternalSchemaStmt:            "KindCreateExternalSchemaStmt",
	KindCreateExternalTableStmt:             "KindCreateExternalTableStmt",
	KindCreateFunctionStmt:                  "KindCreateFunctionStmt",
	KindCreateIndexStmt:                     "KindCreateIndexStmt",
	KindCreateMaterializedViewStmt:          "KindCreateMaterializedViewStmt",
	KindCreateModelAliasedQuery:             "KindCreateModelAliasedQuery",
	KindCreateModelStmt:                     "KindCreateModelStmt",
	KindCreatePrivilegeRestrictionStmt:      "KindCreatePrivilegeRestrictionStmt",
	KindCreateProcedureStmt:                 "KindCreateProcedureStmt",
	KindCreatePropertyGraphStmt:             "KindCreatePropertyGraphStmt",
	KindCreateRowAccessPolicyStmt:           "KindCreateRowAccessPolicyStmt",
	KindCreateSchemaStmt:                    "KindCreateSchemaStmt",
	KindCreateSequenceStmt:                  "KindCreateSequenceStmt",
	KindCreateSnapshotTableStmt:             "KindCreateSnapshotTableStmt",
	KindCreateTableAsSelectStmt:             "KindCreateTableAsSelectStmt",
	KindCreateTableFunctionStmt:             "KindCreateTableFunctionStmt",
	KindCreateTableStmt:                     "KindCreateTableStmt",
	KindCreateViewStmt:                      "KindCreateViewStmt",
	KindCreateWithEntryStmt:                 "KindCreateWithEntryStmt",
	KindCube:                                "KindCube",
	KindDMLDefault:                          "KindDMLDefault",
	KindDMLValue:                            "KindDMLValue",
	KindDeferredComputedColumn:              "KindDeferredComputedColumn",
	KindDefineTableStmt:                     "KindDefineTableStmt",
	KindDeleteStmt:                          "KindDeleteStmt",
	KindDescribeScan:                        "KindDescribeScan",
	KindDescribeStmt:                        "KindDescribeStmt",
	KindDescriptor:                          "KindDescriptor",
	KindDifferentialPrivacyAggregateScan:    "KindDifferentialPrivacyAggregateScan",
	KindDropColumnAction:                    "KindDropColumnAction",
	KindDropConstraintAction:                "KindDropConstraintAction",
	KindDropFunctionStmt:                    "KindDropFunctionStmt",
	KindDropIndexStmt:                       "KindDropIndexStmt",
	KindDropMaterializedViewStmt:            "KindDropMaterializedViewStmt",
	KindDropPrimaryKeyAction:                "KindDropPrimaryKeyAction",
	KindDropPrivilegeRestrictionStmt:        "KindDropPrivilegeRestrictionStmt",
	KindDropRowAccessPolicyStmt:             "KindDropRowAccessPolicyStmt",
	KindDropSnapshotTableStmt:               "KindDropSnapshotTableStmt",
	KindDropStmt:                            "KindDropStmt",
	KindDropSubEntityAction:                 "KindDropSubEntityAction",
	KindDropTableFunctionStmt:               "KindDropTableFunctionStmt",
	KindExecuteAsRoleScan:                   "KindExecuteAsRoleScan",
	KindExecuteImmediateArgument:            "KindExecuteImmediateArgument",
	KindExecuteImmediateStmt:                "KindExecuteImmediateStmt",
	KindExplainStmt:                         "KindExplainStmt",
	KindExportDataStmt:                      "KindExportDataStmt",
	KindExportMetadataStmt:                  "KindExportMetadataStmt",
	KindExportModelStmt:                     "KindExportModelStmt",
	KindExpressionColumn:                    "KindExpressionColumn",
	KindExtendedCastElement:                 "KindExtendedCastElement",
	KindExtendedCast:                        "KindExtendedCast",
	KindFilterFieldArg:                      "KindFilterFieldArg",
	KindFilterField:                         "KindFilterField",
	KindFilterScan:                          "KindFilterScan",
	KindFilterUsingAction:                   "KindFilterUsingAction",
	KindFlatten:                             "KindFlatten",
	KindFlattenedArg:                        "KindFlattenedArg",
	KindForeignKey:                          "KindForeignKey",
	KindFunctionArgument:                    "KindFunctionArgument",
	KindFunctionCall:                        "KindFunctionCall",
	KindFunctionSignatureHolder:             "KindFunctionSignatureHolder",
	KindGeneralizedQueryStmt:                "KindGeneralizedQueryStmt",
	KindGeneralizedQuerySubpipeline:         "KindGeneralizedQuerySubpipeline",
	KindGeneratedColumnInfo:                 "KindGeneratedColumnInfo",
	KindGetJsonField:                        "KindGetJsonField",
	KindGetProtoField:                       "KindGetProtoField",
	KindGetProtoOneof:                       "KindGetProtoOneof",
	KindGetRowField:                         "KindGetRowField",
	KindGetStructField:                      "KindGetStructField",
	KindGrantStmt:                           "KindGrantStmt",
	KindGrantToAction:                       "KindGrantToAction",
	KindGraphCallScan:                       "KindGraphCallScan",
	KindGraphDynamicLabelSpecification:      "KindGraphDynamicLabelSpecification",
	KindGraphDynamicPropertiesSpecification: "KindGraphDynamicPropertiesSpecification",
	KindGraphEdgeScan:                       "KindGraphEdgeScan",
	KindGraphElementIdentifier:              "KindGraphElementIdentifier",
	KindGraphElementLabel:                   "KindGraphElementLabel",
	KindGraphElementProperty:                "KindGraphElementProperty",
	KindGraphElementTable:                   "KindGraphElementTable",
	KindGraphGetElementProperty:             "KindGraphGetElementProperty",
	KindGraphIsLabeledPredicate:             "KindGraphIsLabeledPredicate",
	KindGraphLabelNaryExpr:                  "KindGraphLabelNaryExpr",
	KindGraphLabel:                          "KindGraphLabel",
	KindGraphLinearScan:                     "KindGraphLinearScan",
	KindGraphMakeArrayVariable:              "KindGraphMakeArrayVariable",
	KindGraphMakeElement:                    "KindGraphMakeElement",
	KindGraphNodeScan:                       "KindGraphNodeScan",
	KindGraphNodeTableReference:             "KindGraphNodeTableReference",
	KindGraphPathCost:                       "KindGraphPathCost",
	KindGraphPathMode:                       "KindGraphPathMode",
	KindGraphPathPatternQuantifier:          "KindGraphPathPatternQuantifier",
	KindGraphPathScan:                       "KindGraphPathScan",
	KindGraphPathSearchPrefix:               "KindGraphPathSearchPrefix",
	KindGraphPropertyDeclaration:            "KindGraphPropertyDeclaration",
	KindGraphPropertyDefinition:             "KindGraphPropertyDefinition",
	KindGraphRefScan:                        "KindGraphRefScan",
	KindGraphScan:                           "KindGraphScan",
	KindGraphTableScan:                      "KindGraphTableScan",
	KindGraphWildCardLabel:                  "KindGraphWildCardLabel",
	KindGroupRowsScan:                       "KindGroupRowsScan",
	KindGroupingCall:                        "KindGroupingCall",
	KindGroupingSetList:                     "KindGroupingSetList",
	KindGroupingSetMultiColumn:              "KindGroupingSetMultiColumn",
	KindGroupingSet:                         "KindGroupingSet",
	KindGroupingSetProduct:                  "KindGroupingSetProduct",
	KindIdentityColumnInfo:                  "KindIdentityColumnInfo",
	KindImportStmt:                          "KindImportStmt",
	KindIndexItem:                           "KindIndexItem",
	KindInlineLambda:                        "KindInlineLambda",
	KindInsertRow:                           "KindInsertRow",
	KindInsertStmt:                          "KindInsertStmt",
	KindJoinScan:                            "KindJoinScan",
	KindLimitOffsetScan:                     "KindLimitOffsetScan",
	KindLiteral:                             "KindLiteral",
	KindLockMode:                            "KindLockMode",
	KindLogScan:                             "KindLogScan",
	KindMakeProtoField:                      "KindMakeProtoField",
	KindMakeProto:                           "KindMakeProto",
	KindMakeStruct:                          "KindMakeStruct",
	KindMatchRecognizePatternAnchor:         "KindMatchRecognizePatternAnchor",
	KindMatchRecognizePatternEmpty:          "KindMatchRecognizePatternEmpty",
	KindMatchRecognizePatternOperation:      "KindMatchRecognizePatternOperation",
	KindMatchRecognizePatternQuantification: "KindMatchRecognizePatternQuantification",
	KindMatchRecognizePatternVariableRef:    "KindMatchRecognizePatternVariableRef",
	KindMatchRecognizeScan:                  "KindMatchRecognizeScan",
	KindMatchRecognizeVariableDefinition:    "KindMatchRecognizeVariableDefinition",
	KindMeasureGroup:                        "KindMeasureGroup",
	KindMergeStmt:                           "KindMergeStmt",
	KindMergeWhen:                           "KindMergeWhen",
	KindModel:                               "KindModel",
	KindModuleStmt:                          "KindModuleStmt",
	KindMultiStmt:                           "KindMultiStmt",
	KindObjectUnit:                          "KindObjectUnit",
	KindOnConflictClause:                    "KindOnConflictClause",
	KindOption:                              "KindOption",
	KindOrderByItem:                         "KindOrderByItem",
	KindOrderByScan:                         "KindOrderByScan",
	KindOutputColumn:                        "KindOutputColumn",
	KindOutputSchema:                        "KindOutputSchema",
	KindParameter:                           "KindParameter",
	KindPipeCreateTableScan:                 "KindPipeCreateTableScan",
	KindPipeExportDataScan:                  "KindPipeExportDataScan",
	KindPipeForkScan:                        "KindPipeForkScan",
	KindPipeIfCase:                          "KindPipeIfCase",
	KindPipeIfScan:                          "KindPipeIfScan",
	KindPipeInsertScan:                      "KindPipeInsertScan",
	KindPipeTeeScan:                         "KindPipeTeeScan",
	KindPivotColumn:                         "KindPivotColumn",
	KindPivotScan:                           "KindPivotScan",
	KindPrimaryKey:                          "KindPrimaryKey",
	KindPrivilege:                           "KindPrivilege",
	KindProjectScan:                         "KindProjectScan",
	KindQueryStmt:                           "KindQueryStmt",
	KindRebuildAction:                       "KindRebuildAction",
	KindRecursionDepthModifier:              "KindRecursionDepthModifier",
	KindRecursiveRefScan:                    "KindRecursiveRefScan",
	KindRecursiveScan:                       "KindRecursiveScan",
	KindRelationArgumentScan:                "KindRelationArgumentScan",
	KindRemoveFromRestricteeListAction:      "KindRemoveFromRestricteeListAction",
	KindRenameColumnAction:                  "KindRenameColumnAction",
	KindRenameStmt:                          "KindRenameStmt",
	KindRenameToAction:                      "KindRenameToAction",
	KindReplaceFieldItem:                    "KindReplaceFieldItem",
	KindReplaceField:                        "KindReplaceField",
	KindRestrictToAction:                    "KindRestrictToAction",
	KindReturningClause:                     "KindReturningClause",
	KindRevokeFromAction:                    "KindRevokeFromAction",
	KindRevokeStmt:                          "KindRevokeStmt",
	KindRollbackStmt:                        "KindRollbackStmt",
	KindRollup:                              "KindRollup",
	KindRunBatchStmt:                        "KindRunBatchStmt",
	KindSampleScan:                          "KindSampleScan",
	KindSequence:                            "KindSequence",
	KindSetAsAction:                         "KindSetAsAction",
	KindSetCollateClause:                    "KindSetCollateClause",
	KindSetOperationItem:                    "KindSetOperationItem",
	KindSetOperationScan:                    "KindSetOperationScan",
	KindSetOptionsAction:                    "KindSetOptionsAction",
	KindSetTransactionStmt:                  "KindSetTransactionStmt",
	KindShowStmt:                            "KindShowStmt",
	KindSingleRowScan:                       "KindSingleRowScan",
	KindStartBatchStmt:                      "KindStartBatchStmt",
	KindStatementWithPipeOperatorsStmt:      "KindStatementWithPipeOperatorsStmt",
	KindStaticDescribeScan:                  "KindStaticDescribeScan",
	KindSubpipelineInputScan:                "KindSubpipelineInputScan",
	KindSubpipeline:                         "KindSubpipeline",
	KindSubpipelineStmt:                     "KindSubpipelineStmt",
	KindSubqueryExpr:                        "KindSubqueryExpr",
	KindSystemVariable:                      "KindSystemVariable",
	KindTVFScan:                             "KindTVFScan",
	KindTableAndColumnInfo:                  "KindTableAndColumnInfo",
	KindTableScan:                           "KindTableScan",
	KindTruncateStmt:                        "KindTruncateStmt",
	KindUndropStmt:                          "KindUndropStmt",
	KindUnnestItem:                          "KindUnnestItem",
	KindUnpivotArg:                          "KindUnpivotArg",
	KindUnpivotScan:                         "KindUnpivotScan",
	KindUnsetArgumentScan:                   "KindUnsetArgumentScan",
	KindUpdateConstructor:                   "KindUpdateConstructor",
	KindUpdateFieldItem:                     "KindUpdateFieldItem",
	KindUpdateItemElement:                   "KindUpdateItemElement",
	KindUpdateItem:                          "KindUpdateItem",
	KindUpdateStmt:                          "KindUpdateStmt",
	KindWindowFrameExpr:                     "KindWindowFrameExpr",
	KindWindowFrame:                         "KindWindowFrame",
	KindWindowOrdering:                      "KindWindowOrdering",
	KindWindowPartitioning:                  "KindWindowPartitioning",
	KindWithEntry:                           "KindWithEntry",
	KindWithExpr:                            "KindWithExpr",
	KindWithPartitionColumns:                "KindWithPartitionColumns",
	KindWithRefScan:                         "KindWithRefScan",
	KindWithScan:                            "KindWithScan",
}

func (k Kind) String() string {
	if int(k) < len(kindNames) {
		return kindNames[k]
	}
	return "Unknown"
}
