// Code generated by resolved_astgen. DO NOT EDIT.

package resolved_ast

import (
	"github.com/glassmonkey/zetasql-wasm/wasm/generated"
)

func wrapAggregateScanBase(p *generated.AnyResolvedAggregateScanBaseProto) ScanNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedAggregateScanBaseProto_ResolvedAggregateScanNode:
		return newAggregateScanNode(v.ResolvedAggregateScanNode)
	case *generated.AnyResolvedAggregateScanBaseProto_ResolvedAnonymizedAggregateScanNode:
		return newAnonymizedAggregateScanNode(v.ResolvedAnonymizedAggregateScanNode)
	case *generated.AnyResolvedAggregateScanBaseProto_ResolvedDifferentialPrivacyAggregateScanNode:
		return newDifferentialPrivacyAggregateScanNode(v.ResolvedDifferentialPrivacyAggregateScanNode)
	case *generated.AnyResolvedAggregateScanBaseProto_ResolvedAggregationThresholdAggregateScanNode:
		return newAggregationThresholdAggregateScanNode(v.ResolvedAggregationThresholdAggregateScanNode)
	}
	return nil
}

func wrapAggregateScanBaseSlice(ps []*generated.AnyResolvedAggregateScanBaseProto) []ScanNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ScanNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapAggregateScanBase(p)
	}
	return nodes
}

func wrapAlterAction(p *generated.AnyResolvedAlterActionProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedAlterActionProto_ResolvedSetOptionsActionNode:
		return newSetOptionsActionNode(v.ResolvedSetOptionsActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAddColumnActionNode:
		return newAddColumnActionNode(v.ResolvedAddColumnActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedDropColumnActionNode:
		return newDropColumnActionNode(v.ResolvedDropColumnActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedGrantToActionNode:
		return newGrantToActionNode(v.ResolvedGrantToActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedFilterUsingActionNode:
		return newFilterUsingActionNode(v.ResolvedFilterUsingActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedRevokeFromActionNode:
		return newRevokeFromActionNode(v.ResolvedRevokeFromActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedRenameToActionNode:
		return newRenameToActionNode(v.ResolvedRenameToActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedSetAsActionNode:
		return newSetAsActionNode(v.ResolvedSetAsActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAddConstraintActionNode:
		return newAddConstraintActionNode(v.ResolvedAddConstraintActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedDropConstraintActionNode:
		return newDropConstraintActionNode(v.ResolvedDropConstraintActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedDropPrimaryKeyActionNode:
		return newDropPrimaryKeyActionNode(v.ResolvedDropPrimaryKeyActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedRenameColumnActionNode:
		return newRenameColumnActionNode(v.ResolvedRenameColumnActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedSetCollateClauseNode:
		return newSetCollateClauseNode(v.ResolvedSetCollateClauseNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedRestrictToActionNode:
		return newRestrictToActionNode(v.ResolvedRestrictToActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAddToRestricteeListActionNode:
		return newAddToRestricteeListActionNode(v.ResolvedAddToRestricteeListActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedRemoveFromRestricteeListActionNode:
		return newRemoveFromRestricteeListActionNode(v.ResolvedRemoveFromRestricteeListActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAlterColumnActionNode:
		return wrapAlterColumnAction(v.ResolvedAlterColumnActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAlterSubEntityActionNode:
		return newAlterSubEntityActionNode(v.ResolvedAlterSubEntityActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAddSubEntityActionNode:
		return newAddSubEntityActionNode(v.ResolvedAddSubEntityActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedDropSubEntityActionNode:
		return newDropSubEntityActionNode(v.ResolvedDropSubEntityActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedAddColumnIdentifierActionNode:
		return newAddColumnIdentifierActionNode(v.ResolvedAddColumnIdentifierActionNode)
	case *generated.AnyResolvedAlterActionProto_ResolvedRebuildActionNode:
		return newRebuildActionNode(v.ResolvedRebuildActionNode)
	}
	return nil
}

func wrapAlterActionSlice(ps []*generated.AnyResolvedAlterActionProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapAlterAction(p)
	}
	return nodes
}

func wrapAlterColumnAction(p *generated.AnyResolvedAlterColumnActionProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnOptionsActionNode:
		return newAlterColumnOptionsActionNode(v.ResolvedAlterColumnOptionsActionNode)
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnDropNotNullActionNode:
		return newAlterColumnDropNotNullActionNode(v.ResolvedAlterColumnDropNotNullActionNode)
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnSetDataTypeActionNode:
		return newAlterColumnSetDataTypeActionNode(v.ResolvedAlterColumnSetDataTypeActionNode)
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnSetDefaultActionNode:
		return newAlterColumnSetDefaultActionNode(v.ResolvedAlterColumnSetDefaultActionNode)
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnDropDefaultActionNode:
		return newAlterColumnDropDefaultActionNode(v.ResolvedAlterColumnDropDefaultActionNode)
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnDropGeneratedActionNode:
		return newAlterColumnDropGeneratedActionNode(v.ResolvedAlterColumnDropGeneratedActionNode)
	case *generated.AnyResolvedAlterColumnActionProto_ResolvedAlterColumnSetGeneratedActionNode:
		return newAlterColumnSetGeneratedActionNode(v.ResolvedAlterColumnSetGeneratedActionNode)
	}
	return nil
}

func wrapAlterColumnActionSlice(ps []*generated.AnyResolvedAlterColumnActionProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapAlterColumnAction(p)
	}
	return nodes
}

func wrapAlterObjectStmt(p *generated.AnyResolvedAlterObjectStmtProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterRowAccessPolicyStmtNode:
		return newAlterRowAccessPolicyStmtNode(v.ResolvedAlterRowAccessPolicyStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterTableStmtNode:
		return newAlterTableStmtNode(v.ResolvedAlterTableStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterViewStmtNode:
		return newAlterViewStmtNode(v.ResolvedAlterViewStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterMaterializedViewStmtNode:
		return newAlterMaterializedViewStmtNode(v.ResolvedAlterMaterializedViewStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterDatabaseStmtNode:
		return newAlterDatabaseStmtNode(v.ResolvedAlterDatabaseStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterAllRowAccessPoliciesStmtNode:
		return newAlterAllRowAccessPoliciesStmtNode(v.ResolvedAlterAllRowAccessPoliciesStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterEntityStmtNode:
		return newAlterEntityStmtNode(v.ResolvedAlterEntityStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterSchemaStmtNode:
		return newAlterSchemaStmtNode(v.ResolvedAlterSchemaStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterPrivilegeRestrictionStmtNode:
		return newAlterPrivilegeRestrictionStmtNode(v.ResolvedAlterPrivilegeRestrictionStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterModelStmtNode:
		return newAlterModelStmtNode(v.ResolvedAlterModelStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterApproxViewStmtNode:
		return newAlterApproxViewStmtNode(v.ResolvedAlterApproxViewStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterExternalSchemaStmtNode:
		return newAlterExternalSchemaStmtNode(v.ResolvedAlterExternalSchemaStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterConnectionStmtNode:
		return newAlterConnectionStmtNode(v.ResolvedAlterConnectionStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterIndexStmtNode:
		return newAlterIndexStmtNode(v.ResolvedAlterIndexStmtNode)
	case *generated.AnyResolvedAlterObjectStmtProto_ResolvedAlterSequenceStmtNode:
		return newAlterSequenceStmtNode(v.ResolvedAlterSequenceStmtNode)
	}
	return nil
}

func wrapAlterObjectStmtSlice(ps []*generated.AnyResolvedAlterObjectStmtProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapAlterObjectStmt(p)
	}
	return nodes
}

func wrapArgument(p *generated.AnyResolvedArgumentProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedArgumentProto_ResolvedMakeProtoFieldNode:
		return newMakeProtoFieldNode(v.ResolvedMakeProtoFieldNode)
	case *generated.AnyResolvedArgumentProto_ResolvedColumnHolderNode:
		return newColumnHolderNode(v.ResolvedColumnHolderNode)
	case *generated.AnyResolvedArgumentProto_ResolvedOrderByItemNode:
		return newOrderByItemNode(v.ResolvedOrderByItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedOutputColumnNode:
		return newOutputColumnNode(v.ResolvedOutputColumnNode)
	case *generated.AnyResolvedArgumentProto_ResolvedWithEntryNode:
		return newWithEntryNode(v.ResolvedWithEntryNode)
	case *generated.AnyResolvedArgumentProto_ResolvedOptionNode:
		return newOptionNode(v.ResolvedOptionNode)
	case *generated.AnyResolvedArgumentProto_ResolvedWindowPartitioningNode:
		return newWindowPartitioningNode(v.ResolvedWindowPartitioningNode)
	case *generated.AnyResolvedArgumentProto_ResolvedWindowOrderingNode:
		return newWindowOrderingNode(v.ResolvedWindowOrderingNode)
	case *generated.AnyResolvedArgumentProto_ResolvedWindowFrameNode:
		return newWindowFrameNode(v.ResolvedWindowFrameNode)
	case *generated.AnyResolvedArgumentProto_ResolvedAnalyticFunctionGroupNode:
		return newAnalyticFunctionGroupNode(v.ResolvedAnalyticFunctionGroupNode)
	case *generated.AnyResolvedArgumentProto_ResolvedWindowFrameExprNode:
		return newWindowFrameExprNode(v.ResolvedWindowFrameExprNode)
	case *generated.AnyResolvedArgumentProto_ResolvedDmlvalueNode:
		return newDMLValueNode(v.ResolvedDmlvalueNode)
	case *generated.AnyResolvedArgumentProto_ResolvedAssertRowsModifiedNode:
		return newAssertRowsModifiedNode(v.ResolvedAssertRowsModifiedNode)
	case *generated.AnyResolvedArgumentProto_ResolvedInsertRowNode:
		return newInsertRowNode(v.ResolvedInsertRowNode)
	case *generated.AnyResolvedArgumentProto_ResolvedUpdateItemNode:
		return newUpdateItemNode(v.ResolvedUpdateItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedPrivilegeNode:
		return newPrivilegeNode(v.ResolvedPrivilegeNode)
	case *generated.AnyResolvedArgumentProto_ResolvedArgumentDefNode:
		return newArgumentDefNode(v.ResolvedArgumentDefNode)
	case *generated.AnyResolvedArgumentProto_ResolvedArgumentListNode:
		return newArgumentListNode(v.ResolvedArgumentListNode)
	case *generated.AnyResolvedArgumentProto_ResolvedFunctionArgumentNode:
		return newFunctionArgumentNode(v.ResolvedFunctionArgumentNode)
	case *generated.AnyResolvedArgumentProto_ResolvedFunctionSignatureHolderNode:
		return newFunctionSignatureHolderNode(v.ResolvedFunctionSignatureHolderNode)
	case *generated.AnyResolvedArgumentProto_ResolvedAggregateHavingModifierNode:
		return newAggregateHavingModifierNode(v.ResolvedAggregateHavingModifierNode)
	case *generated.AnyResolvedArgumentProto_ResolvedColumnDefinitionNode:
		return newColumnDefinitionNode(v.ResolvedColumnDefinitionNode)
	case *generated.AnyResolvedArgumentProto_ResolvedSetOperationItemNode:
		return newSetOperationItemNode(v.ResolvedSetOperationItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedIndexItemNode:
		return newIndexItemNode(v.ResolvedIndexItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedMergeWhenNode:
		return newMergeWhenNode(v.ResolvedMergeWhenNode)
	case *generated.AnyResolvedArgumentProto_ResolvedUpdateItemElementNode:
		return newUpdateItemElementNode(v.ResolvedUpdateItemElementNode)
	case *generated.AnyResolvedArgumentProto_ResolvedColumnAnnotationsNode:
		return newColumnAnnotationsNode(v.ResolvedColumnAnnotationsNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGeneratedColumnInfoNode:
		return newGeneratedColumnInfoNode(v.ResolvedGeneratedColumnInfoNode)
	case *generated.AnyResolvedArgumentProto_ResolvedModelNode:
		return newModelNode(v.ResolvedModelNode)
	case *generated.AnyResolvedArgumentProto_ResolvedAlterActionNode:
		return wrapAlterAction(v.ResolvedAlterActionNode)
	case *generated.AnyResolvedArgumentProto_ResolvedUnnestItemNode:
		return newUnnestItemNode(v.ResolvedUnnestItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedReplaceFieldItemNode:
		return newReplaceFieldItemNode(v.ResolvedReplaceFieldItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedConnectionNode:
		return newConnectionNode(v.ResolvedConnectionNode)
	case *generated.AnyResolvedArgumentProto_ResolvedExecuteImmediateArgumentNode:
		return newExecuteImmediateArgumentNode(v.ResolvedExecuteImmediateArgumentNode)
	case *generated.AnyResolvedArgumentProto_ResolvedDescriptorNode:
		return newDescriptorNode(v.ResolvedDescriptorNode)
	case *generated.AnyResolvedArgumentProto_ResolvedExtendedCastElementNode:
		return newExtendedCastElementNode(v.ResolvedExtendedCastElementNode)
	case *generated.AnyResolvedArgumentProto_ResolvedWithPartitionColumnsNode:
		return newWithPartitionColumnsNode(v.ResolvedWithPartitionColumnsNode)
	case *generated.AnyResolvedArgumentProto_ResolvedExtendedCastNode:
		return newExtendedCastNode(v.ResolvedExtendedCastNode)
	case *generated.AnyResolvedArgumentProto_ResolvedInlineLambdaNode:
		return newInlineLambdaNode(v.ResolvedInlineLambdaNode)
	case *generated.AnyResolvedArgumentProto_ResolvedConstraintNode:
		return wrapConstraint(v.ResolvedConstraintNode)
	case *generated.AnyResolvedArgumentProto_ResolvedPivotColumnNode:
		return newPivotColumnNode(v.ResolvedPivotColumnNode)
	case *generated.AnyResolvedArgumentProto_ResolvedReturningClauseNode:
		return newReturningClauseNode(v.ResolvedReturningClauseNode)
	case *generated.AnyResolvedArgumentProto_ResolvedUnpivotArgNode:
		return newUnpivotArgNode(v.ResolvedUnpivotArgNode)
	case *generated.AnyResolvedArgumentProto_ResolvedFilterFieldArgNode:
		return newFilterFieldArgNode(v.ResolvedFilterFieldArgNode)
	case *generated.AnyResolvedArgumentProto_ResolvedTableAndColumnInfoNode:
		return newTableAndColumnInfoNode(v.ResolvedTableAndColumnInfoNode)
	case *generated.AnyResolvedArgumentProto_ResolvedColumnDefaultValueNode:
		return newColumnDefaultValueNode(v.ResolvedColumnDefaultValueNode)
	case *generated.AnyResolvedArgumentProto_ResolvedObjectUnitNode:
		return newObjectUnitNode(v.ResolvedObjectUnitNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphLabelExprNode:
		return wrapGraphLabelExpr(v.ResolvedGraphLabelExprNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphElementIdentifierNode:
		return newGraphElementIdentifierNode(v.ResolvedGraphElementIdentifierNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphElementPropertyNode:
		return newGraphElementPropertyNode(v.ResolvedGraphElementPropertyNode)
	case *generated.AnyResolvedArgumentProto_ResolvedAuxLoadDataPartitionFilterNode:
		return newAuxLoadDataPartitionFilterNode(v.ResolvedAuxLoadDataPartitionFilterNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphElementTableNode:
		return newGraphElementTableNode(v.ResolvedGraphElementTableNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphNodeTableReferenceNode:
		return newGraphNodeTableReferenceNode(v.ResolvedGraphNodeTableReferenceNode)
	case *generated.AnyResolvedArgumentProto_ResolvedCreateModelAliasedQueryNode:
		return newCreateModelAliasedQueryNode(v.ResolvedCreateModelAliasedQueryNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphElementLabelNode:
		return newGraphElementLabelNode(v.ResolvedGraphElementLabelNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphPropertyDeclarationNode:
		return newGraphPropertyDeclarationNode(v.ResolvedGraphPropertyDeclarationNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphPropertyDefinitionNode:
		return newGraphPropertyDefinitionNode(v.ResolvedGraphPropertyDefinitionNode)
	case *generated.AnyResolvedArgumentProto_ResolvedSequenceNode:
		return newSequenceNode(v.ResolvedSequenceNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGroupingSetMultiColumnNode:
		return newGroupingSetMultiColumnNode(v.ResolvedGroupingSetMultiColumnNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGroupingSetBaseNode:
		return wrapGroupingSetBase(v.ResolvedGroupingSetBaseNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGroupingCallNode:
		return newGroupingCallNode(v.ResolvedGroupingCallNode)
	case *generated.AnyResolvedArgumentProto_ResolvedIdentityColumnInfoNode:
		return newIdentityColumnInfoNode(v.ResolvedIdentityColumnInfoNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphPathPatternQuantifierNode:
		return newGraphPathPatternQuantifierNode(v.ResolvedGraphPathPatternQuantifierNode)
	case *generated.AnyResolvedArgumentProto_ResolvedComputedColumnBaseNode:
		return wrapComputedColumnBase(v.ResolvedComputedColumnBaseNode)
	case *generated.AnyResolvedArgumentProto_ResolvedRecursionDepthModifierNode:
		return newRecursionDepthModifierNode(v.ResolvedRecursionDepthModifierNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphMakeArrayVariableNode:
		return newGraphMakeArrayVariableNode(v.ResolvedGraphMakeArrayVariableNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphPathModeNode:
		return newGraphPathModeNode(v.ResolvedGraphPathModeNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphPathSearchPrefixNode:
		return newGraphPathSearchPrefixNode(v.ResolvedGraphPathSearchPrefixNode)
	case *generated.AnyResolvedArgumentProto_ResolvedMatchRecognizeVariableDefinitionNode:
		return newMatchRecognizeVariableDefinitionNode(v.ResolvedMatchRecognizeVariableDefinitionNode)
	case *generated.AnyResolvedArgumentProto_ResolvedMatchRecognizePatternExprNode:
		return wrapMatchRecognizePatternExpr(v.ResolvedMatchRecognizePatternExprNode)
	case *generated.AnyResolvedArgumentProto_ResolvedSubpipelineNode:
		return newSubpipelineNode(v.ResolvedSubpipelineNode)
	case *generated.AnyResolvedArgumentProto_ResolvedLockModeNode:
		return newLockModeNode(v.ResolvedLockModeNode)
	case *generated.AnyResolvedArgumentProto_ResolvedPipeIfCaseNode:
		return newPipeIfCaseNode(v.ResolvedPipeIfCaseNode)
	case *generated.AnyResolvedArgumentProto_ResolvedOutputSchemaNode:
		return newOutputSchemaNode(v.ResolvedOutputSchemaNode)
	case *generated.AnyResolvedArgumentProto_ResolvedMeasureGroupNode:
		return newMeasureGroupNode(v.ResolvedMeasureGroupNode)
	case *generated.AnyResolvedArgumentProto_ResolvedOnConflictClauseNode:
		return newOnConflictClauseNode(v.ResolvedOnConflictClauseNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGeneralizedQuerySubpipelineNode:
		return newGeneralizedQuerySubpipelineNode(v.ResolvedGeneralizedQuerySubpipelineNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphDynamicLabelSpecificationNode:
		return newGraphDynamicLabelSpecificationNode(v.ResolvedGraphDynamicLabelSpecificationNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphDynamicPropertiesSpecificationNode:
		return newGraphDynamicPropertiesSpecificationNode(v.ResolvedGraphDynamicPropertiesSpecificationNode)
	case *generated.AnyResolvedArgumentProto_ResolvedUpdateFieldItemNode:
		return newUpdateFieldItemNode(v.ResolvedUpdateFieldItemNode)
	case *generated.AnyResolvedArgumentProto_ResolvedGraphPathCostNode:
		return newGraphPathCostNode(v.ResolvedGraphPathCostNode)
	}
	return nil
}

func wrapArgumentSlice(ps []*generated.AnyResolvedArgumentProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapArgument(p)
	}
	return nodes
}

func wrapComputedColumnBase(p *generated.AnyResolvedComputedColumnBaseProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedComputedColumnBaseProto_ResolvedComputedColumnImplNode:
		return wrapComputedColumnImpl(v.ResolvedComputedColumnImplNode)
	}
	return nil
}

func wrapComputedColumnBaseSlice(ps []*generated.AnyResolvedComputedColumnBaseProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapComputedColumnBase(p)
	}
	return nodes
}

func wrapComputedColumnImpl(p *generated.AnyResolvedComputedColumnImplProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedComputedColumnImplProto_ResolvedComputedColumnNode:
		return newComputedColumnNode(v.ResolvedComputedColumnNode)
	case *generated.AnyResolvedComputedColumnImplProto_ResolvedDeferredComputedColumnNode:
		return newDeferredComputedColumnNode(v.ResolvedDeferredComputedColumnNode)
	}
	return nil
}

func wrapComputedColumnImplSlice(ps []*generated.AnyResolvedComputedColumnImplProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapComputedColumnImpl(p)
	}
	return nodes
}

func wrapConstraint(p *generated.AnyResolvedConstraintProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedConstraintProto_ResolvedPrimaryKeyNode:
		return newPrimaryKeyNode(v.ResolvedPrimaryKeyNode)
	case *generated.AnyResolvedConstraintProto_ResolvedForeignKeyNode:
		return newForeignKeyNode(v.ResolvedForeignKeyNode)
	case *generated.AnyResolvedConstraintProto_ResolvedCheckConstraintNode:
		return newCheckConstraintNode(v.ResolvedCheckConstraintNode)
	}
	return nil
}

func wrapConstraintSlice(ps []*generated.AnyResolvedConstraintProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapConstraint(p)
	}
	return nodes
}

func wrapCreateSchemaStmtBase(p *generated.AnyResolvedCreateSchemaStmtBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedCreateSchemaStmtBaseProto_ResolvedCreateSchemaStmtNode:
		return newCreateSchemaStmtNode(v.ResolvedCreateSchemaStmtNode)
	case *generated.AnyResolvedCreateSchemaStmtBaseProto_ResolvedCreateExternalSchemaStmtNode:
		return newCreateExternalSchemaStmtNode(v.ResolvedCreateExternalSchemaStmtNode)
	}
	return nil
}

func wrapCreateSchemaStmtBaseSlice(ps []*generated.AnyResolvedCreateSchemaStmtBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateSchemaStmtBase(p)
	}
	return nodes
}

func wrapCreateStatement(p *generated.AnyResolvedCreateStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateFunctionStmtNode:
		return newCreateFunctionStmtNode(v.ResolvedCreateFunctionStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateTableFunctionStmtNode:
		return newCreateTableFunctionStmtNode(v.ResolvedCreateTableFunctionStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateIndexStmtNode:
		return newCreateIndexStmtNode(v.ResolvedCreateIndexStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateConstantStmtNode:
		return newCreateConstantStmtNode(v.ResolvedCreateConstantStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateTableStmtBaseNode:
		return wrapCreateTableStmtBase(v.ResolvedCreateTableStmtBaseNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateModelStmtNode:
		return newCreateModelStmtNode(v.ResolvedCreateModelStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateViewBaseNode:
		return wrapCreateViewBase(v.ResolvedCreateViewBaseNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateProcedureStmtNode:
		return newCreateProcedureStmtNode(v.ResolvedCreateProcedureStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateEntityStmtNode:
		return newCreateEntityStmtNode(v.ResolvedCreateEntityStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateSnapshotTableStmtNode:
		return newCreateSnapshotTableStmtNode(v.ResolvedCreateSnapshotTableStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreatePrivilegeRestrictionStmtNode:
		return newCreatePrivilegeRestrictionStmtNode(v.ResolvedCreatePrivilegeRestrictionStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreatePropertyGraphStmtNode:
		return newCreatePropertyGraphStmtNode(v.ResolvedCreatePropertyGraphStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateSchemaStmtBaseNode:
		return wrapCreateSchemaStmtBase(v.ResolvedCreateSchemaStmtBaseNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateConnectionStmtNode:
		return newCreateConnectionStmtNode(v.ResolvedCreateConnectionStmtNode)
	case *generated.AnyResolvedCreateStatementProto_ResolvedCreateSequenceStmtNode:
		return newCreateSequenceStmtNode(v.ResolvedCreateSequenceStmtNode)
	}
	return nil
}

func wrapCreateStatementSlice(ps []*generated.AnyResolvedCreateStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateStatement(p)
	}
	return nodes
}

func wrapCreateTableStmtBase(p *generated.AnyResolvedCreateTableStmtBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedCreateTableStmtBaseProto_ResolvedCreateTableAsSelectStmtNode:
		return newCreateTableAsSelectStmtNode(v.ResolvedCreateTableAsSelectStmtNode)
	case *generated.AnyResolvedCreateTableStmtBaseProto_ResolvedCreateExternalTableStmtNode:
		return newCreateExternalTableStmtNode(v.ResolvedCreateExternalTableStmtNode)
	case *generated.AnyResolvedCreateTableStmtBaseProto_ResolvedCreateTableStmtNode:
		return newCreateTableStmtNode(v.ResolvedCreateTableStmtNode)
	}
	return nil
}

func wrapCreateTableStmtBaseSlice(ps []*generated.AnyResolvedCreateTableStmtBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateTableStmtBase(p)
	}
	return nodes
}

func wrapCreateViewBase(p *generated.AnyResolvedCreateViewBaseProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedCreateViewBaseProto_ResolvedCreateViewStmtNode:
		return newCreateViewStmtNode(v.ResolvedCreateViewStmtNode)
	case *generated.AnyResolvedCreateViewBaseProto_ResolvedCreateMaterializedViewStmtNode:
		return newCreateMaterializedViewStmtNode(v.ResolvedCreateMaterializedViewStmtNode)
	case *generated.AnyResolvedCreateViewBaseProto_ResolvedCreateApproxViewStmtNode:
		return newCreateApproxViewStmtNode(v.ResolvedCreateApproxViewStmtNode)
	}
	return nil
}

func wrapCreateViewBaseSlice(ps []*generated.AnyResolvedCreateViewBaseProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapCreateViewBase(p)
	}
	return nodes
}

func wrapExpr(p *generated.AnyResolvedExprProto) ExprNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedExprProto_ResolvedLiteralNode:
		return newLiteralNode(v.ResolvedLiteralNode)
	case *generated.AnyResolvedExprProto_ResolvedParameterNode:
		return newParameterNode(v.ResolvedParameterNode)
	case *generated.AnyResolvedExprProto_ResolvedExpressionColumnNode:
		return newExpressionColumnNode(v.ResolvedExpressionColumnNode)
	case *generated.AnyResolvedExprProto_ResolvedColumnRefNode:
		return newColumnRefNode(v.ResolvedColumnRefNode)
	case *generated.AnyResolvedExprProto_ResolvedFunctionCallBaseNode:
		return wrapFunctionCallBase(v.ResolvedFunctionCallBaseNode)
	case *generated.AnyResolvedExprProto_ResolvedCastNode:
		return newCastNode(v.ResolvedCastNode)
	case *generated.AnyResolvedExprProto_ResolvedMakeStructNode:
		return newMakeStructNode(v.ResolvedMakeStructNode)
	case *generated.AnyResolvedExprProto_ResolvedMakeProtoNode:
		return newMakeProtoNode(v.ResolvedMakeProtoNode)
	case *generated.AnyResolvedExprProto_ResolvedGetStructFieldNode:
		return newGetStructFieldNode(v.ResolvedGetStructFieldNode)
	case *generated.AnyResolvedExprProto_ResolvedGetProtoFieldNode:
		return newGetProtoFieldNode(v.ResolvedGetProtoFieldNode)
	case *generated.AnyResolvedExprProto_ResolvedSubqueryExprNode:
		return newSubqueryExprNode(v.ResolvedSubqueryExprNode)
	case *generated.AnyResolvedExprProto_ResolvedDmldefaultNode:
		return newDMLDefaultNode(v.ResolvedDmldefaultNode)
	case *generated.AnyResolvedExprProto_ResolvedArgumentRefNode:
		return newArgumentRefNode(v.ResolvedArgumentRefNode)
	case *generated.AnyResolvedExprProto_ResolvedConstantNode:
		return newConstantNode(v.ResolvedConstantNode)
	case *generated.AnyResolvedExprProto_ResolvedReplaceFieldNode:
		return newReplaceFieldNode(v.ResolvedReplaceFieldNode)
	case *generated.AnyResolvedExprProto_ResolvedGetProtoOneofNode:
		return newGetProtoOneofNode(v.ResolvedGetProtoOneofNode)
	case *generated.AnyResolvedExprProto_ResolvedSystemVariableNode:
		return newSystemVariableNode(v.ResolvedSystemVariableNode)
	case *generated.AnyResolvedExprProto_ResolvedFlattenNode:
		return newFlattenNode(v.ResolvedFlattenNode)
	case *generated.AnyResolvedExprProto_ResolvedFlattenedArgNode:
		return newFlattenedArgNode(v.ResolvedFlattenedArgNode)
	case *generated.AnyResolvedExprProto_ResolvedGetJsonFieldNode:
		return newGetJsonFieldNode(v.ResolvedGetJsonFieldNode)
	case *generated.AnyResolvedExprProto_ResolvedFilterFieldNode:
		return newFilterFieldNode(v.ResolvedFilterFieldNode)
	case *generated.AnyResolvedExprProto_ResolvedWithExprNode:
		return newWithExprNode(v.ResolvedWithExprNode)
	case *generated.AnyResolvedExprProto_ResolvedCatalogColumnRefNode:
		return newCatalogColumnRefNode(v.ResolvedCatalogColumnRefNode)
	case *generated.AnyResolvedExprProto_ResolvedGraphGetElementPropertyNode:
		return newGraphGetElementPropertyNode(v.ResolvedGraphGetElementPropertyNode)
	case *generated.AnyResolvedExprProto_ResolvedGraphMakeElementNode:
		return newGraphMakeElementNode(v.ResolvedGraphMakeElementNode)
	case *generated.AnyResolvedExprProto_ResolvedArrayAggregateNode:
		return newArrayAggregateNode(v.ResolvedArrayAggregateNode)
	case *generated.AnyResolvedExprProto_ResolvedGraphIsLabeledPredicateNode:
		return newGraphIsLabeledPredicateNode(v.ResolvedGraphIsLabeledPredicateNode)
	case *generated.AnyResolvedExprProto_ResolvedUpdateConstructorNode:
		return newUpdateConstructorNode(v.ResolvedUpdateConstructorNode)
	case *generated.AnyResolvedExprProto_ResolvedGetRowFieldNode:
		return newGetRowFieldNode(v.ResolvedGetRowFieldNode)
	}
	return nil
}

func wrapExprSlice(ps []*generated.AnyResolvedExprProto) []ExprNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ExprNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapExpr(p)
	}
	return nodes
}

func wrapFunctionCallBase(p *generated.AnyResolvedFunctionCallBaseProto) ExprNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedFunctionCallBaseProto_ResolvedFunctionCallNode:
		return newFunctionCallNode(v.ResolvedFunctionCallNode)
	case *generated.AnyResolvedFunctionCallBaseProto_ResolvedNonScalarFunctionCallBaseNode:
		return wrapNonScalarFunctionCallBase(v.ResolvedNonScalarFunctionCallBaseNode)
	}
	return nil
}

func wrapFunctionCallBaseSlice(ps []*generated.AnyResolvedFunctionCallBaseProto) []ExprNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ExprNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapFunctionCallBase(p)
	}
	return nodes
}

func wrapGrantOrRevokeStmt(p *generated.AnyResolvedGrantOrRevokeStmtProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedGrantOrRevokeStmtProto_ResolvedGrantStmtNode:
		return newGrantStmtNode(v.ResolvedGrantStmtNode)
	case *generated.AnyResolvedGrantOrRevokeStmtProto_ResolvedRevokeStmtNode:
		return newRevokeStmtNode(v.ResolvedRevokeStmtNode)
	}
	return nil
}

func wrapGrantOrRevokeStmtSlice(ps []*generated.AnyResolvedGrantOrRevokeStmtProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGrantOrRevokeStmt(p)
	}
	return nodes
}

func wrapGraphElementScan(p *generated.AnyResolvedGraphElementScanProto) ScanNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedGraphElementScanProto_ResolvedGraphNodeScanNode:
		return newGraphNodeScanNode(v.ResolvedGraphNodeScanNode)
	case *generated.AnyResolvedGraphElementScanProto_ResolvedGraphEdgeScanNode:
		return newGraphEdgeScanNode(v.ResolvedGraphEdgeScanNode)
	}
	return nil
}

func wrapGraphElementScanSlice(ps []*generated.AnyResolvedGraphElementScanProto) []ScanNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ScanNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphElementScan(p)
	}
	return nodes
}

func wrapGraphLabelExpr(p *generated.AnyResolvedGraphLabelExprProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedGraphLabelExprProto_ResolvedGraphLabelNaryExprNode:
		return newGraphLabelNaryExprNode(v.ResolvedGraphLabelNaryExprNode)
	case *generated.AnyResolvedGraphLabelExprProto_ResolvedGraphLabelNode:
		return newGraphLabelNode(v.ResolvedGraphLabelNode)
	case *generated.AnyResolvedGraphLabelExprProto_ResolvedGraphWildCardLabelNode:
		return newGraphWildCardLabelNode(v.ResolvedGraphWildCardLabelNode)
	}
	return nil
}

func wrapGraphLabelExprSlice(ps []*generated.AnyResolvedGraphLabelExprProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphLabelExpr(p)
	}
	return nodes
}

func wrapGraphPathScanBase(p *generated.AnyResolvedGraphPathScanBaseProto) ScanNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedGraphPathScanBaseProto_ResolvedGraphElementScanNode:
		return wrapGraphElementScan(v.ResolvedGraphElementScanNode)
	case *generated.AnyResolvedGraphPathScanBaseProto_ResolvedGraphPathScanNode:
		return newGraphPathScanNode(v.ResolvedGraphPathScanNode)
	}
	return nil
}

func wrapGraphPathScanBaseSlice(ps []*generated.AnyResolvedGraphPathScanBaseProto) []ScanNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ScanNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphPathScanBase(p)
	}
	return nodes
}

func wrapGraphScanBase(p *generated.AnyResolvedGraphScanBaseProto) ScanNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedGraphScanBaseProto_ResolvedGraphScanNode:
		return newGraphScanNode(v.ResolvedGraphScanNode)
	case *generated.AnyResolvedGraphScanBaseProto_ResolvedGraphLinearScanNode:
		return newGraphLinearScanNode(v.ResolvedGraphLinearScanNode)
	}
	return nil
}

func wrapGraphScanBaseSlice(ps []*generated.AnyResolvedGraphScanBaseProto) []ScanNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ScanNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGraphScanBase(p)
	}
	return nodes
}

func wrapGroupingSetBase(p *generated.AnyResolvedGroupingSetBaseProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedGroupingSetBaseProto_ResolvedGroupingSetNode:
		return newGroupingSetNode(v.ResolvedGroupingSetNode)
	case *generated.AnyResolvedGroupingSetBaseProto_ResolvedRollupNode:
		return newRollupNode(v.ResolvedRollupNode)
	case *generated.AnyResolvedGroupingSetBaseProto_ResolvedCubeNode:
		return newCubeNode(v.ResolvedCubeNode)
	case *generated.AnyResolvedGroupingSetBaseProto_ResolvedGroupingSetListNode:
		return newGroupingSetListNode(v.ResolvedGroupingSetListNode)
	case *generated.AnyResolvedGroupingSetBaseProto_ResolvedGroupingSetProductNode:
		return newGroupingSetProductNode(v.ResolvedGroupingSetProductNode)
	}
	return nil
}

func wrapGroupingSetBaseSlice(ps []*generated.AnyResolvedGroupingSetBaseProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapGroupingSetBase(p)
	}
	return nodes
}

func wrapMatchRecognizePatternExpr(p *generated.AnyResolvedMatchRecognizePatternExprProto) ArgumentNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedMatchRecognizePatternExprProto_ResolvedMatchRecognizePatternEmptyNode:
		return newMatchRecognizePatternEmptyNode(v.ResolvedMatchRecognizePatternEmptyNode)
	case *generated.AnyResolvedMatchRecognizePatternExprProto_ResolvedMatchRecognizePatternVariableRefNode:
		return newMatchRecognizePatternVariableRefNode(v.ResolvedMatchRecognizePatternVariableRefNode)
	case *generated.AnyResolvedMatchRecognizePatternExprProto_ResolvedMatchRecognizePatternOperationNode:
		return newMatchRecognizePatternOperationNode(v.ResolvedMatchRecognizePatternOperationNode)
	case *generated.AnyResolvedMatchRecognizePatternExprProto_ResolvedMatchRecognizePatternQuantificationNode:
		return newMatchRecognizePatternQuantificationNode(v.ResolvedMatchRecognizePatternQuantificationNode)
	case *generated.AnyResolvedMatchRecognizePatternExprProto_ResolvedMatchRecognizePatternAnchorNode:
		return newMatchRecognizePatternAnchorNode(v.ResolvedMatchRecognizePatternAnchorNode)
	}
	return nil
}

func wrapMatchRecognizePatternExprSlice(ps []*generated.AnyResolvedMatchRecognizePatternExprProto) []ArgumentNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ArgumentNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapMatchRecognizePatternExpr(p)
	}
	return nodes
}

func wrapNode(p *generated.AnyResolvedNodeProto) Node {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedNodeProto_ResolvedArgumentNode:
		return wrapArgument(v.ResolvedArgumentNode)
	case *generated.AnyResolvedNodeProto_ResolvedExprNode:
		return wrapExpr(v.ResolvedExprNode)
	case *generated.AnyResolvedNodeProto_ResolvedScanNode:
		return wrapScan(v.ResolvedScanNode)
	case *generated.AnyResolvedNodeProto_ResolvedStatementNode:
		return wrapStatement(v.ResolvedStatementNode)
	}
	return nil
}

func wrapNodeSlice(ps []*generated.AnyResolvedNodeProto) []Node {
	if ps == nil {
		return nil
	}
	nodes := make([]Node, len(ps))
	for i, p := range ps {
		nodes[i] = wrapNode(p)
	}
	return nodes
}

func wrapNonScalarFunctionCallBase(p *generated.AnyResolvedNonScalarFunctionCallBaseProto) ExprNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedNonScalarFunctionCallBaseProto_ResolvedAggregateFunctionCallNode:
		return newAggregateFunctionCallNode(v.ResolvedAggregateFunctionCallNode)
	case *generated.AnyResolvedNonScalarFunctionCallBaseProto_ResolvedAnalyticFunctionCallNode:
		return newAnalyticFunctionCallNode(v.ResolvedAnalyticFunctionCallNode)
	}
	return nil
}

func wrapNonScalarFunctionCallBaseSlice(ps []*generated.AnyResolvedNonScalarFunctionCallBaseProto) []ExprNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ExprNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapNonScalarFunctionCallBase(p)
	}
	return nodes
}

func wrapScan(p *generated.AnyResolvedScanProto) ScanNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedScanProto_ResolvedSingleRowScanNode:
		return newSingleRowScanNode(v.ResolvedSingleRowScanNode)
	case *generated.AnyResolvedScanProto_ResolvedTableScanNode:
		return newTableScanNode(v.ResolvedTableScanNode)
	case *generated.AnyResolvedScanProto_ResolvedJoinScanNode:
		return newJoinScanNode(v.ResolvedJoinScanNode)
	case *generated.AnyResolvedScanProto_ResolvedArrayScanNode:
		return newArrayScanNode(v.ResolvedArrayScanNode)
	case *generated.AnyResolvedScanProto_ResolvedFilterScanNode:
		return newFilterScanNode(v.ResolvedFilterScanNode)
	case *generated.AnyResolvedScanProto_ResolvedSetOperationScanNode:
		return newSetOperationScanNode(v.ResolvedSetOperationScanNode)
	case *generated.AnyResolvedScanProto_ResolvedOrderByScanNode:
		return newOrderByScanNode(v.ResolvedOrderByScanNode)
	case *generated.AnyResolvedScanProto_ResolvedLimitOffsetScanNode:
		return newLimitOffsetScanNode(v.ResolvedLimitOffsetScanNode)
	case *generated.AnyResolvedScanProto_ResolvedWithRefScanNode:
		return newWithRefScanNode(v.ResolvedWithRefScanNode)
	case *generated.AnyResolvedScanProto_ResolvedAnalyticScanNode:
		return newAnalyticScanNode(v.ResolvedAnalyticScanNode)
	case *generated.AnyResolvedScanProto_ResolvedSampleScanNode:
		return newSampleScanNode(v.ResolvedSampleScanNode)
	case *generated.AnyResolvedScanProto_ResolvedProjectScanNode:
		return newProjectScanNode(v.ResolvedProjectScanNode)
	case *generated.AnyResolvedScanProto_ResolvedWithScanNode:
		return newWithScanNode(v.ResolvedWithScanNode)
	case *generated.AnyResolvedScanProto_ResolvedTvfscanNode:
		return newTVFScanNode(v.ResolvedTvfscanNode)
	case *generated.AnyResolvedScanProto_ResolvedRelationArgumentScanNode:
		return newRelationArgumentScanNode(v.ResolvedRelationArgumentScanNode)
	case *generated.AnyResolvedScanProto_ResolvedAggregateScanBaseNode:
		return wrapAggregateScanBase(v.ResolvedAggregateScanBaseNode)
	case *generated.AnyResolvedScanProto_ResolvedRecursiveRefScanNode:
		return newRecursiveRefScanNode(v.ResolvedRecursiveRefScanNode)
	case *generated.AnyResolvedScanProto_ResolvedRecursiveScanNode:
		return newRecursiveScanNode(v.ResolvedRecursiveScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPivotScanNode:
		return newPivotScanNode(v.ResolvedPivotScanNode)
	case *generated.AnyResolvedScanProto_ResolvedUnpivotScanNode:
		return newUnpivotScanNode(v.ResolvedUnpivotScanNode)
	case *generated.AnyResolvedScanProto_ResolvedGroupRowsScanNode:
		return newGroupRowsScanNode(v.ResolvedGroupRowsScanNode)
	case *generated.AnyResolvedScanProto_ResolvedExecuteAsRoleScanNode:
		return newExecuteAsRoleScanNode(v.ResolvedExecuteAsRoleScanNode)
	case *generated.AnyResolvedScanProto_ResolvedGraphTableScanNode:
		return newGraphTableScanNode(v.ResolvedGraphTableScanNode)
	case *generated.AnyResolvedScanProto_ResolvedGraphPathScanBaseNode:
		return wrapGraphPathScanBase(v.ResolvedGraphPathScanBaseNode)
	case *generated.AnyResolvedScanProto_ResolvedGraphScanBaseNode:
		return wrapGraphScanBase(v.ResolvedGraphScanBaseNode)
	case *generated.AnyResolvedScanProto_ResolvedGraphRefScanNode:
		return newGraphRefScanNode(v.ResolvedGraphRefScanNode)
	case *generated.AnyResolvedScanProto_ResolvedStaticDescribeScanNode:
		return newStaticDescribeScanNode(v.ResolvedStaticDescribeScanNode)
	case *generated.AnyResolvedScanProto_ResolvedAssertScanNode:
		return newAssertScanNode(v.ResolvedAssertScanNode)
	case *generated.AnyResolvedScanProto_ResolvedBarrierScanNode:
		return newBarrierScanNode(v.ResolvedBarrierScanNode)
	case *generated.AnyResolvedScanProto_ResolvedMatchRecognizeScanNode:
		return newMatchRecognizeScanNode(v.ResolvedMatchRecognizeScanNode)
	case *generated.AnyResolvedScanProto_ResolvedLogScanNode:
		return newLogScanNode(v.ResolvedLogScanNode)
	case *generated.AnyResolvedScanProto_ResolvedSubpipelineInputScanNode:
		return newSubpipelineInputScanNode(v.ResolvedSubpipelineInputScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPipeIfScanNode:
		return newPipeIfScanNode(v.ResolvedPipeIfScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPipeForkScanNode:
		return newPipeForkScanNode(v.ResolvedPipeForkScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPipeExportDataScanNode:
		return newPipeExportDataScanNode(v.ResolvedPipeExportDataScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPipeCreateTableScanNode:
		return newPipeCreateTableScanNode(v.ResolvedPipeCreateTableScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPipeTeeScanNode:
		return newPipeTeeScanNode(v.ResolvedPipeTeeScanNode)
	case *generated.AnyResolvedScanProto_ResolvedPipeInsertScanNode:
		return newPipeInsertScanNode(v.ResolvedPipeInsertScanNode)
	case *generated.AnyResolvedScanProto_ResolvedGraphCallScanNode:
		return newGraphCallScanNode(v.ResolvedGraphCallScanNode)
	case *generated.AnyResolvedScanProto_ResolvedDescribeScanNode:
		return newDescribeScanNode(v.ResolvedDescribeScanNode)
	case *generated.AnyResolvedScanProto_ResolvedUnsetArgumentScanNode:
		return newUnsetArgumentScanNode(v.ResolvedUnsetArgumentScanNode)
	}
	return nil
}

func wrapScanSlice(ps []*generated.AnyResolvedScanProto) []ScanNode {
	if ps == nil {
		return nil
	}
	nodes := make([]ScanNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapScan(p)
	}
	return nodes
}

func wrapStatement(p *generated.AnyResolvedStatementProto) StatementNode {
	if p == nil {
		return nil
	}
	switch v := p.Node.(type) {
	case *generated.AnyResolvedStatementProto_ResolvedExplainStmtNode:
		return newExplainStmtNode(v.ResolvedExplainStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedQueryStmtNode:
		return newQueryStmtNode(v.ResolvedQueryStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCreateStatementNode:
		return wrapCreateStatement(v.ResolvedCreateStatementNode)
	case *generated.AnyResolvedStatementProto_ResolvedExportDataStmtNode:
		return newExportDataStmtNode(v.ResolvedExportDataStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDefineTableStmtNode:
		return newDefineTableStmtNode(v.ResolvedDefineTableStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDescribeStmtNode:
		return newDescribeStmtNode(v.ResolvedDescribeStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedShowStmtNode:
		return newShowStmtNode(v.ResolvedShowStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedBeginStmtNode:
		return newBeginStmtNode(v.ResolvedBeginStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCommitStmtNode:
		return newCommitStmtNode(v.ResolvedCommitStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedRollbackStmtNode:
		return newRollbackStmtNode(v.ResolvedRollbackStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropStmtNode:
		return newDropStmtNode(v.ResolvedDropStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedInsertStmtNode:
		return newInsertStmtNode(v.ResolvedInsertStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDeleteStmtNode:
		return newDeleteStmtNode(v.ResolvedDeleteStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedUpdateStmtNode:
		return newUpdateStmtNode(v.ResolvedUpdateStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedGrantOrRevokeStmtNode:
		return wrapGrantOrRevokeStmt(v.ResolvedGrantOrRevokeStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAlterTableSetOptionsStmtNode:
		return newAlterTableSetOptionsStmtNode(v.ResolvedAlterTableSetOptionsStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedRenameStmtNode:
		return newRenameStmtNode(v.ResolvedRenameStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCreateRowAccessPolicyStmtNode:
		return newCreateRowAccessPolicyStmtNode(v.ResolvedCreateRowAccessPolicyStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropRowAccessPolicyStmtNode:
		return newDropRowAccessPolicyStmtNode(v.ResolvedDropRowAccessPolicyStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropFunctionStmtNode:
		return newDropFunctionStmtNode(v.ResolvedDropFunctionStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCallStmtNode:
		return newCallStmtNode(v.ResolvedCallStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedImportStmtNode:
		return newImportStmtNode(v.ResolvedImportStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedModuleStmtNode:
		return newModuleStmtNode(v.ResolvedModuleStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCreateDatabaseStmtNode:
		return newCreateDatabaseStmtNode(v.ResolvedCreateDatabaseStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAssertStmtNode:
		return newAssertStmtNode(v.ResolvedAssertStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedMergeStmtNode:
		return newMergeStmtNode(v.ResolvedMergeStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAlterObjectStmtNode:
		return wrapAlterObjectStmt(v.ResolvedAlterObjectStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedSetTransactionStmtNode:
		return newSetTransactionStmtNode(v.ResolvedSetTransactionStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropMaterializedViewStmtNode:
		return newDropMaterializedViewStmtNode(v.ResolvedDropMaterializedViewStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedStartBatchStmtNode:
		return newStartBatchStmtNode(v.ResolvedStartBatchStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedRunBatchStmtNode:
		return newRunBatchStmtNode(v.ResolvedRunBatchStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAbortBatchStmtNode:
		return newAbortBatchStmtNode(v.ResolvedAbortBatchStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedTruncateStmtNode:
		return newTruncateStmtNode(v.ResolvedTruncateStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedExecuteImmediateStmtNode:
		return newExecuteImmediateStmtNode(v.ResolvedExecuteImmediateStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAssignmentStmtNode:
		return newAssignmentStmtNode(v.ResolvedAssignmentStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedExportModelStmtNode:
		return newExportModelStmtNode(v.ResolvedExportModelStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropTableFunctionStmtNode:
		return newDropTableFunctionStmtNode(v.ResolvedDropTableFunctionStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCloneDataStmtNode:
		return newCloneDataStmtNode(v.ResolvedCloneDataStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAnalyzeStmtNode:
		return newAnalyzeStmtNode(v.ResolvedAnalyzeStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropSnapshotTableStmtNode:
		return newDropSnapshotTableStmtNode(v.ResolvedDropSnapshotTableStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedAuxLoadDataStmtNode:
		return newAuxLoadDataStmtNode(v.ResolvedAuxLoadDataStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropPrivilegeRestrictionStmtNode:
		return newDropPrivilegeRestrictionStmtNode(v.ResolvedDropPrivilegeRestrictionStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedUndropStmtNode:
		return newUndropStmtNode(v.ResolvedUndropStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedExportMetadataStmtNode:
		return newExportMetadataStmtNode(v.ResolvedExportMetadataStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedDropIndexStmtNode:
		return newDropIndexStmtNode(v.ResolvedDropIndexStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedGeneralizedQueryStmtNode:
		return newGeneralizedQueryStmtNode(v.ResolvedGeneralizedQueryStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedMultiStmtNode:
		return newMultiStmtNode(v.ResolvedMultiStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedCreateWithEntryStmtNode:
		return newCreateWithEntryStmtNode(v.ResolvedCreateWithEntryStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedSubpipelineStmtNode:
		return newSubpipelineStmtNode(v.ResolvedSubpipelineStmtNode)
	case *generated.AnyResolvedStatementProto_ResolvedStatementWithPipeOperatorsStmtNode:
		return newStatementWithPipeOperatorsStmtNode(v.ResolvedStatementWithPipeOperatorsStmtNode)
	}
	return nil
}

func wrapStatementSlice(ps []*generated.AnyResolvedStatementProto) []StatementNode {
	if ps == nil {
		return nil
	}
	nodes := make([]StatementNode, len(ps))
	for i, p := range ps {
		nodes[i] = wrapStatement(p)
	}
	return nodes
}
