// C++ bridge code - Connects ZetaSQL and WASM
#include <string>
#include <memory>
#include <cstring>
#include <vector>
#include <emscripten.h>

#include "zetasql/public/parse_resume_location.h"
#include "zetasql/public/parse_helpers.h"
#include "zetasql/public/analyzer.h"
#include "zetasql/public/simple_catalog.h"
#include "zetasql/public/builtin_function_options.h"
#include "zetasql/public/function.h"
#include "zetasql/public/language_options.h"
#include "zetasql/public/type.h"
#include "zetasql/public/type.pb.h"
#include "zetasql/resolved_ast/resolved_node.h"
#include "zetasql/resolved_ast/resolved_ast.pb.h"
#include "zetasql/resolved_ast/serialization.pb.h"
#include "zetasql/parser/parse_tree_serializer.h"
#include "zetasql/parser/parse_tree.pb.h"
#include "zetasql/proto/simple_catalog.pb.h"
#include "zetasql/proto/options.pb.h"
#include "zetasql/local_service/local_service.pb.h"

extern "C" {

// __wasm_call_ctors: Generated by LLVM/Emscripten to run C++ global constructors.
// Normally invoked via _start (with main) or _initialize (reactor mode), but this
// module uses --no-entry with an explicit EXPORTED_FUNCTIONS list, which prevents
// _initialize from being exported. We call it directly from init_module instead.
// ref: https://github.com/emscripten-core/emscripten/blob/main/system/lib/libc/crt1_reactor.c
extern void __wasm_call_ctors();

// Must be called by the host before any function that depends on C++ global state
// (e.g., AnalyzerOptions relies on abseil globals — without this, CHECK fails and aborts).
EMSCRIPTEN_KEEPALIVE
void init_module() {
    __wasm_call_ctors();
}

// ============ Debug functions ============
// These functions help identify where crashes occur
// Note: No try/catch used because Emscripten has exceptions disabled by default

// Test 1: Just return a string (basic WASM test)
EMSCRIPTEN_KEEPALIVE
char* debug_test_basic() {
    return strdup("debug_test_basic: OK");
}

// Test 2: Test SimpleCatalog creation
EMSCRIPTEN_KEEPALIVE
char* debug_test_catalog() {
    zetasql::SimpleCatalog catalog("test_catalog");
    return strdup("debug_test_catalog: OK - SimpleCatalog created");
}

// Test 3: Test SimpleCatalog with AddZetaSQLFunctions
EMSCRIPTEN_KEEPALIVE
char* debug_test_catalog_with_functions() {
    zetasql::SimpleCatalog catalog("test_catalog");
    catalog.AddZetaSQLFunctions();
    return strdup("debug_test_catalog_with_functions: OK - Functions added");
}

// Test 4: Test AnalyzerOptions creation with minimal settings
EMSCRIPTEN_KEEPALIVE
char* debug_test_analyzer_options() {
    // Create AnalyzerOptions with explicit language options to avoid
    // default initialization issues in WASM environment
    zetasql::AnalyzerOptions options;

    // Set minimal language options
    zetasql::LanguageOptions language_options;
    language_options.SetSupportsAllStatementKinds();
    options.set_language(language_options);

    return strdup("debug_test_analyzer_options: OK - AnalyzerOptions created");
}

// Test 5: Test full AnalyzeStatement with simple SQL
EMSCRIPTEN_KEEPALIVE
char* debug_test_analyze() {
    zetasql::SimpleCatalog catalog("test_catalog");
    catalog.AddZetaSQLFunctions();
    zetasql::AnalyzerOptions options;

    std::unique_ptr<const zetasql::AnalyzerOutput> output;
    absl::Status status = zetasql::AnalyzeStatement(
        "SELECT 1", options, &catalog, catalog.type_factory(), &output);

    if (!status.ok()) {
        std::string error = "debug_test_analyze: ANALYZE FAILED - " + status.ToString();
        return strdup(error.c_str());
    }
    return strdup("debug_test_analyze: OK - AnalyzeStatement succeeded");
}

// ============ End Debug functions ============

// Parse SQL and return AST string (legacy)
EMSCRIPTEN_KEEPALIVE
char* parse_statement(const char* sql) {
    std::string sql_str(sql);
    zetasql::ParserOptions options;

    std::unique_ptr<zetasql::ParserOutput> output;
    absl::Status status = zetasql::ParseStatement(
        sql_str, options, &output);

    if (!status.ok()) {
        std::string error = "Error: " + status.ToString();
        return strdup(error.c_str());
    }

    // Convert AST information to string
    std::string result = output->statement()->DebugString();
    return strdup(result.c_str());
}

// Parse SQL and return serialized Parse Tree AST proto bytes
// Uses ParseStatement + ParseTreeSerializer (does NOT require AnalyzeStatement)
// Returns: pointer to struct { size: uint32, data: uint8[] }
EMSCRIPTEN_KEEPALIVE
void* parse_statement_proto(const char* sql) {
    std::string sql_str(sql);
    zetasql::ParserOptions parser_options;

    std::unique_ptr<zetasql::ParserOutput> parser_output;
    absl::Status status = zetasql::ParseStatement(
        sql_str, parser_options, &parser_output);

    if (!status.ok()) {
        std::string error = "Error: " + status.ToString();
        uint32_t size = error.size();
        void* result = malloc(sizeof(uint32_t) + size + 1);
        memcpy(result, &size, sizeof(uint32_t));
        memcpy((char*)result + sizeof(uint32_t), error.c_str(), size + 1);
        return result;
    }

    // Serialize Parse Tree AST to proto using ParseTreeSerializer
    zetasql::AnyASTStatementProto proto;
    absl::Status serialize_status = zetasql::ParseTreeSerializer::Serialize(
        parser_output->statement(), &proto);

    if (!serialize_status.ok()) {
        std::string error = "Error serializing: " + serialize_status.ToString();
        uint32_t size = error.size();
        void* result = malloc(sizeof(uint32_t) + size + 1);
        memcpy(result, &size, sizeof(uint32_t));
        memcpy((char*)result + sizeof(uint32_t), error.c_str(), size + 1);
        return result;
    }

    // Serialize proto to bytes
    std::string serialized;
    if (!proto.SerializeToString(&serialized)) {
        std::string error = "Error: Failed to serialize proto";
        uint32_t size = error.size();
        void* result = malloc(sizeof(uint32_t) + size + 1);
        memcpy(result, &size, sizeof(uint32_t));
        memcpy((char*)result + sizeof(uint32_t), error.c_str(), size + 1);
        return result;
    }

    // Allocate memory for size + data
    uint32_t size = serialized.size();
    void* result = malloc(sizeof(uint32_t) + size);
    memcpy(result, &size, sizeof(uint32_t));
    memcpy((char*)result + sizeof(uint32_t), serialized.data(), size);

    return result;
}

// SQL analysis (catalog support to be implemented in the future if needed)
EMSCRIPTEN_KEEPALIVE
char* analyze_statement(const char* sql) {
    // TODO: Receive and analyze catalog information
    // Currently only returns parse results
    return parse_statement(sql);
}

// Helper: pack error into [size][data] format
static void* pack_error(const std::string& error_msg) {
    std::string error = "Error: " + error_msg;
    uint32_t size = error.size();
    void* result = malloc(sizeof(uint32_t) + size + 1);
    memcpy(result, &size, sizeof(uint32_t));
    memcpy((char*)result + sizeof(uint32_t), error.c_str(), size + 1);
    return result;
}

// Helper: pack proto bytes into [size][data] format
static void* pack_proto(const std::string& serialized) {
    uint32_t size = serialized.size();
    void* result = malloc(sizeof(uint32_t) + size);
    memcpy(result, &size, sizeof(uint32_t));
    memcpy((char*)result + sizeof(uint32_t), serialized.data(), size);
    return result;
}

// Helper: build FunctionArgumentType from proto
static zetasql::FunctionArgumentType build_function_arg_type(
    const zetasql::FunctionArgumentTypeProto& proto,
    zetasql::TypeFactory* type_factory) {
    auto kind = proto.kind();
    if (kind == zetasql::ARG_TYPE_FIXED && proto.has_type()) {
        const zetasql::Type* type = nullptr;
        google::protobuf::DescriptorPool pool(
            google::protobuf::DescriptorPool::generated_pool());
        auto status = type_factory->DeserializeFromSelfContainedProto(
            proto.type(), &pool, &type);
        if (status.ok() && type != nullptr) {
            return zetasql::FunctionArgumentType(type);
        }
    }
    // Templated argument (ARG_TYPE_ANY_1, ARG_TYPE_ANY_2, etc.)
    return zetasql::FunctionArgumentType(kind);
}

// Helper: build SimpleCatalog from proto
static absl::Status build_catalog_from_proto(
    const zetasql::SimpleCatalogProto& catalog_proto,
    zetasql::TypeFactory* type_factory,
    std::unique_ptr<zetasql::SimpleCatalog>* out_catalog) {

    auto catalog = std::make_unique<zetasql::SimpleCatalog>(
        catalog_proto.has_name() ? catalog_proto.name() : "catalog",
        type_factory);

    // Add builtin functions if requested
    if (catalog_proto.has_builtin_function_options()) {
        catalog->AddZetaSQLFunctions(
            zetasql::ZetaSQLBuiltinFunctionOptions(
                catalog_proto.builtin_function_options()));
    }

    // Add tables
    for (const auto& table_proto : catalog_proto.table()) {
        std::string table_name = table_proto.has_name() ? table_proto.name() : "";
        bool is_value_table = table_proto.has_is_value_table() && table_proto.is_value_table();

        std::vector<zetasql::SimpleTable::NameAndType> columns;
        for (const auto& col_proto : table_proto.column()) {
            std::string col_name = col_proto.has_name() ? col_proto.name() : "";
            const zetasql::Type* col_type = nullptr;

            if (col_proto.has_type()) {
                google::protobuf::DescriptorPool pool(
                    google::protobuf::DescriptorPool::generated_pool());
                absl::Status type_status = type_factory->DeserializeFromSelfContainedProto(
                    col_proto.type(), &pool, &col_type);
                if (!type_status.ok()) {
                    return type_status;
                }
            } else {
                col_type = zetasql::types::Int64Type();
            }
            columns.push_back({col_name, col_type});
        }

        auto table = new zetasql::SimpleTable(table_name, columns);
        if (is_value_table) {
            table->set_is_value_table(true);
        }
        catalog->AddOwnedTable(table);
    }

    // Add custom functions
    for (const auto& fn_proto : catalog_proto.custom_function()) {
        std::vector<std::string> name_path(
            fn_proto.name_path().begin(), fn_proto.name_path().end());
        std::string group = fn_proto.has_group() ? fn_proto.group() : "";
        auto mode = static_cast<zetasql::Function::Mode>(fn_proto.mode());

        std::vector<zetasql::FunctionSignature> signatures;
        for (const auto& sig_proto : fn_proto.signature()) {
            zetasql::FunctionArgumentType return_type =
                build_function_arg_type(sig_proto.return_type(), type_factory);

            zetasql::FunctionArgumentTypeList arguments;
            for (const auto& arg_proto : sig_proto.argument()) {
                arguments.push_back(
                    build_function_arg_type(arg_proto, type_factory));
            }

            int64_t context_id = sig_proto.has_context_id()
                ? sig_proto.context_id() : -1;
            signatures.push_back(
                zetasql::FunctionSignature(return_type, arguments, context_id));
        }

        auto* function = new zetasql::Function(
            name_path, group, mode, signatures);
        catalog->AddOwnedFunction(function);
    }

    // Add sub-catalogs recursively
    for (const auto& sub_proto : catalog_proto.catalog()) {
        std::unique_ptr<zetasql::SimpleCatalog> sub_catalog;
        auto status = build_catalog_from_proto(sub_proto, type_factory, &sub_catalog);
        if (!status.ok()) return status;
        catalog->AddOwnedCatalog(sub_catalog.release());
    }

    *out_catalog = std::move(catalog);
    return absl::OkStatus();
}

// Analyze SQL statement using protobuf request/response
// request_ptr: pointer to serialized AnalyzeRequest proto bytes
// request_size: size of the request bytes
// Returns: pointer to [uint32 size][AnalyzeResponse proto bytes] or [uint32 size][error string]
EMSCRIPTEN_KEEPALIVE
void* analyze_statement_proto(const void* request_ptr, uint32_t request_size) {
    // Deserialize AnalyzeRequest
    zetasql::local_service::AnalyzeRequest request;
    if (!request.ParseFromArray(request_ptr, request_size)) {
        return pack_error("Failed to parse AnalyzeRequest proto");
    }

    // Determine target type
    bool is_next_statement = request.has_parse_resume_location();
    std::string sql;
    if (request.has_sql_statement()) {
        sql = request.sql_statement();
    } else if (is_next_statement) {
        sql = request.parse_resume_location().input();
    } else {
        return pack_error("AnalyzeRequest must contain sql_statement or parse_resume_location");
    }

    // Build TypeFactory (needed for catalog and analyzer)
    zetasql::TypeFactory type_factory;

    // Build catalog from proto
    std::unique_ptr<zetasql::SimpleCatalog> catalog;
    if (request.has_simple_catalog()) {
        absl::Status cat_status = build_catalog_from_proto(
            request.simple_catalog(), &type_factory, &catalog);
        if (!cat_status.ok()) {
            return pack_error("Failed to build catalog: " + cat_status.ToString());
        }
    } else {
        // Empty catalog with builtins
        catalog = std::make_unique<zetasql::SimpleCatalog>("default", &type_factory);
        catalog->AddZetaSQLFunctions();
    }

    // Build AnalyzerOptions from proto
    zetasql::AnalyzerOptions options;
    if (request.has_options() && request.options().has_language_options()) {
        zetasql::LanguageOptions language_options(
            request.options().language_options());
        options.set_language(language_options);
    } else {
        // Default: support all statement kinds
        zetasql::LanguageOptions language_options;
        language_options.SetSupportsAllStatementKinds();
        options.set_language(language_options);
    }

    // Set parse location record type if specified
    if (request.has_options() && request.options().has_parse_location_record_type()) {
        options.set_parse_location_record_type(
            static_cast<zetasql::ParseLocationRecordType>(
                request.options().parse_location_record_type()));
    }

    // Run analysis
    std::unique_ptr<const zetasql::AnalyzerOutput> output;
    absl::Status status;

    if (is_next_statement) {
        // Multi-statement: use AnalyzeNextStatement
        zetasql::ParseResumeLocation resume_location =
            zetasql::ParseResumeLocation::FromStringView(sql);
        resume_location.set_byte_position(
            request.parse_resume_location().byte_position());

        bool at_end_of_input = false;
        status = zetasql::AnalyzeNextStatement(
            &resume_location, options, catalog.get(), &type_factory,
            &output, &at_end_of_input);

        if (!status.ok()) {
            return pack_error(status.ToString());
        }

        // Serialize resolved AST to proto
        zetasql::FileDescriptorSetMap file_descriptor_set_map;
        zetasql::AnyResolvedStatementProto resolved_proto;
        absl::Status save_status = output->resolved_statement()->SaveTo(
            &file_descriptor_set_map, &resolved_proto);
        if (!save_status.ok()) {
            return pack_error("Failed to serialize resolved AST: " + save_status.ToString());
        }

        // Build AnalyzeResponse with resume position
        zetasql::local_service::AnalyzeResponse response;
        *response.mutable_resolved_statement() = resolved_proto;
        response.set_resume_byte_position(resume_location.byte_position());

        std::string serialized;
        if (!response.SerializeToString(&serialized)) {
            return pack_error("Failed to serialize AnalyzeResponse");
        }
        return pack_proto(serialized);
    }

    // Single statement: use AnalyzeStatement
    status = zetasql::AnalyzeStatement(
        sql, options, catalog.get(), &type_factory, &output);

    if (!status.ok()) {
        return pack_error(status.ToString());
    }

    // Serialize resolved AST to proto
    zetasql::FileDescriptorSetMap file_descriptor_set_map;
    zetasql::AnyResolvedStatementProto resolved_proto;
    absl::Status save_status = output->resolved_statement()->SaveTo(
        &file_descriptor_set_map, &resolved_proto);
    if (!save_status.ok()) {
        return pack_error("Failed to serialize resolved AST: " + save_status.ToString());
    }

    // Build AnalyzeResponse
    zetasql::local_service::AnalyzeResponse response;
    *response.mutable_resolved_statement() = resolved_proto;

    // Serialize response to bytes
    std::string serialized;
    if (!response.SerializeToString(&serialized)) {
        return pack_error("Failed to serialize AnalyzeResponse");
    }

    return pack_proto(serialized);
}

// Free memory
EMSCRIPTEN_KEEPALIVE
void free_string(char* ptr) {
    free(ptr);
}

// Free proto buffer memory
EMSCRIPTEN_KEEPALIVE
void free_proto_buffer(void* ptr) {
    free(ptr);
}

} // extern "C"
